### ISSUE TITLE
Implement setup script for image metadata

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#10]
### Documentation
Story: [User saves image preview](https://github.com/magento/adobe-stock-integration/issues/26)
App Design Documen: [Save preview image design](https://github.com/magento/adobe-stock-integration/wiki/Save-preview-image-design)

### Description
- Introduce new tables in the database as image metadata storage
- Tables structure is described in [Database](https://github.com/magento/adobe-stock-integration/wiki/Database) document

### QA notes
- Table created according to the design.

**Comment by igor-imaginemage** [comment]
Hi @sidolov, I created a PR for this issue

https://github.com/magento/adobe-stock-integration/pull/49
