### ISSUE TITLE
Search for 0 - doesn't work

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#100]
### Preconditions:
1. php bin/magento config:set adobe_stock/integration/enabled 1
2. php bin/magento config:set adobe_stock/integration/api_key \<key\>
3. php bin/magento config:set cms/wysiwyg/enabled disabled
4. php bin/magento config:set admin/security/admin_account_sharing 1
5. php bin/magento config:set admin/security/use_form_key 0
6. php bin/magento cache:flush

### Steps to reproduce:
1. Navigate to Content > Elements > Pages
2. Click Add New Page button
3. Fill Title with "Test CMS Page"
4. Expand the "Content" section
5. Fill Content Heading with "Test Content Heading"
6. Click "Insert Image..." button
7. Click "Search Adobe Stock" button
8. Type `0` in the search input
9. Submit search

### Expected result:
:heavy_check_mark: 1. Images similar to `00`, `zero`, `O` requests.

### Actual result
:x: 1. Initial images.

**Comment by dmytrokaplin** [comment]
Hi @TomashKhamlai  @sivaschenko 

I investigated this issue. I have bad news.
1. PHP treats 0 as an empty string and as result, Magento 2 doesn't see search parameter. Look [here](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Ui/Component/Filters/Type/Search.php#L37)
2. adobe/stock-api-libphp throws an exception if you call method setWords from AdobeStock\Api\Models\SearchParameters with string '0' or 0. Look [here](https://github.com/adobe/stock-api-libphp/blob/master/src/Models/SearchParameters.php#L517).

**Comment by sivaschenko** [comment]
Hi @jaysmook thanks for investigation!

Considering the investigation results I think that the issue can be fixed by 2 pull requests introducing more strict value checks to:
1. https://github.com/magento/magento2
2. https://github.com/adobe/stock-api-libphp/

**Comment by engcom-Golf** [comment]
Related issue: [magento/magento2:23424](https://github.com/magento/magento2/issues/23424)

**Comment by sivaschenko** [comment]
Waiting for https://github.com/adobe/stock-api-libphp/pull/7 to be merged

**Comment by sidolov** [comment]
@chfabbro , do you have any estimates when https://github.com/adobe/stock-api-libphp/pull/7 may be merged to the SDK? Thanks!

**Comment by chfabbro** [comment]
@sidolov I just added some comments. There is a typo, and I'm not sure if this is the correct fix.
