### ISSUE TITLE
New folder is not created after hitting Enter key in "Create Folder" window [Media Gallery]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1001]
### Preconditions (*)
Magento 2.3.5-alpha2 (but reproducible on all Magento versions with ASI installed)

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select, for example, _Storage Root_ and click **Create Folder** button
4. Type any _name_
5. Hit **Enter key** from keyboard

### Expected result (*)
The folder is successfully created, like on Magento 2.4-develop
![create_new_folder_enter key_mage24-develop](https://user-images.githubusercontent.com/45624059/76856176-6724d080-685b-11ea-83b2-13f88bb95a2f.gif)

### Actual result (*)
The folder is not created, _Content - Pages - Add New Page_ is opened
![create_new_folder_enter key](https://user-images.githubusercontent.com/45624059/76856341-be2aa580-685b-11ea-8581-fbce9cd5ce0c.gif)

### Additional info
This is an Adobe Stock Integration bug, because this behavior is not reproducible on a "clean" Magento 2.4-develop

**Comment by mmezhensky** [comment]
Hello @chalov-anton

I can not reproduce it, and it is worked for me now. (2.4-dev + ASI)

![New Page _ Pages _ Elements _ Content _ Magento Admin](https://user-images.githubusercontent.com/60603281/78356170-b7b85f80-75b7-11ea-9328-4cd1c574ae3f.gif)

Could you, please, clarify this issue?

Thank you!

**Comment by chalov-anton** [comment]
Hello @mmezhensky 

I have just rechecked this and it is no longer reproducible. It seems to be fixed in the latest codebase.  

Thank you for your comment. 
I'm closing this issue.
