### ISSUE TITLE
Confirm Save Preview is performed if click outside of the Search Adobe Stock when File Name window is opened

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1002]
### Preconditions (*)
Magento 2.3.5-alpha2 (but reproducible on all Magento versions with ASI installed)

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** and select any image so that Preview is opened 
4. Click **Save Preview** button ( _Save Preview_ window appears. do not Confirm)
5. Move the mouse cursor to the Magento Left vertical toolbar (Dashboard, Sales, Catalog, Customer...), and perform Left mouse click 

### Expected result (*)
Image Preview is not saved. Nothing happens OR the Search Adobe Stock is closed, but the Image Preview is still not saved 

### Actual result (*)
**Confirm** action is performed. The image Preview is saved to the Media Gallery
![confirm_preview_1](https://user-images.githubusercontent.com/45624059/76954953-f09ad800-6919-11ea-88c1-d25bc97c02e4.gif)

**Comment by serhiyzhovnir** [comment]
The PR for fixing this issue is created for core repository: https://github.com/magento/magento2/pull/27399
Thank you!
