### ISSUE TITLE
Licensing is not available from image properties (three dots) [Media Gallery]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1090]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)
4. Have an _Unlicensed_ image saved in Media Gallery from Adobe Stock. The image must have _Unlicensed_ label 

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select an image with _Unlicensed_ label added from Adobe Stock with 
4. Click on three dots near the image and select **View Details**
5. Verify **License** button

### Expected result (*)
According to the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/58ed48b8-06fe-4cab-91a0-87d3708ccc3e/Gallery-item-dropdown-unlicensed/) the **License** button must be available 

### Actual result (*)
No **License** button
![no_license button](https://user-images.githubusercontent.com/45624059/78115510-91ee5780-740b-11ea-9a40-c712fa8e048c.png)

**Comment by sivaschenko** [comment]
Duplicate to https://github.com/magento/adobe-stock-integration/issues/910
