### ISSUE TITLE
Add "Rename Folder" functionality [Media Gallery]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1092]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)
4. A folder created in _folder tree_ 

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select an already existing folder from the folder tree
4. Verify **Rename Folder** button

### Expected result (*)
**Rename Folder** button available

### Actual result (*)
The **Rename Folder** button is missing 
![rename_folder](https://user-images.githubusercontent.com/45624059/78119611-5fdff400-7411-11ea-81a3-906f256fc853.png)

**Comment by sivaschenko** [comment]
The old media gallery does not allow to rename a folder, so it's not necessary to implement this functionality at this point. Keeping this feature request in the backlog for the phase 4

**Comment by Nazar65** [comment]
There is few issues with rename folder functionality from backend side, If we change the folder name with a lot of images, we need to run media-gallery:synchronization, it will takes long time to finish even with run it asynchronus, media-gallery images will have broken images until synchronization not complete, the second issue is about that images that were used in products or pages will be broken.

**Comment by sivaschenko** [comment]
Renaming a folder is an insecure operation that could lead to potentially broken frontend and any content where the assets from the folder have been used.
For a better understanding of consequences, it's better to let admin user to delete and recreate a folder instead
