### ISSUE TITLE
[MFTF] User deletes images using Delete button

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1094]
# Description
Implement MFTF test to cover scenario: "User deletes images contextually" (story 42, #461)

#  Preconditions

1. Admin User is logged into Admin Panel
2. Two images is saved in the Media Gallery

# Test steps

1. Open Media Gallery
2. Select an image
2. Click delete button
3. Confirm the confimation popup
4. User sees the image disappear from the gallery. The image information is deleted from the data base. Image file and all the renditions are deleted from the media server
5. User selects other image to delete and doesn't see the confirmation message.

**Comment by sivaschenko** [comment]
@konarshankar07 are you working on this issue?

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Sorry, I missed this task and working on it and try to finish latest in this week
Thanks
