### ISSUE TITLE
The "Licensed" label disappears from images in Adobe Stock grid if the Enhanced Media Gallery is enabled

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1106]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)
4. Have licensed images in the Adobe Stock grid

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock**
4. Sign In Adobe Stock 
5. Switch between pages and verify the _Licensed_ label

### Expected result (*)
_Licensed_ label on all Licensed images

### Actual result (*)
The _Licensed_ label appears for a while and disappears
![licensed_label](https://user-images.githubusercontent.com/45624059/78235534-6fc70900-74e1-11ea-9f4e-4ba702c6c815.gif)

### Note
- not reproducible if Enhanced Media Gallery **is disabled**

**Comment by gabrieldagama** [comment]
This issue is probably linked to #1028, I've created a PR to fix this issue: https://github.com/magento/adobe-stock-integration/pull/1129

**Comment by Nazar65** [comment]
@gabriel-webjump could you please verify if issue fixed in your pr ? If yes, link it in fixed issue section, thanks

**Comment by gabrieldagama** [comment]
Hi @Nazar65, yes this issue is fixed with my PR. Thanks.
