### ISSUE TITLE
[MFTF] Cover filtering images by their keywords in Standalone Media Gallery

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1121]
**Do not proceed yet. The steps need to be edited** 

### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
Admin user is logged in to admin panel
Adobe Stock API credentials are saved in configuration
Adobe Stock Preview image exists in gallery
User navigate to Content - Media - Media Gallery
Manage Gallery is opened
Assert that the Search by keyword field exists
Type a name of the existing image from Media Gallery
User click Search or hit Enter key
User sees the image grid updated and images that have the selected 'keyword' are displayed
User sees images sorted by the 'upload date'
Click some button to reset the filter
User can drop the filter by 'keyword' and sees the initial state of the Media Gallery

### Note (*)
Test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/4503803

**Comment by konarshankar07** [comment]
@magento I'm working on this issue

**Comment by konarshankar07** [comment]
@magento I'm working on this
