### ISSUE TITLE
"Technical problem with the server..." and "File validation failed." error messages appear if try to Upload an unsupported file type 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1123]
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)
4. An image added to Media Gallery

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select a folder from the folder tree 
4. Click **Upload Image** button
5. Select an unsupported file from your local machine, txt for example and click Open

### Expected result (*)
A propper message like on NOT Enhanced Media Gallery
![not_enhanced_file_size](https://user-images.githubusercontent.com/45624059/78362790-5bf3d380-75c3-11ea-9cae-7f7f72fc857f.png)

### Actual result (*)
:x: _Technical problem with the server..._ and :x: _File validation failed._ error messages appear
![enhanced_file_type_](https://user-images.githubusercontent.com/45624059/78362841-75951b00-75c3-11ea-94c2-ae824571171d.png)

**Comment by lenaorobei** [comment]
Closing ion favor of https://github.com/magento/adobe-stock-integration/issues/1193
