### ISSUE TITLE
"Technical problem with the server..." and "An error occurred on attempt to uploaded the image." error messages appear if try to Upload an image with more then 5 MB size

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1124]
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)
4. An image added to Media Gallery

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select a folder from the folder tree 
4. Click **Upload Image** button
5. Select an image file from your local machine, which has size over 5 MB, and click Open

### Expected result (*)
A proper message like on NOT Enhanced Media Gallery
![not_enhanced_file_size](https://user-images.githubusercontent.com/45624059/78363188-ff44e880-75c3-11ea-9acd-71a51512281e.png)

### Actual result (*)
:x: _Technical problem with the server..._ and :x: _An error occurred on attempt to uploaded the image._ error messages appear
![enhanced_file_type_](https://user-images.githubusercontent.com/45624059/78362841-75951b00-75c3-11ea-94c2-ae824571171d.png)

**Comment by lenaorobei** [comment]
Closing ion favor of https://github.com/magento/adobe-stock-integration/issues/1193
