### ISSUE TITLE
The "time" info is displayed on another line than "date" for Images Uploaded locally   

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1125]
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Select a folder from the folder tree 
4. Click **Upload Image** button, select an image file from your local machine and click Open
5. Select the previously uploaded image and click on "three dots" select **View Details**

### Expected result (*)
Date and time are on different lines
![details](https://user-images.githubusercontent.com/45624059/78365748-37e6c100-75c8-11ea-9c74-82ca26591fc8.png)

### Actual result (*)
Date and time are on the same line
![details_expected](https://user-images.githubusercontent.com/45624059/78365813-4f25ae80-75c8-11ea-970b-07ac5905c468.png)

**Comment by Nazar65** [comment]
Already fixed in -> https://github.com/magento/adobe-stock-integration/pull/1110
