### ISSUE TITLE
Integration name input is not visible on Adobe Stock Integration configuration panel

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#113]
Related to #29 

### Expected result:
Integration name is visible
![download](https://user-images.githubusercontent.com/11827230/59853956-9cf36200-937a-11e9-8a7b-bb81d394ec5d.png)

### Actual result:
Integration name is not visible
![image](https://user-images.githubusercontent.com/11827230/59854081-da57ef80-937a-11e9-9487-b2de4797624f.png)

**Comment by sidolov** [comment]
@TomashKhamlai we decided with PO to keep integration name hidden. Mockups are outdated.
