### ISSUE TITLE
[MFTF] User views basic image attributes in Standalone Media Gallery

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1137]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
Admin user is logged in to admin panel
Adobe Stock API credentials are saved in configuration
Adobe Stock Licensed image exists in gallery
User navigate to Content - Media - Media Gallery
Media Gallery is opened
Select a Licensed Image by clicking on it
User clicks on three dots in the bottom right
User click View Details
Image Details window is opened

### Expected Result (*)
title, type, dimensions, size, creation date, keywords, source,  and stock id attributes are displayed

### Note (*)
Test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/4503223

**Comment by coderimus** [comment]
This request is dependent on next changes https://github.com/magento/adobe-stock-integration/pull/1149

**Comment by coderimus** [comment]
This PR is in progress. I am working on it. Plan to finish it this week or in the middle of the next one.
