### ISSUE TITLE
Assorted issues reported by PM

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1143]
1. <duplicate #1074> The whole image tile in the Media Gallery area should be clickable 
<img width="228" alt="Screen Shot 2020-04-06 at 11 49 03 AM" src="https://user-images.githubusercontent.com/5603216/78584374-c1cb9f80-77fd-11ea-8690-052ee170daf8.png">
2.  new Stories: read and write meta data

 Image manual upload should extract image meta data and display it in media gallery:

-  _Image title_ to be displayed as a header in image details and under the image thumbnail in the Media Gallery. If there is no _image title_ in the meta data - use _image name_.
- keywords to be displayed in the image details in case of manual image upload
3. If user updates keywords in Media Gallery, can we update the file meta data as well? 
4.  new bug
 Allow multiple image selection when uploading new images in Media Gallery with file browser. Old gallery supported that. New one doesn't. 
5. New sorting: newest first (default), oldest fist. when images uploaded, show success message with the link to show them (sorting by newest first)

When file is uploaded, it's not in the viewport because images in the gallery are sorted the way, file is added to X page. So it looks like the file is not uploaded at all. Need @belbiy to help with the solution
6. Navigation bar doesn't match the mockup
<img width="804" alt="Screen Shot 2020-04-07 at 11 08 25 AM" src="https://user-images.githubusercontent.com/5603216/78692907-30713180-78c0-11ea-8b30-7cc36f5e2853.png">
<img width="674" alt="Screen Shot 2020-04-07 at 11 09 16 AM" src="https://user-images.githubusercontent.com/5603216/78692984-43840180-78c0-11ea-8e37-555620ff27f6.png">
7. On uploading unsupported file formats, Magento tries to upload the asset, but server side declines the file. Need to have storefront validation. 
<img width="1153" alt="Screen Shot 2020-04-07 at 11 16 59 AM" src="https://user-images.githubusercontent.com/5603216/78693860-72e73e00-78c1-11ea-82d8-53347b934fc6.png">
8. issues with Page Builder:

- create a page
- select an image form the gallery 
- close the gallery and content type configuration panel
- observe the page with the image inserted 
- go back to configuration and open the media gallery to replace the image. 
- ❌ Gallery doesn't load

<img width="1704" alt="Screen Shot 2020-04-07 at 11 59 43 AM" src="https://user-images.githubusercontent.com/5603216/78698019-4b936f80-78c7-11ea-8898-02d4f950a2bb.png">
9. Sorting by upload date doesn't work. 

- Upload the image and sort by date 
- ❌ Observe that image you uploaded is not first one

10. new bug 
Image details for uploaded files and saved from stock look very different; local images look broken 

11. review #717 if we have time to understand the options to expand functionality in the future

**Comment by sivaschenko** [comment]
Duplicate to https://github.com/magento/adobe-stock-integration/issues/1074
