### ISSUE TITLE
An error occurred during delete folder from a media gallery.

### ISSUE THREAD

**Issue by coderimus** [magento/adobe-stock-integration#1144]
### Preconditions (*)
Preconditions: use the latest 1.1-develop branch.
Disable Enhanced Media Gallery: Stores -> Settings -> Configuration -> Advanced -> System -> Enhanced Media Gallery -> Enabled -> No

### Steps to reproduce (*)
Go to the Catalog -> Categories
Select the default one
Press Content -> Select from Gallery
At the open media, gallery menu try to delete a folder
Next error occurred:
![image](https://user-images.githubusercontent.com/5318512/78586101-9c618480-7843-11ea-8cb2-b59452e495bd.png)

and a media gallery window is blocked
![image](https://user-images.githubusercontent.com/5318512/78586191-c450e800-7843-11ea-92c5-1d44ea79f20e.png)

### Expected result (*)
A folder can be deleted and page is unblocked

### Actual result (*)
A folder is deleted physically but a javascript error occurred and page became blocked.

**Comment by Nazar65** [comment]
Pull Request opened at magento 2 repository https://github.com/magento/magento2/pull/27652

**Comment by Nazar65** [comment]
I'm Closing,  as this already merged to 2.4-develop
