### ISSUE TITLE
[Documentation] Changes caused by #106 should be reflected in Adobe-Stock-Image-Search-Design Wiki page

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#115]
Changes introduced by #106 should be reflected in [Adobe-Stock-Image-Search-Design Wiki](https://github.com/magento/adobe-stock-integration/wiki/Adobe-Stock-Image-Search-Design) page.

### Expected result:
:heavy_check_mark: Table Search Parameters -> "Values" for "Name"("Per page") 32 (default); 48; 64

### Actual result:
:x: Table Search Parameters -> "Values" for "Name"("Per page") 32 (default); 64

**Comment by rogyar** [comment]
Hi @TomashKhamlai. I've just adjusted the corresponding wiki page
https://github.com/magento/adobe-stock-integration/wiki/Adobe-Stock-Image-Search-Design

**Comment by TomashKhamlai** [comment]
Thank you
