### ISSUE TITLE
Configuration can be saved with not valid API key

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#116]
Related to #29

### Preconditions:
1. Go to **Steps to reproduce** section

### Steps to reproduce:
1. Execute magentoCLI command
`php bin/magento config:set adobe_stock/integration/api_key ""`
2. Execute magentoCLI command
`php bin/magento config:set adobe_stock/integration/enabled 0`
3. Before - LoginAsAdmin
4. User navigates to Stores > Settings > Configuration
5. Page reloads
6. User expands `Advanced` tab
7. User clicks on `System` section
8. Page reloads
9. Location is `admin/system_config/edit/section/system/`
10. User expands "Adobe Stock Integration" expandable section
11. User sets "Enabled Adobe Stock" to "Yes"
12. Find input field labeled by `Api Key` label
13. Input field is in empty state
14. User fills next string to the `API Key` input
`adobeadobeadobeadobeadobeadobe`
15. User clicks `Test Connection` button
16. `Key is invalid. Try a different key.` appears
17. User clicks `Connection failed! Test again?` button
18. `Key is invalid. Try a different key.` appears
19. User clicks `Save Config` button

### Expected result:
:heavy_check_mark: 1. Configuration is successfully saved

### Actual result
:x: 1. `Key is invalid. Try a different key.` appears

**Comment by sivaschenko** [comment]
I don't think thats an issue. @tkacheva I think we should allow saving API key without verification (i.e. to be able to workaround missing network connection to Adobe Stock). However, the ability to test the API key before saving the configuration will be introduced in https://github.com/magento/adobe-stock-integration/pull/126

What do you think about it?
