### ISSUE TITLE
Filters do not have initial values applied according to Stories

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#118]
### Steps to reproduce: 
1. Before - LoginAsAdmin
2. Navigate to Catalog > Categories
3. Click on the `Default Category` in the category tree
4. Page reloads
5. `Default Category` is currently selected category
6. User clicks `Add Subcategory` button
7. Type `Sales` in the `Category Name` field
8. User clicks `Save` button
9. Category `Sales` is saved and is a direct child of the `Default Category`
10. Navigate to Catalog > Categories
11. User clicks on the `Sales` in the category tree
12. Page reloads
13. Expand the "Content" section
14. User clicks `Select from Gallery` button
15. Media Gallery slide out panel appears
16. User clicks `Search Adobe Stock` button
17. `Adobe Stock` slide out panel appears
18. User clicks `Filters` button

### Expected result:
:heavy_check_mark: User sees `Cancel` and `Apply Filters` buttons
:heavy_check_mark: User sees label and input for each filter from the list: Orientation, Price, Offensive, Isolated images only, Subcategory, Color.
:heavy_check_mark: User sees the default filter `Only safe` applied in Offensive filter. It displays images that do not include adult content
:heavy_check_mark: All is set to default instead of `Select...` and `Select...` option is not one of the available options for Price filters.
:heavy_check_mark: User sees the default filter "All" applied in the Orientation filter

### Actual result:
:heavy_check_mark: User sees `Cancel` and `Apply Filters` buttons
:x: User sees label and input for each filter from the list: Orientation, Price, Offensive, Isolated images only.
:x: User sees the default filter `Select...` applied in Offensive filter.
:x: User sees the filter `All` but it is the same as `Select...` in Price filter
:x: User sees the default filter `Select...` applied in Orientation filter.

**Comment by sidolov** [comment]
Fixed in scope of: https://github.com/magento/adobe-stock-integration/pull/112
