### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1182]
- add PHP 7.4 compatibility
- remove 7.1 and 7.2 compatibility
- keep 7.3 compatibility
- make code and tests comply with this change
- tests should be compatible with PHPUnit 9

**Comment by coderimus** [comment]
@lenaorobei nice feature request! With which `magento2` branch this can be tested?

**Comment by lenaorobei** [comment]
Internal team is working on it for `2.4-develop` branch.
