### ISSUE TITLE
No frontend validation on uploading not supported file formats 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1193]
## Issue 
On uploading unsupported file formats, Magento tries to upload the asset, but server side declines the file. Need to have storefront validation.

## Steps 

- Open Media Gallery and click Upload images button
- Select files that are not supported 
<img width="1360" alt="Screen Shot 2020-04-13 at 1 59 36 PM" src="https://user-images.githubusercontent.com/5603216/79151157-99a8e700-7d8f-11ea-9b87-76834818571f.png">

- Confirm selection and wait for Magento to return the backend validation:
<img width="1153" alt="Screen Shot 2020-04-07 at 11 16 59 AM" src="https://user-images.githubusercontent.com/5603216/78693860-72e73e00-78c1-11ea-82d8-53347b934fc6.png">

 ## ✅ Expected behavior 

- Consider option to disable not supported file formats from selection. 
- If user dragged the not supported files to upload, perform frontend validation
- If possible upload files with supported format and show success message  and block uploading not supported formats and  show error message with file types that are not supported. If above not possible , than block uploading all files and  show error message

## Design

![Image-uploaded-messages](https://user-images.githubusercontent.com/752610/79155983-a6c9d400-7d97-11ea-98b1-4fe9f6ae8227.png)

Basically, bulk the success messages into one message, but call out each failed file:

`Cannot upload “filename-of-the-image.mov”. This file format is not supported.`

**Comment by belbiy** [comment]
Here's the messages: 

![Image-uploaded-messages](https://user-images.githubusercontent.com/752610/79155983-a6c9d400-7d97-11ea-98b1-4fe9f6ae8227.png)

Basically, bulk the success messages into one message, but call out each failed file:

`Cannot upload “filename-of-the-image.mov”. This file format is not supported.`

**Comment by chalov-anton** [comment]
https://github.com/magento/adobe-stock-integration/issues/1123

**Comment by lenaorobei** [comment]
Closing ion favor of https://github.com/magento/adobe-stock-integration/issues/1123
