### ISSUE TITLE
Image Details Page for uploaded images has broken CSS 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1194]
Programmatically downloaded 
<img width="1918" alt="Screen Shot 2020-04-13 at 2 19 40 PM" src="https://user-images.githubusercontent.com/5603216/79152713-4be1ae00-7d92-11ea-9af2-3d5be4871016.png">
Manually uploaded 
<img width="1912" alt="Screen Shot 2020-04-13 at 2 18 29 PM" src="https://user-images.githubusercontent.com/5603216/79152722-500dcb80-7d92-11ea-9c32-8f894a3e013d.png">

**Comment by Nazar65** [comment]
fixed in https://github.com/magento/adobe-stock-integration/pull/1138

**Comment by chalov-anton** [comment]
https://github.com/magento/adobe-stock-integration/issues/1125
