### ISSUE TITLE
Cleanup stock metadata after image delete action

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#12]
### Description
- Introduce new plugin to cleanup stock metadata after image delete action in media gallery

### QA notes
- Save image to the media gallery via Adobe Stock Image
- Remove image from media gallery
- Image metadata should be removed

**Comment by igor-imaginemage** [comment]
Hi @sidolov, I created a PR for this task.

https://github.com/magento/adobe-stock-integration/pull/51
