### ISSUE TITLE
Image preview is broken (Licensing)

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1228]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. From Admin go to **Content** - **Media - Media Gallery** 
2. Click **Search Adobe Stock**, select an unlicensed image to open Preview
3. **Select the second image from More from this series** and click **Save Preview**
(the image appeared in Media Gallery and it is selected/highlighted)
4. Click on _three dots_ and select **License**. **Confirm** licensing
5. Click **Search Adobe Stock** and observe the image preview
![image_preview_2020-04-17](https://user-images.githubusercontent.com/45624059/79548788-a898dd80-809e-11ea-9eb5-e3aaea20d429.gif)

### Expected result (*)
![im_preview_1704_er](https://user-images.githubusercontent.com/45624059/79548279-e21d1900-809d-11ea-9169-b40a463e06d6.png)

### Actual result (*)
The image preview is broken
![im_preview_1704_ar](https://user-images.githubusercontent.com/45624059/79548170-ab470300-809d-11ea-8b0d-3a1850f204d7.png)

### Note 
There is another way to reproduce this issue. It will be reproducible after merging https://github.com/magento/adobe-stock-integration/pull/1249 I will also leave an identical comment for visibility  
If the secret key is not entered, and user tries to License ann image from Media Gallery
![preview_is broken_license](https://user-images.githubusercontent.com/45624059/79972838-3dd11300-849f-11ea-9896-3fbcdcaaa128.gif)

**Comment by gabrieldagama** [comment]
Hi @chalov-anton, I've tried to reproduce this issue locally but haven't been able to, not sure if I'm doing something wrong, my branches are up to date and magento is updated.

![test-issue-1228](https://user-images.githubusercontent.com/3008360/79632525-c5ddb280-8157-11ea-837f-846ebab4098e.gif)

**Comment by chalov-anton** [comment]
Hello @gabrieldagama 
We were able to reproduce this on two different environments.
The main step is the Step number 3. You need to switch to another image from _More from this series_ and Save it's preview. And after, license it from Media Gallery.

**Comment by chalov-anton** [comment]
There is another way to reproduce this issue. It will be reproducible after merging https://github.com/magento/adobe-stock-integration/pull/1249
If the secret key is not entered, and user tries to License ann image from Media Gallery
![preview_is broken_license](https://user-images.githubusercontent.com/45624059/79972838-3dd11300-849f-11ea-9896-3fbcdcaaa128.gif)
