### ISSUE TITLE
[Spike] Investigate meta data extracting

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1237]
As a Merchant I want Magento Media Storage to parse image meta data that is available in the file and expose it on image details page so that I can manage it and use for filtering images

**Additional context**
https://github.com/magento/adobe-stock-integration/issues/1183

# Open questions: 
- is there any required set of fields that exist in image meta data? Like title, description, keywords. Or any fields can be removed/added to the file according to standard?
- is there a way in a meta data file to define what fields can be edited by user in the application? e.g. Camera data, image format, creation and modification date can not be edited

**Comment by sivaschenko** [comment]
Neet to try `exif_read_data` on different image formats

**Comment by sivaschenko** [comment]
We can use the `APP13` IPTC data of the image for reading and saving metadata.

Reading the metadata:

    $iptcHeaders = [
        'title' => '2#005',
        'headline' => '2#105',
        'keywords' => '2#025'
    ];
    
    getimagesize('image.jpg', $info);
    $decodedMetadata = iptcparse($info['APP13']);
    $keywords = $decodedMetadata[$iptcHeaders['keywords']];
    $title = $decodedMetadata[$iptcHeaders['headline']];

Saving the metadata:

    $newTitle = 'New Title';
    $length = strlen($newTitle);
    $retval = chr(0x1C) . chr(2) . chr(substr($iptcHeaders['headline'], 2));
    if($length < 0x8000) {
        $retval .= chr($length >> 8) .  chr($length & 0xFF);
    } else {
        $retval .= chr(0x80) .
            chr(0x04) .
            chr(($length >> 24) & 0xFF) .
            chr(($length >> 16) & 0xFF) .
            chr(($length >> 8) & 0xFF) .
            chr($length & 0xFF);
    }
    $data = $retval . $newTitle;
    
    $content = iptcembed($data, $filename);
    
    $file = fopen($filename, "wb");
    fwrite($file, $content);
    fclose($file);

IPTC standard: https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata
