### ISSUE TITLE
'Test Connection' button is over-spanned

### ISSUE THREAD

**Issue by konarshankar07** [magento/adobe-stock-integration#124]
### Preconditions (*)

1.No preconditions

### Steps to reproduce (*)

1. Navigate to Stores > Settings > Configuration > Advanced > System > Adobe Stock Integration 
2. Find the Test Connection button and inspect it

### Expected result (*)

```
<button class="scalable" type="button" id="system_adobe_stock_integration_adobe_stock_test_connect_wizard">
            <span id="system_adobe_stock_integration_adobe_stock_test_connect_wizard_result">
                Test Connection            </span>
</button>
```

### Actual result (*)

```
<button class="scalable" type="button" id="system_adobe_stock_integration_adobe_stock_test_connect_wizard">
    <span>
        <span>
            <span id="system_adobe_stock_integration_adobe_stock_test_connect_wizard_result">
                Test Connection            </span>
        </span>
    </span>
</button>
```

**Comment by konarshankar07** [comment]
Thanks to @TomashKhamlai . He found this issue in [23346](https://github.com/magento/magento2/issues/23346) and we also have the same issue with our test button

**Comment by sidolov** [comment]
Hi @konarshankar07 , I'm closing this issue in favor of https://github.com/magento/magento2/issues/23346, I think we don't need duplicated issues in both projects. It will be fixed in Adobe Stock integration too after the PR https://github.com/magento/magento2/pull/23367 will be merged. Thank you!

**Comment by konarshankar07** [comment]
Hello @sidolov ,

It won't fix this issue in our extension. I found an issue in `ext\magento\stock-integration\AdobeStockAsset\view\adminhtml\templates\system\config\testconnection.phtml`. Please check and reopen this issue

**Comment by sidolov** [comment]
@konarshankar07 got it! Thank you for the clarification!
