### ISSUE TITLE
Image thumbnails are displayed after "media-gallery:sync"

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1243]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. **Upload an Image**
3. In terminal run ```php bin/magento media-gallery:sync```
4. Open **Content - Media Gallery** again

### Expected result (*)
No image thumbnails are displayed

### Actual result (*) 
Image thumbnails are displayed
![im_thumb1](https://user-images.githubusercontent.com/45624059/79855295-75728900-83d3-11ea-910b-8c9b09eb4ef9.png)

![im_thumb](https://user-images.githubusercontent.com/45624059/79855152-3d6b4600-83d3-11ea-80da-f223a784a3eb.gif)

**Comment by coderimus** [comment]
@Nazar65 this issue should be fixed with this PR https://github.com/magento/adobe-stock-integration/pull/1236
