### ISSUE TITLE
Deleting doesn't remove image from pub/media, thus it appears in Media Gallery after synchronizing

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1245]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Have an image uploaded to Media Gallery

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on _three dots_ and select **Delete**
3. Verify that the image disappears from Media Gallery 
4. In terminal run ```php bin/magento media-gallery:sync```
5. Open **Content - Media Gallery** again

### Expected result (*)
The image is deleted from ```pub/media``` and not displayed in Media Gallery after synchronizing 

### Actual result (*) 
The image is not deleted from ```pub/media```, thus it appears in Media Gallery after synchronizing

![im_delete_2020-04-21](https://user-images.githubusercontent.com/45624059/79856634-40673600-83d5-11ea-986a-c4e1089f579e.gif)

**Comment by coderimus** [comment]
@chalov-anton @sivaschenko 
What should happen with the content which uses this image? Should we remove it from it or what is the flow in that case?

**Comment by coderimus** [comment]
@chalov-anton @sivaschenko I got the point about the image delete action and content at the yesterday ASI meeting. Will proceed with this issue ASAP.
