### ISSUE TITLE
Image title is displayed in Media Gallery instead of image name 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1248]
I think it would be more convenient for the user to see image names in Media Gallery, that were set during Save Preview. And in the View Details page, the image title from Adobe Stock.
It is confusing not to be able to manage your own Media Gallery. To name images and easily find them. 

### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock** and open an Image Preview from the grid 
3. Click **Save Preview**
4. In the _Save Preview_ window, _File Name_ field, type a valid name you'd like to name the file, "_myfile_" for example. **Confirm**
5. Observe the image in Media Gallery grid 

### Expected result (*)
The image name displayed as specified in Save Preview. Image title from Adobe Stock is displayed in _Image Details_ page 

### Actual result (*)
Image title from Adobe Stock is displayed
![im_name_2020-04-21](https://user-images.githubusercontent.com/45624059/79864468-339d0f00-83e2-11ea-8c07-9aae1d2e4899.gif)

### Note
- NOT Enhanced Media Gallery displays image name which was set during saving preview

**Comment by sivaschenko** [comment]
Hi @tkacheva can you please let us know what do you think about this issue

**Comment by sivaschenko** [comment]
Not actual as the ability to edit image title will be added in the upcoming milestone
