### ISSUE TITLE
Used in section doesn't display more than 1 Product or Page

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1265]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. An image added to Media Gallery 

### Steps to reproduce (*)
Two different Products (or Pages) with **Content** containing one **same image** from Media Gallery
Open Media Gallery and verify Image Details

### Expected result (*)
The image is used in two products, so the _Used in_ section should display 2 Products. Please see the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/162f3177-f504-454f-82e2-f5a8f89f92e4/Image-Details) 

### Actual result (*)
Used in section displayed 1 Product. The same result with Pages
![used_in](https://user-images.githubusercontent.com/45624059/80113627-3ab35100-858b-11ea-823b-5e58869dfddf.png)

### Note
PR which adds the _Used In_ functionality https://github.com/magento/adobe-stock-integration/pull/1161

**Comment by Nazar65** [comment]
PR created at magento 2 repo https://github.com/magento/magento2/pull/27966

**Comment by Nazar65** [comment]
Closing this as pr was merged to 2.4 develop branch
