### ISSUE TITLE
"Used in" doesn't display any Categories 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1266]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. An image added to Media Gallery 

### Steps to reproduce (*)
Create a category in Catalog - Categories and add an image from Media Gallery to it's Content. 
Save category
Open Media Gallery and verify Image Details

### Expected result (*)
_Used In: 1 category_ should be displayed in. Please see the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/162f3177-f504-454f-82e2-f5a8f89f92e4/Image-Details) 

### Actual result (*)
Used in section does not display that the image is used in 1 Category
![used_in_cat](https://user-images.githubusercontent.com/45624059/80115349-50c21100-858d-11ea-8b28-44dc01f28a72.png)

### Note
PR which adds the _Used In_ functionality https://github.com/magento/adobe-stock-integration/pull/1161

**Comment by Nazar65** [comment]
PR created at magento 2 repo https://github.com/magento/magento2/pull/27966

**Comment by Nazar65** [comment]
Closing this as pr was merged to 2.4 develop branch
