### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'id' of null" error appears if add a Page content image and open Media Gallery again

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1272]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. An image added to Media Gallery

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, select **Insert Image...**
3. Select an image from Media Gallery and click **Add Selected**
4. Click **Insert Image** again

### Expected result (*)
No error in Browsers dev console 

### Actual result (*)
:x: _Uncaught TypeError: Cannot read property 'id' of null_ error in dev console
![uncought_id null_open meg gal again](https://user-images.githubusercontent.com/45624059/80195222-3129f780-8624-11ea-8b35-61fcd49a4ea7.png)
![delete_image confirmation_redirected](https://user-images.githubusercontent.com/45624059/80195458-86660900-8624-11ea-85a7-1c19b52ab625.gif)

**Comment by Nazar65** [comment]
PR created at magento 2 repo -> https://github.com/magento/magento2/pull/27934
