### ISSUE TITLE
Story 54: User inserts image rendition to the content

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1286]
# Story
As a Merchant I want to use image renditions programmatically generated from original hi res image  based on predefined configurable parameters *so that* content is optimized for desktop and mobile

## Business Value
Web optimized Images used in the content 

## Preconditions 
1.  Admin User is logged into Admin Panel
2. The old media gallery is off

## Acceptance Criteria
* User goes to Store>Configuration>Advanced >System and sees the image optimization is on
 * User sees images renditions default width to be set to 1000px
* User changes image rendition width OR height
* User defines image renditions settings globally
* User saves configuration and verifies that parameters provided are used when image is inserted into the content. For images that are used on the storefront, all the image rendition sizes are regenerated.
* User goes to the page with where insert image button is present
* User  selects an image from the Media Gallery 
* User confirms inserting the image 
* User saves the page and sees image renditions used  in the content instead of original hi res image 
* User sees image rendition link to be human readable
* Only relevant rendition is loaded on the storefront

**Comment by belbiy** [comment]
Please see proposed settings: 

![media-gallery-image-size-settings](https://user-images.githubusercontent.com/752610/93113726-2fb6a580-f67f-11ea-97cf-57d6a0025c6d.png)
