### ISSUE TITLE
Story 55: User sets the image rendition parameters for all breakpoints 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1287]
# Story
As a Developer/Technically powerful Marketer I want to set the image renditions parameters for resizing original hi res image to the version suitable for the web  *so that* Marketer can insert web optimized images into the content 

## Business Value
defines image renditions default behavior across websites 

## Preconditions 
1.  Admin User is logged into Admin Panel

## Acceptance Criteria
* User  goes to Store>Configuration>Advanced >System and opens web image renditions parameters 
* User defines image rendition width OR height 
* User chooses if rendition is inserted into the content instead of original image for all images or only stock images (resize images from the selected source - multiselect) 
* User defines image renditions settings globally 
* User saves configuration and verifies that parameters provided are used when image is inserted into the content

**Comment by lenaorobei** [comment]
Merged into https://github.com/magento/adobe-stock-integration/issues/1286
