### ISSUE TITLE
Story 56: User inserts image rendition to the content with TinyMCE WYSIWYG editor

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1289]
# Story
As a Merchant I want to use image renditions programmatically generated from original hi res image  based on predefined configurable parameters *so that* content is optimized for desktop and mobile

## Business Value
Web optimized Images used in the content 

## Preconditions 
1. [Web image parameters defined in site configuration ](https://github.com/magento/adobe-stock-integration/issues/1287)
2.  Admin User is logged into Admin Panel
3. Admin user is on the page with content controlled by TinyMCE WYSIWYG editor (E.g. product short description field)

## Acceptance Criteria
* User initiates inserting image and sees Media Gallery opened (no Insert/Edit image tinyMCE dialog)
* User  selects an image from the Media Gallery 
* User confirms inserting the image 
* User sees image rendition inserted into the content
* User selects image and clicks _Edit Image_ button, user sees Media Gallery opened (no Insert/Edit image tinyMCE dialog)
* User saves the page and sees image rendition generated based on site configuration loaded to the storefront instead of original hi res image

**Comment by lenaorobei** [comment]
Merged into https://github.com/magento/adobe-stock-integration/issues/1286
