### ISSUE TITLE
Investigate potential problem: Argument 2 passed to AdobeStock\Api\Client\AdobeStock::__construct() must be of the type string, null given, called in .../AdobeStockClient/Model/Client.php on line 175

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#129]
### Preconditions (*)

1. Something wrong with ASI API key.
2. Folders `var`, `generated` do not contain visible files. (Keep dotfiles if you are using Midnight Commander).
3. Magento was upgraded using `php bin/magento setup:upgrade`

### Steps to reproduce (*)

1. Cannot reproduce. Probably error is masked by #128 

### Expected result (*)

1. 

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by vpodorozh** [comment]
@TomashKhamlai - seems that you have issues with your DB.
Reason of the problem:
1. This is not an API Key param, this is a Product Name param `AdobeStockClient/Model/Client.php:174` - param 2
2. It can happen only in case when you have this config `adobe_stock/integration/product_name` set to `null` (via DB or `config.xml`)

So, clean up your DB - I do not see any other reasons for this. Check screenshots for the proves.
![Screen Shot 2019-06-25 at 21 25 44](https://user-images.githubusercontent.com/16047928/60123890-1df29500-9791-11e9-941d-b6d45ce11b98.png)
![Screen Shot 2019-06-25 at 21 30 25](https://user-images.githubusercontent.com/16047928/60123891-1df29500-9791-11e9-8925-23f467e28851.png)
