### ISSUE TITLE
Story 57: User filters images by the area they used in

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1291]
## Story
As a Merchant I want to filter images by the place they are used in *so that* I can find images that are included into particular piece of content 

## Business Value
Ability to find images used in the magento storefront 

## Preconditions 
* Admin User is logged into Admin Panel
* Images are used on the blocks, dynamic blocks, pages, category description and product information 
* Admin User views images in Media Gallery 

## Acceptance Criteria
* User filters images by the area where the images are used in
** pages
** categories
** blocks 
** dynamic blocks
*** product information 
* User can filter images across all entities of selected type (E.g. all pages, all blocks, all categories etc) or narrow down search to selected entities (e.g. products A, B and Z)
* User can search by status of the entity where assets are used in (e.g. assets used in disabled pages) :
*** any
*** enabled
*** disabled
* User can filter assets by the storeviews where they are used in 
* User can filter assets by the customer segment they are shown as part of the targeted content 
* User can choose multiple areas of image usages (e.g. product content and cms pages) 
* User applies selected filters and sees images to be updated and only  images that match the filter displayed

**Comment by sivaschenko** [comment]
Tasks:
 - HLD
 - Implement GetAssetListInterface to MediaGallery module in Magento 2 repo + Integration test
 - GetAssetListInterface functionality should be extended from AdobeStockAsset module to add the ability to process adobe stock asset attributes in the search criteria (adding select modifier to the pool used in GetAssetListInterface) + Integration tests
 - GetAssetListInterface functionality should be extended from MediaContentCms module to add the ability to process media-content relations in the search criteria (adding select modifier to the pool used in GetAssetListInterface) + Integration tests
 - GetAssetListInterface functionality should be extended from MediaContentCatalog module to add the ability to process media-content relations in the search criteria (adding select modifier to the pool used in GetAssetListInterface) + Integration tests
 - use GetAssetListInterface for the DataProvider of media gallery grids + Integration tests
 - Add the content-media relations (only for entity types) multiselect filter to the frontend + MFTF test
 - Extend multiselect filter on the frontend to handle more detailed attributes of related content entities + MFTF test
 - Add autosuggestion of content entities + MFTF test
