### ISSUE TITLE
Story 58: User sees entities where asset is used in

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1292]
## Story
As a Merchant I want to list of entities  where the selected asset is used in *so that* can manage this association from asset side and clean up assets that are no longer used
## Business Value
overview of where asset is used in Magento storefront 

## Preconditions
1.  Admin User is logged into Admin Panel
2. Admin user is on Content>Media Gallery 
3. Admin user views asset details 

## Acceptance Criteria
* User sees list of entities this asset is associated with:

   - Pages (title, url-key, status, store view)
   - Blocks (title, id, status, storeview)
   - Dynamic Blocks (name, status, storeview)
   - Category (name, status, store view, area (category image, category description  )
   - Product (name, status, store view, area (attribute name, product gallery)
   - Newsletter template (name)
- User can open each entity the asset is associated with in a separate tab to manage association

**Comment by sivaschenko** [comment]
2 tasks:
1. Return detailed information from backend (image details request) + Integration test (still displaying just number of entities)
2. Display detailed information on frontend + MFTF test
