### ISSUE TITLE
`Search by keyword` filter dismiss other filters

### ISSUE THREAD

**Issue by engcom-Charlie** [magento/adobe-stock-integration#1301]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Upload image with name `a4`
2. Search this image by search input
![image](https://user-images.githubusercontent.com/51680850/80586305-6f0c8e80-8a1d-11ea-8cbc-1e0046589ca4.png)
3. Apply filter `Source` - `Adobe Stock`
![image](https://user-images.githubusercontent.com/51680850/80587361-176f2280-8a1f-11ea-9c69-ea548477cb06.png)

### Expected result (*)

Image can't be found because it was uploaded

### Actual result (*)

Image is found

**Comment by chalov-anton** [comment]
Also a problem if a _Directory_ filter is applied together with _Source_ , for example, _Adobe Stock_
In this case, the _Source_ filter is ignored and all the images in Directory are displayed
