### ISSUE TITLE
Story 59: User sees warning when deleting image if it's used on storefront 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1310]
## Story
As a Merchant I want to see a warning that image I delete is used on storefront  *so that* I don't accidentally corrupt storefront content 

## Business Value
no broken content due to accidentally removed asset 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User views images in Media Gallery 

## Acceptance Criteria
* User selects image and start deleting it. 
* USer sees a warning message, if image is used somewhere on storefront. Warning message communicates how many times the asset is used in catalog, content and marketing areas. User has option to view and manage the asset usage before deleting it. I
* User confirms deleting the asset, asset and all its renditions removed from media storage and DB records 

![image](https://user-images.githubusercontent.com/2028541/82818870-4b5f2b80-9e97-11ea-9d1a-8531e33b8faf.png)

**Comment by sivaschenko** [comment]
Single task: check if image is used on attempt to delete an image and show the usage in the warning
- New request to the server before deletion confirmation
- Controller and model
- Support multiple image deletion
