### ISSUE TITLE
Redirect URL pattern, used by Adobe Stock Integration, is removed from https://console.adobe.io/ 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1314]
After the https://console.adobe.io/ update, there is no option to specify the Redirect URL pattern

![creative_sdk](https://user-images.githubusercontent.com/45624059/80980078-dfa61780-8e30-11ea-9054-772ea587426c.png)

According to Adobe Stock Integration documentation, the pattern is needed for user Sign In
https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide
![70395270-f9177480-19f4-11ea-8d0a-1a8268fdf706](https://user-images.githubusercontent.com/45624059/80980733-a9b56300-8e31-11ea-899a-2915323a4bd8.png)

User is not able without Redirect pattern use: SignIn, License functionality with secret key functionality 
bin/magento config:set admin/security/use_form_key 1

**Comment by sivaschenko** [comment]
Redirect URI in console.adobe.io is now a field for Redirect URI Pattern, please use `https://<hostname>/<backend_frontname>/adobe_ims/oauth/callback/.*` value for that field.

Working on documentation update.

cc @chalov-anton @Nazar65 @coderimus

**Comment by sivaschenko** [comment]
Configuration instructions were moved to a new page in project wiki: https://github.com/magento/adobe-stock-integration/wiki/Get-API-keys

**Comment by sivaschenko** [comment]
Pull request to merchdocs: https://github.com/magento/merchdocs/pull/490

**Comment by coderimus** [comment]
@sivaschenko thank you for the update! I checked the pattern and it works. I also checked mentioned PR to the merchdoc but as I can see it can be assigned and reviewed only by the members of merchdocs :) In any case, it is correct - check 👍

**Comment by sivaschenko** [comment]
Integration used for test builds updated accordingly

**Comment by sivaschenko** [comment]
@coderimus thank you!
