### ISSUE TITLE
Fix failed tests

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1320]
Following PRs are constantly failing for all release lines:
- AdminAdobeStockImagePreviewKeywordsSearchTest
- AdminAdobeStockImagePreviewKeywordsTest
- AdminAdobeStockLocalizationTest

**Comment by Nazar65** [comment]
There was a problem on Adobe Stock site, keywords for all images disappeared, now all ok.

**Comment by sivaschenko** [comment]
Recent build example: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/adobe-stock-integration/pull/1319/4168b34d915bbb577c1ec4f6669449fa/Functional/allure-report-ce/index.html#
