### ISSUE TITLE
[MFTF] - Cover Uploading images into Media Gallery 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1325]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
Admin user is logged in to admin panel
User navigate to Content - Media - Media Gallery
Media Gallery is opened
Click Create Folder button
Enter folder name in "local"
Click Confirm button
Folder is created in "Storage Root" folder tree
Select the created folder
User clicks Upload Image button
"Open Files" window appears
User selects an unsupported file format, text file for example
User click Open
Assert that the "Cannot upload 'filename'.  This file format is not supported" error message appears
Assert that the error message disappears in several seconds 
User clicks Upload Image button
"Open Files" window appears 
User select an image with size more than 2 MB
User click Open
Assert that the "Cannot upload 'filename'. file exceeds maximum file size limit" message appears
User clicks Upload Image button
"Open Files" window appears
User selects a supported file type image that are less than 2MB each
User click Open
Assert that success message appears "Successfully uploaded an image"
Assert that the image appeared in media gallery
User clicks Upload Image button
"Open Files" window appears
Form the "Open Files" window select at once: unsupported file format, unsupported file size, multiple supported images
User clicks Open button
Assert that the following messages are displayed: 
- "Cannot upload 'filename'. File exceeds maximum file size limit" 
- "Cannot upload 'filename'. This file format is not supported" 
- Success message with image number counter "Successfully uploaded 'number_of_images' images"
Assert that all the messages disappear within several seconds 
Asserts that the successfully uploaded images exist in Media Gallery

### Note (*)
Test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/4659063

**Comment by sivaschenko** [comment]
The base case of image uploading and attributes verification is covered in https://github.com/magento/adobe-stock-integration/pull/1329
