### ISSUE TITLE
Media gallery synchronization should consider file modification time

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1339]
Task to address the issue: https://github.com/magento/adobe-stock-integration/issues/1336

### Preconditions (*)
Install Magento 2.4.x with Adobe Stock Integration 2.0.0-develop

### Steps to reproduce (*)
1. Run `bin/magento media-gallery:sync`

### Expected result (*)
Media gallery synchronization should be performed only for files that were modified since the last synchronization execution

**Comment by coderimus** [comment]
Ah, such a subtle, challenging issue! Love it.
