### ISSUE TITLE
"The image cannot be located" message appears if try to Save Preview in a sub-folder with the same name as the main folder.[NOT Enhanced Media Gallery] 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1361]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Go to _Stores - Configuration - Advanced -System - Enhanced Media Gallery_ and select **Enabled - No**
![enabled_no](https://user-images.githubusercontent.com/45624059/82206114-51da2a00-9910-11ea-8bc0-53055f9fb82e.png)

### Steps to reproduce (*)
1. Go to _Content - Pages_ click **Add New Page**
2. Expand _Content_ click **Show / Hide Editor** - **Insert Image...**
3. Create a folder name _"1"_, for example, and a subfolder with the same name in it
![1_subfolder](https://user-images.githubusercontent.com/45624059/82206586-2ad02800-9911-11ea-9937-da31e253e125.png)
4. Select the subfolder _"1"_ and click **Search Adobe Stock**
5. Open any image Preview, click **Save Preview** - **Confirm**

### Expected result (*)
Subfolder  _"1/1"_ is opened. No message appears

### Actual result (*)
The main folder _"1"_ is opened. A message appears_"The image cannot be located"_. After closing the error message, a Gray overlay appears all over the page

**Comment by chalov-anton** [comment]
Severity: S2 added because of the Gray overlay

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed
