### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'complete' of undefined" appears in dev console if save Previewed image as a new View and open this View on another page

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1387]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock**
3. Go to the first page from the grid, and select any image to open its Preview
4. Click on **Default View** (bookmarks view)
5. Click **Save View As...**, 
6. Click **Save all Changes** :arrow_right: 
7. Switch to the _Default View_
8. Go to the second page in Adobe Stock grid
9. Switch to the previously created _New View_

### Expected result (*)
No error message in dev console

### Actual result (*)
:x: _Uncaught TypeError: Cannot read property 'complete' of undefined_ appears in dev console 
![uncought_complete_view_2520](https://user-images.githubusercontent.com/45624059/82804815-a25f0380-9e8b-11ea-9a7b-8df1fd40813a.png)

**Comment by mmezhensky** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Also related to this issue, when you follow the steps described on the issue, the image that gets displayed on the image preview section is incorrect, currently, it is displaying the image from the previous page, instead of the image from the saved bookmark.
