### ISSUE TITLE
Add related content information to the delete asset warning

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1390]
### Story

https://github.com/magento/adobe-stock-integration/issues/1310

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Enable Enhanced Media Gallery

### Steps to reproduce
1. Open Media Gallery
2. Upload an image
3. Insert the image to Page/Block/Product/Category wysiwyg field
4. Delete the uploaded image
 - Selecting the image and clicking Delete button
 - Opening view details and clicking Delete button
 - Opening context menu for the image (click on 3 dots) and selecting Delete option

### Expected result
The warning message appears with the information that the image is used in the content

![image](https://user-images.githubusercontent.com/2028541/82818870-4b5f2b80-9e97-11ea-9d1a-8531e33b8faf.png)

**Comment by ProkopovVitaliy** [comment]
@magento I am working on this
