### ISSUE TITLE
SaveAssetsKeywordsInterface to delete obsolete keywords

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1391]
### Story

https://github.com/magento/adobe-stock-integration/issues/724

### Description

This change should be done in magento2 repo

The functionality of `\Magento\MediaGallery\Model\ResourceModel\Keyword\SaveAssetsKeywords::execute` should be update to delete the links to the keywords that are not provided in the argument

### Testing
`\Magento\MediaGallery\Model\ResourceModel\AssetKeywordsTest` integration test should be adjusted to cover this case

**Comment by ProkopovVitaliy** [comment]
@magento I am working on this

**Comment by lenaorobei** [comment]
Hi @ProkopovVitaliy. Do you have any progress with this task? If you need an assistance please let us know.
