### ISSUE TITLE
Implement content type search filter

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#14]
### Description
- Implement content type search filter UI element
- Implement content type filter for the API endpoint on the backend

### Documentation
Story: [User filters images by type](https://github.com/magento/adobe-stock-integration/issues/32)
App Design Document: [Adobe Stock Image Search Design](https://github.com/magento/adobe-stock-integration/wiki/Adobe-Stock-Image-Search-Design)

### QA notes
- User has the ability to filter results by the content type attribute

**Comment by konarshankar07** [comment]
@sidolov 

I'm not sure with how you are trying to implement this cause the search by content_type is have only one option  "content_type": "image/jpeg" and for photos, we need to use "filters_content_type_photos" which is boolean and for illustration, we need to use "filters_content_type_illustration" which is also boolean. Let me know if I'm implementing wrong
Thanks

**Comment by sivaschenko** [comment]
Hi @konarshankar07 we are working on identifying the best approach to work with such kind of filters.

Currently, there are two approaches under review:
1. Add an ability to specify a class responsible for applying filter
2. Include the filter logic handling as part of the Client

We'll let you know once we'll come to a final decision. Also, feel free to share your ideas on how it's better to handle this

**Comment by sidolov** [comment]
@konarshankar07 we already finished API refactoring and you are able to implement described filter.
