### ISSUE TITLE
Broken profile image leads to a 403 error in dev-console 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1404]
### Description (*)
Sometimes you may see a :x: _GET https://a5.behance.net/.../img/profile/no-image-276.png **403**_ error in dev console when opening Media Gallery 
This happens because of a broken image in Adobe Stock profile information

### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery** 
(the error message already appears )
![get_devconsole](https://user-images.githubusercontent.com/45624059/83554535-a20eda00-a515-11ea-8d88-1071ce4b070d.png)

2. Click **Search Adobe Stock**
3. Sign In your account  
 

### Expected result (*)
Profile image is correctly displayed

### Actual result (*)
![broken_image](https://user-images.githubusercontent.com/45624059/83554520-9a4f3580-a515-11ea-9aa1-5b0e0dcdc08a.png)

The link in the error message leads to
![403_forbidden](https://user-images.githubusercontent.com/45624059/83554588-b652d700-a515-11ea-8a71-938fa9d662eb.png)

**Comment by Nazar65** [comment]
Looks like this issue was on adobe side, as url with image retrieved from adobe side after each login action, and placed to the database. so it might be issue with not actual link to the image. For now it works as exepcted

**Comment by chalov-anton** [comment]
Also reproducible on our test cloud instance. So this is not an installation problem.

**Comment by sivaschenko** [comment]
@chalov-anton can this issue be reproduced on different adobe stock account?

**Comment by chalov-anton** [comment]
This is the full link to the image
https://a5.behance.net/27000444e0c8b62c56deff3fc491e1a92d07f0cb/img/profile/no-image-276.png
