### ISSUE TITLE
If the Root is not empty, the image state is not updated when the containing folder has been deleted.

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1410]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery** 
2. Do not select any folder from the folder tree  
3. Save an image Preview or Upload an image
4. Create a new folder named _1_ for example
5. Select the previously created folder and Sava Preview in it or Upload an image
6. Select the Previously created folder and **Delete** it

### Expected result (*)
Root directory is opened and the images from folder _1_ are not displayed

### Actual result (*)
Root directory is opened and the images from folder _1_ are displayed. Viewing image details will lead too _"Could not retrieve image details."_ message
![delete folder](https://user-images.githubusercontent.com/45624059/83763063-f84c5c00-a680-11ea-8bd4-e7cca901ec05.gif)

### Note
 Might be related to https://github.com/magento/adobe-stock-integration/issues/825

**Comment by gabrieldagama** [comment]
@magento run all tests
