### ISSUE TITLE
The "Used in- Product" doesn't consider images added from Custom Product Attribute 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1420]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Create a custom **Product Attribute**, type _Text Editor_
2. Create a new Product and add the previously created attribute 
3. From the added Attribute, insert an image from the Media Gallery and Save the Product
4. Go to Standalone Media Gallery and view the Image Details of the previously used image
 
### Expected result (*)
The image Used in Product should be displayed

### Actual result (*)
The _Used in_ section doesn't display that the image is used in Product

**Comment by sivaschenko** [comment]
The decision was made to require adding any custom attributes that require synchronization to the configuration of the synchronizer. I.e. DI configuration of `Magento\MediaContentSynchronizationCatalog\Model\Synchronizer\Category` for category custom attributes
