### ISSUE TITLE
Small image is stretched all over the image thumbnail

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1422]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery** 
2. Upload a small image to the Media Gallery
3. Observe the image thumbnail 

### Expected result (*)
The image is not stretched and displayed as it is

### Actual result (*)
The image is stretched all over the thumbnail which leads to a low-quality being displayed
![small_im_quality](https://user-images.githubusercontent.com/45624059/84139062-e63f3480-aa57-11ea-93c0-a7cef0c97f40.png)

**Comment by Nazar65** [comment]
PR created at M2 repo https://github.com/magento/magento2/pull/29149

**Comment by Nazar65** [comment]
closing via https://github.com/magento/magento2/pull/29149/
