### ISSUE TITLE
Remove the "Get User Profile" ACL

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1432]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Description
Remove the _Get User Profile_ ACL
![get_us_prof](https://user-images.githubusercontent.com/45624059/84277551-5aeb9f00-ab3c-11ea-89a3-04b2619f27f6.png)

User can Log In but the Sign In will remain Sign In
![get_us_prof_sign_in](https://user-images.githubusercontent.com/45624059/84278288-380dba80-ab3d-11ea-9b53-83b0dae10495.png)

User can License images and Save Preview, and not be aware, if the image is already Licensed or how many credits remained

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by konarshankar07** [comment]
Hello @chalov-anton ....
For this issue, I guess that you want to remove the `Get User Profile` ACL and use the `Login` ACL for viewing the `how many credits remained`. Correct me if I'm wrong 
Thanks

**Comment by chalov-anton** [comment]
Hello @konarshankar07 
Let's just remove the _Get user Profile_, because there is not much sense in having it. And leave the _Login_ as it works now
Thanks

**Comment by konarshankar07** [comment]
Thanks @chalov-anton for the update but which ACL we need to use for the `Magento\AdobeIms\Controller\Adminhtml\User\Profile::ADMIN_RESOURCE`?

**Comment by chalov-anton** [comment]
@konarshankar07 
Yes, let's use the Login ACL for viewing how many credits remained
