### ISSUE TITLE
Create an endpoint for saving asset attributes

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1440]
**Story** https://github.com/magento/adobe-stock-integration/issues/724: User edits image meta data in Media Gallery

#### Implementation details

 - The `Magento\MediaGalleryUi\Controller\Adminhtml\Image\SaveDetails` post controller should be added
 - The controller should save asset title, keywords and description provided in the request using the `\Magento\MediaGalleryApi\Api\SaveAssetsInterface`
 - `\Magento\MediaGalleryApi\Api\GetAssetsByIdsInterface` can be used to retrieve the asset that should be updated

### AC
- Endpoint for updating asset title and keywords is created
- Implementation is covered by integration tests

**Comment by joweecaquicla** [comment]
@magento I am working on this

**Comment by joweecaquicla** [comment]
@magento add to contributors team

**Comment by joweecaquicla** [comment]
@magento I am working on this
