### ISSUE TITLE
Add metadata to synchronization process

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1442]
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Implementation details
TBD

Depends on https://github.com/magento/adobe-stock-integration/issues/1447

### AC
- Image metadata is added to synchronization
- Implementation is covered by integration tests

**Comment by sivaschenko** [comment]
Closed in favour to https://github.com/magento/adobe-stock-integration/issues/1497
