### ISSUE TITLE
Save metadata to file on editing

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1444]
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Implementation details
Depends on
https://github.com/magento/adobe-stock-integration/issues/1448

### AC
- Metadata is saved when file is edited
- Implementation is covered with integration tests

**Comment by yolouiese** [comment]
@magento I am working on this
