### ISSUE TITLE
Create MediaGalleryMetadata and MediaGalleryMetadataApi modules

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1445]
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Implementation details
Basic module skeleton should be created with minimal required files.
See: https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

### AC
- Modules are created

**Comment by konarshankar07** [comment]
@magento I'm working on this
