### ISSUE TITLE
[MFTF] Backport the assertion correction to 1.0-develop

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1446]
The fix https://github.com/magento/adobe-stock-integration/commit/13fe5a121942ba57c84e923619f4342adbaccfef for the app/code/Magento/AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml test assetion should be backported to 1.0-develop to prevent the test from potential random failures

**Comment by lenaorobei** [comment]
Needs to be back-ported https://github.com/magento/adobe-stock-integration/commit/13fe5a121942ba57c84e923619f4342adbaccfef

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by konarshankar07** [comment]
Hello @sivaschenko ....
The changes are already backported in `2.0-develop` branch. Please check
https://github.com/magento/adobe-stock-integration/blob/d2ff62651c739b3b2b001dc3a9c7166da0229abe/AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml#L34
Thanks

**Comment by lenaorobei** [comment]
Hi @konarshankar07. This fix should be back-ported to `1.0-develop` branch.
