### ISSUE TITLE
The Vertical images in "More from this series..." are not centered

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1458]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Open preview of an image which has both _Horizontal_ and _Vertical_ imaged in **More from this...** tab 
(for example, search for the image _345873592_)
3. Observe the four images in **More from this series**

### Expected Result (*)
The Vertical image is centered

### Actual Result (*)
The Vertical image is shifted to the left side
![more from_vertical images_centered](https://user-images.githubusercontent.com/45624059/84505072-c6ad4380-acc5-11ea-972a-6b72f50d5ea4.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
