### ISSUE TITLE
Introduce Used In filter

### ISSUE THREAD

**Issue by gabrieldagama** [magento/adobe-stock-integration#1462]
Story #1291 

Add `Used In` filter to the media gallery to allow the user to filter by the area where the images are used in:
- Pages
- Categories
- Blocks
- Products

The filter input type should be the same as the print screen below and allow the user to select multiple options.

<img width="407" alt="Screenshot 2020-06-16 at 13 56 06" src="https://user-images.githubusercontent.com/3008360/84777255-40e90b00-afd9-11ea-865a-d72f08b2e3a7.png">

**Technical details**
https://github.com/magento/adobe-stock-integration/wiki/MediaGalleryUi-DataProvider

**Comment by ghost** [comment]
@magento I am working on this
