### ISSUE TITLE
Introduce Enabled filter

### ISSUE THREAD

**Issue by gabrieldagama** [magento/adobe-stock-integration#1464]
Story #1291 

Add a filter to allow the user to search by the status of the entity where assets are used in, for example, user filters by enabled, the filter should search across all entities (products, blocks, pages, and categories) and return assets that are used in entities that are enabled.

The frontend input should be the same used across other grids:

<img width="418" alt="Screenshot 2020-06-22 at 14 39 31" src="https://user-images.githubusercontent.com/3008360/85294598-bf8cef00-b496-11ea-8ce6-6a97a811478e.png">

**Technical details**
https://github.com/magento/adobe-stock-integration/wiki/MediaGalleryUi-DataProvider

**Comment by ghost** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Requires additional technical design on extension points for other entities.
