### ISSUE TITLE
Introduce Used In Categories filter

### ISSUE THREAD

**Issue by gabrieldagama** [magento/adobe-stock-integration#1466]
Story #1291 

Add a filter to allow users to filter assets that are used in specific categories. The input will display categories that exist on the platform and have a field for search by category name, the user must be able to select/filter multiple categories at the same time. The input should be similar to the one used on product edit form to select categories.

<img width="869" alt="Screenshot 2020-06-17 at 10 17 47" src="https://user-images.githubusercontent.com/3008360/84880370-549d7b80-b084-11ea-908a-ca5007fa4aca.png">

**Technical details**
https://github.com/magento/adobe-stock-integration/wiki/MediaGalleryUi-DataProvider

**Comment by ghost** [comment]
@magento I am working on this
