### ISSUE TITLE
Save image content hash to the media asset when saving image from the Adobe Stock

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1494]
Story: https://github.com/magento/adobe-stock-integration/issues/1484

### Preconditions (*)
1. Install Magento 2.4-develop with ASI 2.0-develop
2. Enable and Configure Adobe Stock Integration in the Stores -> Configuration -> System -> Adobe Stock Integration

### Steps to reproduce (*)
1. Login to Admin panel
2. Open the media gallery. I.e. from the Catalog -> Category -> Content fieldset -> Select image from gallery
3. Click "Search Adobe Stock" button
4. Click on any image to open the image preview panel
5. Click "Save Preview" button
6. Confirm the image name in the popup

### Expected result (*)
The images information should be saved to the `media_gallery_asset` table. The `hash` filed should be populated with the `sha1` hash of the image content

### Additional info

The same use case should work for Licensing or Saving Licensed image

**Comment by joweecaquicla** [comment]
@magento I am working on this
