### ISSUE TITLE
Add hash to asset on uploading the image to magento

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1496]
Story: https://github.com/magento/adobe-stock-integration/issues/1484

### Preconditions (*)
1. Install Magento 2.4-develop with ASI 2.0-develop
2. Enable Enhanced Media Gallery

### Steps to reproduce (*)
1. Login to Admin panel
2. Open the media gallery. I.e. from the Catalog -> Category -> Content fieldset -> Select image from gallery
3. Click "Upload image" button and upload an image

### Expected result (*)
The images information should be saved to the `media_gallery_asset` table. The `hash` filed should be populated with the `sha1` hash of the image content

### Testing

Should be checked for the next scenarios:
 - Uploading the image to the enhanced media gallery
 - Uploading the image to the old media gallery
 - Uploading the image to the category
 - Uploading the image to the Page builder
 - Runing `bin/magento media-gallery:sync` for images added manually to pub/media directory

### Technical Details

The changes should be applied to `\Magento\MediaGallerySynchronization\Model\CreateAssetFromFile::execute` method

**Comment by joweecaquicla** [comment]
@magento I am working on this
