### ISSUE TITLE
Display image description in the View Details slide panel

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1499]
Story https://github.com/magento/adobe-stock-integration/issues/724

### Preconditions (*)
1. Install magneto 2.4-develop with Adobe Stock Integration 2.0-develop
2. Enable Enhanced Media Gallery
3. Have an image uploaded to the media gallery
4. Have a description field filled in the `media_gallery_asset` table

### Steps to reproduce (*)
1. Login to admin panel
2. Open the media gallery (Content -> Media Gallery)
3. Select "View details" from the context menu for the image (opened clicking on three dots)

### Expected result (*)
The description should be visible in the image details panel

![image](https://user-images.githubusercontent.com/2028541/85023051-1c716800-b16c-11ea-9194-362a7c69376b.png)

### AC
- section is displayed
- covered with MFTF tests

**Comment by ghost** [comment]
@magento I am working on this
