### ISSUE TITLE
Add links to grids to the image details panel

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1503]
Story https://github.com/magento/adobe-stock-integration/issues/1292

**Preconditions:**
1. Magento and Adobe Stock Integrations are installed
2. Enhanced Media Gallery is enabled
3. An image is uploaded to the media gallery and added to the contents of Product, Category, Page and Block

**Steps:**
1. Open the Media Gallery
2. View details of the image

**Expected Result:**
Each item of the Used In the section of image details is a link.
Clicking the link opens the appropriate grid in a new tab with the Asset filter set to the viewed asset

![image](https://user-images.githubusercontent.com/2028541/87469396-21162880-c613-11ea-8ab7-87eb6096e242.png)

**Technical Details:**
See https://github.com/magento/magento2/pull/28932 introducing the component enabling to set filter using an URL parameter

See: https://github.com/magento/magento2/pull/28932

**Comment by konarshankar07** [comment]
@magento I'm working on this
