### ISSUE TITLE
Add keywords field to the edit image description slide panel

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1515]
Story: https://github.com/magento/adobe-stock-integration/issues/724

### Preconditions (*)
1. Install Magento 2.4-develop with Adobe Stock 2.0-develop
2. Enable Enhanced Media Gallery in the configuration
3. Have an image uploaded to the media gallery

### Steps to reproduce (*)
1. Login to admin panel
2. Open media gallery (I.e. Content -> Media Gallery menu)
3. Open context menu for the image by clicking on three dots next to the image in the grid
4. Select "Edit" option to open the Edit image details slide panel

### Expected result (*)
A popup appears with a warning message showing the content usage information for the selected assets

### Expected result (*)
Keywords filed is present in the slide panel

![image](https://user-images.githubusercontent.com/2028541/82818781-279be580-9e97-11ea-80fb-d978638f6841.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
