### ISSUE TITLE
Wrong folder is selected if create a sub-folder with a name that already exist in folder tree

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1522]
### Preconditions (*)
1.  Magento 2.4.0-beta1. ASI 2.0.0-beta1
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**, 
2. Create a main folder named **_b_** for example
3. Create another main folder named **_c_** for example
4. Select the folder **_c_** by clicking on it
5. Create a subfolder named **_b_** in it **_(c/b)_**

### Expected Result (*)
After the folder is created, the subfolder **c/b** is selected
![Selection_331](https://user-images.githubusercontent.com/45624059/85529973-3d2b3900-b616-11ea-9c7a-3cf5990ab78c.png)

### Actual Result (*)
![Selection_332](https://user-images.githubusercontent.com/45624059/85530094-56cc8080-b616-11ea-875e-4c82646e6dc5.png)

![Peek 2020-06-24 11-47](https://user-images.githubusercontent.com/45624059/85528738-f852d280-b614-11ea-8065-76b7bd9325b2.gif)

### Note 
**Not reproducible** on ASI 2.0-develop. Seems to be fixed in this PR https://github.com/magento/adobe-stock-integration/pull/1434

**Comment by yolouiese** [comment]
@magento I am working on this

**Comment by yolouiese** [comment]
This issue seems to be fixed and can no longer be replicated. I have checked on my end and confirmed that this is working as expected.

**Comment by chalov-anton** [comment]
@yolouiese I have rechecked this issue on the latest codebase and can Confirm that the issue is not reproducible anymore. I'm closing it.

Thank you
