### ISSUE TITLE
Switching between Views does not change the selected folder. [Media Gallery]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1523]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery is enabled

### Steps to reproduce (*)
1. Go **Content - Pages** click **Add New Page**
2. Expand **Content** click **Show / Hide Editor**, **Insert Image...**
3. Create a main folder named _folder_ for example and select it
![main folder](https://user-images.githubusercontent.com/45624059/85553234-6f479580-b62c-11ea-8745-f0d4b673ea25.png)
4. Click on **Default View** dropdown 
5. Click **Save View As...**, and click **Save all changes** ( ➡️  )
_now you have a New View with the selected folder_
6. Close the Media Gallery and go to **Catalog - Categories**
7. Expand **Content** and click **Select from Gallery**
_folder is selected_
8. Try to switch between **New View** and **Default View**
9. Observe the _Active filters: Directory_

### Expected Result (*)
Catalog/category folder is selected, and the Default view is selected

### Actual Result (*)
The _Active filters: Directory_ is changed but the selected folder remains the same 
![Peek 2020-06-24 15-29](https://user-images.githubusercontent.com/45624059/85556568-a23f5880-b62f-11ea-9a27-97bdc75da185.gif)

**Comment by sivaschenko** [comment]
Fixed in 2.4-develop, the fix is going to be delivered to 2.4.1-develop in https://github.com/magento-commerce/magento2ce/pull/6105
