### ISSUE TITLE
In some cases, the Media Gallery is not loaded from Page Builder

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1540]
### Preconditions (*)
1. Installed Magento EE with Page Builder with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery is enabled
4. Add Secret Key to URLs is set to Yes
![add_sec_key](https://user-images.githubusercontent.com/45624059/85836529-60cdbb00-b79f-11ea-8aff-285c4de4b7f4.png)

### Description
In some cases, the Media Gallery is not opened from Page Builder. Further investigation discovered that the issue is in _Invalid Secret Key_
![invalid secret key](https://user-images.githubusercontent.com/45624059/85836678-a7bbb080-b79f-11ea-906c-204cf26d58db.png)
Refreshing the web page doesn't solve the issue

### Workaround
- After cleaning Magento cache, the Media Gallery can be opened properly
- If the _Add Secret Key to URLs_ is Disabled, the issue will not occur

### Steps to reproduce (*)
1. Go **Catalog - Categories**
2. Expand **Content** and click **Edit with Page Builder**
3. Expand **Media**. Drag and drop **Image** on the **Row** area
4. Click **Select from Gallery**

### Expected Result (*)
Media Gallery is loaded
![med_gal_opened](https://user-images.githubusercontent.com/45624059/85837071-3af4e600-b7a0-11ea-9939-3782acad976f.png)

### Actual Result (*)
The Media Gallery is not loaded
![med_gal_not_opened_](https://user-images.githubusercontent.com/45624059/85837001-231d6200-b7a0-11ea-81b1-522a83ebd741.png)

![Peek 2020-06-26 11-02](https://user-images.githubusercontent.com/45624059/85837096-46e0a800-b7a0-11ea-9c1b-ee82089a111a.gif)

**Comment by sivaschenko** [comment]
@chalov-anton can you please check this issue with old media gallery and transfer the issue to page builder repo if it's not related to enhanced media gallery only

**Comment by chalov-anton** [comment]
@sivaschenko The issue is reproducible with "old" Media Gallery.
Can you please transfer this issue to the Page Builder repository? 

Thank you

**Comment by chalov-anton** [comment]
Transferred this issue to Page Builder repository https://github.com/magento/magento2-page-builder/issues/591

**Comment by Eddcapone** [comment]
Is there any news about this issue? I experience this in Magento 2.4.2 EE

**UPDATE**: **Deleting the cookies** did resolved the issue. I think it might have something to do with the cookie domain. I once changed it and then changed it to NULL again.
However, this was not helping a colleague of mine, we solved it by flushing the cache with `bin/magento cache:flush`

**Comment by igorwulff** [comment]
I can't access the page-builder github anymore. @chalov-anton can you give us information on how we can get access to it, and if there is already a fix for this?

**Comment by chalov-anton** [comment]
@sivaschenko Do you know how to access the Page Builder repo and check the issues state?
Thank you

**Comment by sivaschenko** [comment]
@Eddcapone @igorwulff @chalov-anton access to Page Builder repository is currently limited to Magento partners. The issue is still open and does not have a fix.
