### ISSUE TITLE
Uncaught JS Error after authorization failure on licensing image from media gallery

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1543]
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Provided _API Key (Client ID)_ 
![client_key](https://user-images.githubusercontent.com/45624059/85844326-3681fa80-b7ab-11ea-8cd2-d97d7fc19ad0.png)

### Steps to reproduce (*)

1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Save an _Unlicensed image_ Preview
(_the image appeared in Media Gallery_)
3. Go to _Stores - Configuration - Advanced - System - Adobe Stock Integration_ and **remove** the _API Key (Client ID)_. **Save Config**
![no_keys](https://user-images.githubusercontent.com/45624059/85845316-b78dc180-b7ac-11ea-8eae-f7c708832727.png)
4. Go to **Content - Media Gallery** and select the previously saved Unlicensed image
5. Click "three dots" and select **Lisense**

### Expected result (*)
Adobe error is displayed in an opened window, after closing the window no additional alerts of console errors are displayed

### Actual result (*)
Adobe error appears.
After closing the window:
`Uncaught TypeError: this.imageModel is not a function` error appears in dev console

![uncought](https://user-images.githubusercontent.com/45624059/85845412-e2781580-b7ac-11ea-9ecd-a30d049e47ae.png)

### Video!

![Peek 2020-06-26 13-09](https://user-images.githubusercontent.com/45624059/85846342-55ce5700-b7ae-11ea-8230-e15ef4866d82.gif)

**Comment by joweecaquicla** [comment]
@magento I am working on this
