### ISSUE TITLE
[Stub] Resolve the issue with saving adobe stock image using stub

### ISSUE THREAD

**Issue by coderimus** [magento/adobe-stock-integration#1544]
### Preconditions

1. Adobe Stock Integration `stub` branch is used and stub module is enabled

### Steps to Reproduce
1. Login to Admin panel
2. Open Media Gallery
3. Click "Search Adobe Stock"
4. Expand preview for any image
5. Click `Save Preview` button

### Expected Result

The popup to specify path should appear, after the confirmation, the image should be saved successfully

### Actual Result

![image](https://user-images.githubusercontent.com/2028541/90033583-88c59f00-dcb7-11ea-96be-cd4cfe324c4b.png)

**Comment by yolouiese** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
Looks like we are not going to have a possibility to finalize stab in the scope of the project, closing this issue as out of scope
