### ISSUE TITLE
Add support of PNG IPTC reading to MediaGalleryMetadata module implementation

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1553]
Add support of GIF XMP readingto MediaGalleryMetadat module implementation.

Technical Design:
https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

What needs to be done:
 - Introduce `Magento\MediaGalleryMetadata\Model\Png\Segment\IptcReader`(see examples of implementation in Png and Jpeg namespaces)
 - Add the png image containing only IPTC data to `Magento\MediaGalleryMetadata\Test\Integration\Model\ExtractMetadataTest` integration test
 - Cover the implementation with `Magento\MediaGalleryMetadata\Test\Integration\Model\AddIptcMetadataTest` integration test (should be the same as `Magento\MediaGalleryMetadata\Test\Integration\Model\AddIptcMetadataTest` however the Magento\MediaGalleryMetadataApi\Api\AddMetadataInterface instance used should be configured to use only Iptc writer)

**Comment by yolouiese** [comment]
@magento I am working on this
