### ISSUE TITLE
Grammar mistakes in "Delete image" confirmation message

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1561]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. Have two images in Media Gallery. One of the images is Used In one category, for example 

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Delete Images...**
3. Select the image which is used in one entity and one more image
4. Click **Delete Selected**
5. Observe the _Delete image_

### Expected result (*)
**These** images **are** used in 1 Category. 
![expected1](https://user-images.githubusercontent.com/45624059/86589878-24683f00-bf97-11ea-9b10-4331ef0786fb.png)

### Actual result (*)
This images **is** used in 1 Category. 
![actual](https://user-images.githubusercontent.com/45624059/86589321-241b7400-bf96-11ea-8438-1692df86453f.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
