### ISSUE TITLE
A line appears on tabs [UI]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1562]
### Description
On my monitor, I have some UI issues on specific Zoom. Namely, a line on tabs, where it should no appear 

### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock**
3. Open an image Preview 
4. Start to Zoom In and Zoom Out your web browser window
5. Observe the _More from this series_ tab
![Peek 2020-07-06 15-10](https://user-images.githubusercontent.com/45624059/86592669-8f684480-bf9c-11ea-875c-e59370b2ab90.gif)

### Expected result (*)
![line_tab_more from this_expected](https://user-images.githubusercontent.com/45624059/86592625-81b2bf00-bf9c-11ea-904a-3cf4c2504cee.png)

### Actual result (*)
![line_tab_more from this](https://user-images.githubusercontent.com/45624059/86592642-87a8a000-bf9c-11ea-9209-c68edd57e31c.png)

### Note
The same issue with **Filters** tab
![line_tab](https://user-images.githubusercontent.com/45624059/86592748-b4f54e00-bf9c-11ea-90f7-04a09ead2ee3.png)

**Comment by jmonteros422** [comment]
Hi @chalov-anton,

I have linked a pull request to fix the issue for the media gallery tabs only. For the filter tabs, it looks like this is happening as well on the magento core filters aswell. ex. Catalog > Products > Filters (Zoom at 80% and 150%).

Let me know what do you think.

Thank you!

**Comment by chalov-anton** [comment]
Hello @jmonteros422 

Yes, this issue also occurs in the Magento core.
Let me get this strait, the linked PR provides fixes for _More from this series_ and _More from this model_ tabs? 

Thank you

**Comment by jmonteros422** [comment]
> Hello @jmonteros422
> 
> Yes, this issue also occurs in the Magento core.
> Let me get this strait, the linked PR provides fixes for _More from this series_ and _More from this model_ tabs?
> 
> Thank you

@chalov-anton, that's correct.
