### ISSUE TITLE
Possible to Edit image and save it with empty name

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1573]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. An image added yo Media Gallery

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery and click "three dots" in the bottom right
3. Select **Edit**
4. Remove all the text from the _Name_ field
![name_empty](https://user-images.githubusercontent.com/45624059/86920279-36cab000-c132-11ea-8a9f-b3d470e44da7.png)
5. Click **Save** button  

### Expected result (*)
The _Name_ field is a *required field, so it should not be possible to save an image with no name

### Actual result (*)
Image with no name is saved into Media Gallery
![name_empty_saved](https://user-images.githubusercontent.com/45624059/86920473-86a97700-c132-11ea-98d0-f333a03f1797.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
