### ISSUE TITLE
Add "Edit" button to Image Details page

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1581]
### Description
Editing image is only available from _"three dots" - Edit_. 
![edit](https://user-images.githubusercontent.com/45624059/87034044-e31e9c00-c1ef-11ea-9fa7-81419e34d686.png)
According to the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/162f3177-f504-454f-82e2-f5a8f89f92e4/), the Editing should be available from _Image Details_ page

### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **View Details**
4. Verify if **Edit** button is available

### Expected result (*)
**Edit** button is available

### Actual result (*)
![no_edit_button](https://user-images.githubusercontent.com/45624059/87033995-d1d58f80-c1ef-11ea-8cf2-70f3bda4fadd.png)

**Comment by jmonteros422** [comment]
@magento I am working on this
