### ISSUE TITLE
Add "filename" information to Image Details page [Improvement]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1582]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **View Details**
4. Verify if _filename_ information is displayed
![file_name_edit_page](https://user-images.githubusercontent.com/45624059/87035925-b7e97c00-c1f2-11ea-88bc-61dd516dc1b6.png)

### Expected result (*)
The _filename_ is displayed on Image Details page
![file_name_im_det_page](https://user-images.githubusercontent.com/45624059/87035959-c33ca780-c1f2-11ea-847d-ba46cb67140f.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
