### ISSUE TITLE
Rename the field "Name" into "Title" on Edit Image page [Improvement]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1583]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **Edit**

### Expected result (*)
Rename the _Name_ into _Title_ in order not to have two different fields: _Name_ and _filename_ on the same page
![title](https://user-images.githubusercontent.com/45624059/87036188-1878b900-c1f3-11ea-9f97-2834414f338f.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
