### ISSUE TITLE
Hitting "Enter" key on Edit Image page redirects the user to Magento Dashboard instead of Saving the image

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1589]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **Edit**
4. Place the cursor into _Name_ field
5. Type any text
6. Hit Enter key from your keyboard

### Expected result (*)
The Edit Image window is closed, the file name is saved

### Actual result (*)
User is redirected to Magento Dashboard, the file name is not saved 
![Peek 2020-07-09 17-04](https://user-images.githubusercontent.com/45624059/87049960-46b3c400-c206-11ea-88bc-efd807840736.gif)

**Comment by yolouiese** [comment]
@magento I am working on this
