### ISSUE TITLE
Image description is not added or updated before page reload

### ISSUE THREAD

**Issue by konarshankar07** [magento/adobe-stock-integration#1592]
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)

1. Go to Content - Media Gallery
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select Edit
4. Add the description
5. Save
6. Click "three dots" in the bottom right for the same image which has recently updated
7. Select View Details

### Expected result (*)

1. Description should be visible

### Actual result (*)

1. Description is not visible

Note:- After manually page reload image description will be visible on image detail page

**Comment by konarshankar07** [comment]
This PR will fix this issue https://github.com/magento/adobe-stock-integration/pull/1591

**Comment by chalov-anton** [comment]
Hello @konarshankar07 
This seems to be a duplicate of https://github.com/magento/adobe-stock-integration/issues/1575

**Comment by konarshankar07** [comment]
@chalov-anton ..Yes, you are right and I'm closing this ticket
Thanks
