### ISSUE TITLE
Underscore symbol is not allowed in Image name and Description. (Edit window)

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1599]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. **Upload** an image with name containing underscore symbol, _test_1_ for example
3. Click on "three dots" near the image and select **Edit**
4. Do not, change anything, click **Save**
![Peek 2020-07-15 17-05](https://user-images.githubusercontent.com/45624059/87554945-73ac1f00-c6bd-11ea-877a-e3d9e3f47b29.gif)

### Expected result (*)
The image is saved. 

### Actual result (*)
The image name doesn't pass the validation
![underscore_validation](https://user-images.githubusercontent.com/45624059/87554346-b15c7800-c6bc-11ea-9cf6-352b50a66c34.png)
The image name, containing underscore, can be saved from Adobe Stock and Uploaded locally. Allow also to Edit.

**Comment by chalov-anton** [comment]
Please, use the same validator which is used on Saving images from Adobe Stock. The validation allows:
- Name to contain comma (,) dot (.) dash (-)
- Maximum number of characters is 128

It might look weird if user will have saved file from Adobe Stock, open Edit, and will not be able to save the image without changing anything.
![description](https://user-images.githubusercontent.com/45624059/87678309-72ddc080-c783-11ea-8f6e-3fad97d6b080.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this

**Comment by chalov-anton** [comment]
There is another issue with the Description field
When you enter some text in the first line of the Description field and hit Enter key to switch to another line... such description will not pass the validation 
![Peek 2020-07-20 16-25](https://user-images.githubusercontent.com/45624059/87942932-ff4ef280-caa5-11ea-8f36-97854897dca8.gif)
