### ISSUE TITLE
Improvements to mass delete message

### ISSUE THREAD

**Issue by konarshankar07** [magento/adobe-stock-integration#1600]
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. Upload 4 to 5 images in the Media Gallery

### Steps to reproduce (*)

1. Go to Content - Media Gallery
2. Click on Delete Images button
3. Select 3 images to delete
4. Click on delete selected button
5. Check the popup message in which number of images is present
6. Click on delete image button in the popup
7. Check the success message

### Expected result (*)

Number of image should also be present in the success message

### Actual result (*)

![image](https://user-images.githubusercontent.com/39480008/87630928-f2ec3200-c753-11ea-9e2f-de58e2d7bf4f.png)

**Comment by konarshankar07** [comment]
Hello @lenaorobei ...
Can I know the reason for removing this ticket from the backlog?
Thanks

**Comment by lenaorobei** [comment]
Hi @konarshankar07. We are now focused on finishing our commitment for 2.1.0 and this enhancement if out of scope for the current milestone. If you, however, are interested in implementing this, we will be happy to accept your contribution. Thank you!
