### ISSUE TITLE
The "See more" is not in correct position on device mode

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1604]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock**
3. Open an image Preview
4. Switch your browser to device mode
5. Observe the position of the **See more** link button

### Expected result (*)
The button is in correct position

### Actual result (*)
![see_more](https://user-images.githubusercontent.com/45624059/87682573-a838dd00-c788-11ea-8773-7550ba39c4cd.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
