### ISSUE TITLE
[Refactoring] DateTime handling and formatting

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1609]
Related to https://github.com/magento/adobe-stock-integration/issues/1578

As per code review proper DateTime handling and formatting should be used. Magento framework DateTime functionality should be utilized

Files to check:
- `MediaGalleryUi/Model/AssetDetailsProvider/CreatedAt.php` - Should it be configurable or inherited from the current Magento locale?
- `MediaGalleryUi/Model/AssetDetailsProvider/UpdatedAt.php`
- `MediaGalleryUi/Model/AssetDetailsProvider/CreatedAt.php`
- `MediaGallerySynchronization/Model/SynchronizeFiles.php`

**Comment by yolouiese** [comment]
@magento I am working on this
