### ISSUE TITLE
[Refactoring] PHP

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1614]
Related to https://github.com/magento/adobe-stock-integration/issues/1578

As per code review we need address following issues in PHP files.

- `MediaContentSynchronization/Console/Command/Synchronize.php:61`, `MediaGallerySynchronization/Console/Command/Synchronize.php:63` - Get rid of area emulation
- `MediaGalleryUi/Model/AssetDetailsProviderInterface.php:23` - Consider using AssetDetails data object instead of plain array
- `MediaGalleryUi/Plugin/ResizeSyncedFiles.php:36` - add return type
- `MediaGalleryUi/Ui/Component/Listing/Filters/Options/UsedIn.php` - It does not make sense to configure options via DI, it's better to return a plain array with all required information. Any 3d party developer is able to create a plugin in the case when the list should be extended. Also, localization will not work for values stored in the di.xml config.
- `MediaGallerySynchronizationApi/Api/SynchronizeFilesInterface.php:18` - Please, don't use generic PHP interfaces. It's better to introduce our own interface for that.
- `MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php:22` - What's the purpose of this field? Could you please add a description.
- `MediaGallerySynchronizationApi/Model/GetContentHashInterface.php` - What's the reason to keep this interface in the API module? How external developers can use it/extend? It looks like internal implementation and shouldn't be exposed via API.
- `MediaGallerySynchronization/Model/Synchronize.php:67` - Move logic to the pool initialization. According to our technical vision - any object in Magento should be ready for use after initialization, it means that pool must contain only valid elements and client code doesn't need to perform any checks.
- `MediaGallerySynchronizationApi/Model/SynchronizerPool.php:30` - Add synchronizers validation.
- `MediaGalleryRenditionsApi/Model/ConfigInterface.php:` - Why this interface located under the Model folder instead of Api?
- `MediaGallerySynchronization/Model/Filesystem/SplFileInfoFactory.php` - Define our own interface and object instead of generic
- `MediaGallerySynchronization/Model/CreateAssetFromFile.php:24` - The class should be refactored to avoid coupling.
- `MediaGalleryIntegration/etc/adminhtml/di.xml:17` - Should be moved to MediaGalleryCatalogIntegration module
- `MediaGalleryIntegration/Model/OpenDialogUrlProvider.php:16` - Is it required to extend from DataObject? I don't see any use cases.
- `MediaContentSynchronization/Model/ResourceModel/GetOutdatedRelations.php:98` - Used incorrect exception type
- `MediaContentSynchronizationApi/Api/SynchronizerInterface.php` - Should be removed
- `MediaContentSynchronizationApi/Model/Entities.php:13` - Rename to GetEntities to be consistent with interface
- `MediaGalleryCatalogUi/Model/Listing/DataProvider.php:167` - get rid of hardcoded `entity_id`
- `MediaGalleryCatalogUi/Ui/Component/Listing/Columns/Thumbnail.php:67` - DataObject? According to the method signature, it expects the Product model.

**Comment by yolouiese** [comment]
@magento I am working on this

**Comment by Nazar65** [comment]
`MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php:22 - What's the purpose of this field? Could you please add a description.` The modification date column can be null, this column needed to fetch only those entities wich was changed since last execution, so the Generator compare modification date column and if the value bigger then in last execution time they will include this item to the batch. this behavior was implemented to avoid fetch again items thats were fetched in previous synchronization

**Comment by Nazar65** [comment]
`MediaGalleryIntegration/Model/OpenDialogUrlProvider.php:16 - Is it required to extend from DataObject? I don't see any use cases.` yes please see `Magento\Ui\Component\Form\Element\DataType\Media\OpenDialogUrl:get`

**Comment by Nazar65** [comment]
`MediaGalleryIntegration/Model/OpenDialogUrlProvider.php:16 - Is it required to extend from DataObject? I don't see any use cases.` this is what we put to the
   ```<type name="Magento\Ui\Component\Form\Element\DataType\Media\OpenDialogUrl">
        <arguments>
            <argument name="url" xsi:type="object">Magento\MediaGalleryIntegration\Model\OpenDialogUrlProvider</argument>
        </arguments>
```
This is required to be DataObject
