### ISSUE TITLE
[Refactoring] Metadata

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1616]
Related to https://github.com/magento/adobe-stock-integration/issues/1578

As per code review we need address following issues related to images metadata processing:

- `MediaGalleryMetadataApi/Api/Data/MetadataInterface.php:24` - Is possible that the file will not contain the title in the metadata? Should it be nullable?
- `MediaGalleryMetadataApi/Model/ExtractMetadataPool.php:27` - Should we check the readers before adding to the pool?
- `MediaGalleryMetadataApi/Model/FileReaderInterface.php:29` - Why we need a separate method to check reader compatibility? It looks like private reader implementation as for me. Right now all client code must call isApplicable method to check if the reader is compatible for file instead of just call execute method and got an exception in case if the reader is not compatible.
- `MediaGalleryMetadata/Model/File/AddMetadata.php` - compare with `\Magento\MediaGalleryMetadata\Model\AddMetadata` and choose one
- `MediaGalleryMetadataApi/Model/FileWriterInterface.php:18` - extra new line
- `MediaGalleryMetadata/Model/AddMetadata.php` - Why we need this class? Why we just cannot use composite in the client code? It looks like an unnecessary level of abstraction.
- `MediaGalleryMetadata/Model/File/ExtractMetadata.php:98` - Please, refactor code and remove suppress warning. It's weird to introduce a new code that contradicts our guidelines.
- `MediaGalleryMetadata/Model/Gif/Segment/XmpReader.php:95` - Unnecessary var assignment.
- `MediaGalleryMetadata/Model/Gif/FileReader.php:72` - Use single quotes
- `MediaGalleryMetadata/Model/Gif/FileReader.php` - The file is too long, it would be better to split it to separate logical parts.
- `MediaGalleryMetadata/Model/Jpeg/Segment/IptcReader.php:74`, `MediaGalleryMetadata/Model/Jpeg/Segment/IptcWriter.php:108`, `MediaGalleryMetadata/Model/Jpeg/Segment/XmpReader.php:72`, `MediaGalleryMetadata/Model/Jpeg/Segment/XmpWriter.php:154` - Use strict comparison
- `MediaGalleryMetadata/Model/Jpeg/Segment/IptcWriter.php:86`, `MediaGalleryMetadata/Model/Jpeg/Segment/XmpWriter.php:134`, `MediaGalleryMetadata/Model/Jpeg/Segment/XmpWriter.php:118`, `MediaGalleryMetadata/Model/Png/Segment/XmpWriter.php:84` - should be private
- `MediaGalleryMetadata/Model/Png/FileReader.php:118`, `MediaGalleryMetadata/Model/Png/FileReader.php:131` - Add strict type
- `MediaGalleryMetadata/Model/AddIptcMetadata.php` - It's not clear where iptc metadata will be added. According to the method signature string will be returned, as not deeply involved in the feature development I don't understand what data will be returned and why it's cannot be just added to the file. Probably, class should be renamed to reflect the functionality, or at least, comment with explanation should be added.
- `MediaGalleryMetadata/Model/AddXmpMetadata.php` - The same as for app/code/Magento/MediaGalleryMetadata/Model/AddIptcMetadata.php
- `MediaGalleryMetadata/Model/ExtractMetadata.php` - Maybe it would be better to replace pool with composite and move this logic there? With such approach, we will remove current file in favor of composite usage. The same approach used for AddMetadata functionality, I don't see any reason to use two separate approaches for similar functionality.
- `MediaGalleryMetadata/Model/GetXmpMetadata.php:41` - It would be much better to have consistent interfaces for both xmp and iptc data services with SegmentInterface $segment usage instead of a string. Code from \Magento\MediaGalleryMetadata\Model\Gif\Segment\XmpReader::getXmpData can be moved to this file.
- `MediaGalleryMetadata/Model/XmpTemplate.php:50` - Need to discuss such file usage. Maybe it's possible to generate a template in the runtime instead of file reading.
- Why AddMetdata is absent fro the gif?

**Comment by Nazar65** [comment]
MediaGalleryMetadataApi/Api/Data/MetadataInterface.php:24 in case if file not contain title it will be empty string.

**Comment by Nazar65** [comment]
`MediaGalleryMetadata/Model/File/AddMetadata.php - compare with \Magento\MediaGalleryMetadata\Model\AddMetadata and choose one `It's two different classes one is responsible for writers type e.g XMP or IPTC or EXIF second one is responsible for writing XMP or IPTC or EXIF data for different images format because all formats are different for example PNG have totally different segments for XMP data then jpeg format. and merge those classes to one not a good idea

**Comment by Nazar65** [comment]
`Code from \Magento\MediaGalleryMetadata\Model\Gif\Segment\XmpReader::getXmpData can be moved to this file.` GIF XMP segment is totaly different from Jpeg XMP segment or PNG and it have different checks for XMP segment data and different structurte for all formats. so getXmpData from PNG file will not work for GIF file, and MediaGalleryMetadata/Model/GetXmpMetadata.php is responsible only for extracting metadata from xml template.

**Comment by Nazar65** [comment]
`MediaGalleryMetadata/Model/Png/FileReader.php:118, MediaGalleryMetadata/Model/Png/FileReader.php:131 - Add strict type` There is no any strict type in PHP for file stream resource, which return fopen() function. basically this is binary string
Please see https://www.php.net/manual/en/function.fopen.php and `Magento\Framework\Filesystem\Driver\File:586`

**Comment by Nazar65** [comment]
`MediaGalleryMetadata/Model/Gif/FileReader.php - The file is too long, it would be better to split it to separate logical parts.` this file works with file stream, and only get segments can be extracted to a separate part. becouse when we read file we need read it part by part byte by byte on stream.

**Comment by lenaorobei** [comment]
>MediaGalleryMetadataApi/Api/Data/MetadataInterface.php:24

Let's allow `null`.

For resources check PHPDoc blocks to reflect this.

Need to get rid of `isApplicable` and use exceptions.

Rename `Reader` & `Writer` to `Read` & `Write`.
