### ISSUE TITLE
Duplicated items in Used in Entities filters 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1618]
### Description
The issue is not reproducible constantly, but I have seen it on all **Used in** filters.
Usually, after the web page is refreshed, the issue disappears 
I will continue to investigate it and will add additional info if I find any
A low Severity is added

### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Filters**
3. Expand, for example, **Used in Pages** filter
4. Start typing _page_ into **Page Title** field

### Actual result (*)
The found entities are duplicated
![duplicated](https://user-images.githubusercontent.com/45624059/88036432-37a90c00-cb4c-11ea-9c21-3331a56a8d2c.png)
![duplicated2](https://user-images.githubusercontent.com/45624059/88036878-d59cd680-cb4c-11ea-80f1-a58bad5962d6.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
