### ISSUE TITLE
Change the position of "Show duplicates" checkbox

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1619]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Filters**
3. Observe the position of **Show duplicates** checkbox

### Expected result (*)
The checkbox is the last like on [UI Protitype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/0c2b569e-50c0-4a6d-b66b-63c03bcb0afa)

### Actual result (*)
The checkbox filter is between drop down filters
![show_duplicates](https://user-images.githubusercontent.com/45624059/88039821-bc962480-cb50-11ea-9b96-c6783e42e8ed.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
