### ISSUE TITLE
Not possible to enter multi-line image Description 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1620]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on "three dots"
3. Select **Edit** 
4. Place the cursor to the **Description** field
5. Type any text, and hit Enter key

### Expected result (*)
When you hit Enter key in the Description field, the expected behaviour is to "jump" to the next line, in order to type multiline description
Check the behaviour on **Product Description** page
![Peek 2020-07-21 12-59](https://user-images.githubusercontent.com/45624059/88040803-1d722c80-cb52-11ea-8daf-d3f02373cbd5.gif)

### Actual result (*)
The image Details are saved

**Comment by joweecaquicla** [comment]
@magento I am working on this
