### ISSUE TITLE
Modified date and time changes to original after Media Gallery synchronization

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1626]
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on "three dots"
3. Select **Edit** 
4. Change the image _Title_ by typing a new, valid text. Click **Save**
5. Click on "three dots" again and select **View Details**
6. Verify that the _Modified_ date and time has changed
![modified](https://user-images.githubusercontent.com/45624059/88156926-c84a1f80-cc12-11ea-9bc4-1da286dd51e1.png)
7. Perform `php bin/magento media-gallery:sync`
8. Refresh the web page and View the image Details again
9. Verify the _Modified_ date and time

### Expected result (*)
The _Modified_ date and time did not change to the original. 

### Actual result (*)
The _Modified_ date and time is not saved and changed to original
![modified_original](https://user-images.githubusercontent.com/45624059/88157456-75249c80-cc13-11ea-9cf4-438c95add31f.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
