### ISSUE TITLE
The loop symbol overlaps the text in Used in Products filter [Device mod]

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1641]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**,
2. In your web browser, turn on _Toggle Device Toolbar_ and select _iPad_ device fro example  
3. Click **Filters**
4. Click **Used in Products** dropdown

### Actual Result (*)
The loop symbol overlaps the _"SKU"_ text
![overlap_small_loop](https://user-images.githubusercontent.com/45624059/88378283-5eb04980-cda9-11ea-946c-f699f59358d4.png)

**Comment by joweecaquicla** [comment]
@magento I am working on this
