### ISSUE TITLE
[Refactoring] Refactor phtml templates

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1642]
#1612 

### Description (*)

Related to https://github.com/magento/adobe-stock-integration/issues/1578

As per code review we need to avoid the use of legacy syntax. More info can be found here https://devdocs.magento.com/guides/v2.4/ui_comp_guide/concepts/magento-bindings.html

Files to refactor:
- `MediaGalleryUi/view/adminhtml/templates/image_details.phtml:30`
- `MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml:28`
- `MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml:28`
- `MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml:34`

**Comment by joweecaquicla** [comment]
@magento I am working on this
