### ISSUE TITLE
Media Gallery synchronization fails on newly Saved and Edited image

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1663]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Save a new image Preview from Adobe Stock.
2. Edit the image Description.
3. Perform `php bin/magento media-gallery:sync`

### Expected result (*)
Synchronization pass successfully 

### Actual result (*)
_In Synchronize.php line 83:
  Failed to execute the following synchronizers: media_gallery_asset_synchronizer_
![failed_to_execute_asset_syncronizer](https://user-images.githubusercontent.com/45624059/88671059-83c8f300-d0ee-11ea-9578-4ab7a2eb15b6.png)

### Note:
The synchronization pass without any errors if delete the newly added image

**Comment by chalov-anton** [comment]
Further investigation discovered that the issue occurs only with .jpg files.
After Editing the image MetaData, the image is not displayed in Image Details.
![corrupted](https://user-images.githubusercontent.com/45624059/88682732-b0373c00-d0fb-11ea-8185-49b2a664ee04.png)

**Comment by namtb1994** [comment]
@chalov-anton, I have this error. Please help me.

**Comment by trandinh2409** [comment]
@chalov-anton, I have this error. Please help me. Thanks.

**Comment by chalov-anton** [comment]
Hello @trandinh2409 The bug has been fixed in this Pull Request https://github.com/magento/adobe-stock-integration/pull/1668
