### ISSUE TITLE
Bulk image delete is not working after the first attempt was canceled 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#1680]
### Preconditions (*)
1. Open Media Gallery
2. click Delete images button, observe the bulk image delete is enabled
3. Cancel deleting images

### Steps to reproduce (*)
1. Click Delete images button again

### Expected result (*)
1. Bulk image delete is enabled

### Actual result (*)
1. Delete images Button does noting 
![bulk-delete](https://user-images.githubusercontent.com/5603216/88843809-51c79780-d1a7-11ea-886f-2260fce24c41.gif)

**Comment by yolouiese** [comment]
@magento I am working on this
