### ISSUE TITLE
Login failed error contains HTML tags

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1684]
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Provided _API Key (Client ID)_ . **Not** provided _Client Secret_
![client_key](https://user-images.githubusercontent.com/45624059/85844326-3681fa80-b7ab-11ea-8cd2-d97d7fc19ad0.png)

### Steps to reproduce (*)

1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Save an _Unlicensed image_ Preview
(_the image appeared in Media Gallery_)
3. Select the previously saved Unlicensed image
4. Click "three dots" and select **License**

### Expected result (*)
Propper error message, like _"Login failed. Please check if the Secret Key is set correctly and try again."_

### Actual result (*)
The message contains HTML tags. _Login failed. Please check if `<a href="https://magento2/admin/admin/system_config/edit/section/system/">the Secret Key</a> is set correctly and try again.`_
![Selection_031](https://user-images.githubusercontent.com/45624059/88908539-ab40cc80-d262-11ea-9c25-1192b6d5eca1.png)

**Comment by yolouiese** [comment]
@magento I am working on this
