### ISSUE TITLE
The deleted tags are not removed from Tags drop-down until the web page is refreshed 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1703]
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
4. Uploaded image 

### Steps to reproduce (*)
1. Select the uploaded image by clicking on it
2. Click "three dots", select **Edit**
3. Add three new **Tags**, for example. Click **Save**
4. Click "three dots" again, and select **Edit**
5. Remove the previously added Tags by clicking on the cross (x) near them
6. Click **Save**
7. Click "three dots" again, and select **Edit**

### Expected result (*)
The Tags drop-down is empty
![tags3](https://user-images.githubusercontent.com/45624059/89173891-9bd8c080-d58d-11ea-93cc-cb1a175f2b93.png)

### Actual result (*)
The Tags drop-down still contains the previously deleted tags
![tags4](https://user-images.githubusercontent.com/45624059/89173593-2ec52b00-d58d-11ea-865b-ba6cd837df2f.png)

### Note
The tags are removed from View Details and will disappear after the web page is refreshed. It's just might be confusing for the user. Besides, the previously deleted Tags will be saved to Image Details if click Save after step number 7
**(The Tags are not removed from Database)**

**Comment by yolouiese** [comment]
@magento I am working on this
