### ISSUE TITLE
Created and Modified date are different for newly saved Image Preview

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1708]
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
 
### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock** and Save an image Preview
3. Select the previously saved preview image
4. Click "three dots", select **View Details**
5. Observe the _Created_ and _Modified_ dates

### Expected result (*)
The _Created_ and _Modified_ dates should be equal

### Actual result (*)
The _Created_ date is 7 hours earlier than _Modified_ date
![time_zone](https://user-images.githubusercontent.com/45624059/89280067-c93a7280-d650-11ea-9dd2-6b123609c1cd.png)

### NOTE
The same happens with locally uploaded images after Edit.
1. Upload an image
2. Check that the Modified And Created are equal
3. Edit image Description and Save

AR: The _Created_ date is 7 hours earlier than _Modified_ date

**Comment by sivaschenko** [comment]
@tkacheva @lenaorobei we have to decide if the created_at, updated_at should be taken from file on import or simply represent the create/updated time of database record

**Comment by tkacheva** [comment]
it makes sense to align the behavior with file management industry standards. So it's when file added/modified in that system
