### ISSUE TITLE
Support batches processing for synchronization queue messages

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1724]
### Media content bulk sync service
 - Introduce `Magento\MediaContentSynchronizationApi\Api\SynchronizeIdentitiesInterface::execute(array $contentIdentities): void` accepting the array of `ContentIdentityInterface` as a parameter
 - Intorduce the implementation of the interface `Magento\MediaContentSynchronization\Model\SynchronizeIdentities`
 - Reuse the service in existing implementations of `Magento\MediaContentSynchronizationApi\Api\SynchronizeInterface` (i.e. `Magento\MediaContentSynchronizationCatalog\Model\Synchronizer\Category::synchronizeItem`)

### Media content synchronization consumer
 - Update the media content queue consumer `Magento\MediaContentSynchronization\Model\Consume` to be able to consume the message containing information about content identities and use `SynchronizeIdentitiesInterface` if such information is present in the message

### Media gallery synchronization consumer
 - Update the media content queue consumer `Magento\MediaGallerySynchronization\Model\Consume` to be able to consume the message containing information about path's to synchronize and use `SynchronizeFilesInterface` if such information is present in the message

**Comment by yolouiese** [comment]
@magento I am working on this
