### ISSUE TITLE
MediaGalleryUi module contains selectors and pages from Adobe Stock Modules

### ISSUE THREAD

**Issue by Nazar65** [magento/adobe-stock-integration#1730]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)
Generate mftf tests without AdobeStock modules

### Expected result (*)
Generation should pass

### Actual result (*)
Generation fails with:
![image_2020_08_05T11_04_29_131Z](https://user-images.githubusercontent.com/2481206/89409442-bdbb7a00-d72a-11ea-9c5b-a0bd4b60a97c.png)

**Comment by naydav** [comment]
Merged with https://github.com/magento/magento2ce/pull/5960
