### ISSUE TITLE
Reorganize Media Gallery stores configuration UI

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1738]
### Steps to reproduce (*)
1. Login to Admin Panel
2. Go to Stores -> Configuration -> Advanced -> System

### Expected result (*)
0. **The changes should be applied to the UI only, the values or configuration path should not be affected**
1. Section label is changed from `Enhanced Media Gallery` to `Media Gallery`
2. Select label is changed from `Enable` to `Enable Old Media Gallery`
3. Select option values should be reversed
4. Corresponding MFTF action groups should be corrected
![image](https://user-images.githubusercontent.com/2028541/89554321-9e921a80-d806-11ea-89bc-cc55aca34aaf.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
