### ISSUE TITLE
[WIP]: WebAPI for AssetRepository::delete

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#174]
Declare a WebAPI endpoint for `\Magento\AdobeStockAsset\Model\AssetRepository::delete` and cover it with a WebAPI test.

Example of WebAPI declaration: https://github.com/magento/adobe-stock-integration/blob/develop/AdobeStockImage/etc/webapi.xml

**Comment by diazwatson** [comment]
@sivaschenko just wondering if we have an endpoint to `deleteById` #177 do we need this other one to delete without id?

**Comment by sivaschenko** [comment]
@diazwatson you are right, we shouldn't have 2 API method with the same purpose. Probably we should delete the `delete` method from the repository and leave only `deleteById`
