### ISSUE TITLE
Used In secrion of asset details is formatted incorrectly if more than 2 entities referenced

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1747]
### Steps to reproduce (*)
1. Add an image from media gallery to three different entities content (i.e. page, category and block)
2. View details of this image in the media gallery

### Expected result (*)
Used in entities should be listed one under another

### Actual result (*)
![image](https://user-images.githubusercontent.com/2028541/89929348-0aa6c100-dc01-11ea-913a-e336091247f3.png)

**Comment by Nazar65** [comment]
Already fixed in  https://github.com/magento/magento2/pull/29367
