### ISSUE TITLE
Media Gallery Used In filter is dropped when the page is refreshed

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1752]
### Steps to reproduce (*)
1. Open Media Gallery
2. Apply any Used In filter
3. Reload the page

### Expected result (*)
The applied filter is still applied

### Actual result (*)
The applied Used In filter is dropped

**Comment by Nazar65** [comment]
This happens only when you apply the filter and page has been immediately reloaded, and after that  bookmark component  have no ability to save the state

**Comment by sivaschenko** [comment]
@Nazar65 thanks for investigation
