### ISSUE TITLE
Tag is displayed on the "Edit Image" window in Media Gallery after clicking on the "Cancel" button

### ISSUE THREAD

**Issue by engcom-Lima** [magento/adobe-stock-integration#1754]
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled

### Steps to reproduce (*)

1. Go to Content - Media Gallery
2. Upload png image
3. Click on three dots -> Edit
4. Add tag
5. Click on the "Cancel" button
6. Click on three dots -> Edit for previously edited image

### Expected result (*)

Changes aren't saved. No any new tags.

### Actual result (*)

Tag is displayed on the "Edit Image" window in Media Gallery after clicking on the "Cancel" button
But if open the image for editing in new tab - changes aren`t shown
![Peek 2020-08-13 19-26](https://user-images.githubusercontent.com/60198022/90160933-16c68600-dd9b-11ea-81a0-f2fdc75a2f5e.gif)

**Comment by sivaschenko** [comment]
@engcom-Lima if the added tag is not present:
 - after the page refresh
 - in the view details panel of the image
 - in the edit form for another image

I don't think it is a bug. Preserving the state of the form might be actually useful (i.e. in case when Cancel button is clicked by mistake)
