### ISSUE TITLE
Extracting keywords from Exif segment

### ISSUE THREAD

**Issue by Nazar65** [magento/adobe-stock-integration#1759]
### Description (*)
after https://github.com/magento/magento2/pull/29576 will be merged 

There is two fields where keywords can be extracted:
1.` Exif.Photo.UserComment`
2. `Exif.Image.XPKeywords`

the second one per documentation is related only for WINDOWS XP guys, but there is no standard filed for keywords

Need to decide wich field we will using for extracting Keywords from Exif data, but as per description to `'Exif.Photo.UserComment'`
```
A tag for Exif users to write keywords or comments on the image besides those in <ImageDescription>, and without the character code limitations of the <ImageDescription> tag.
```
 i would prefer to use this file.

reference to official documentation https://exiv2.org/tags.html

After the field will be chosen, need to modify readers to extract keywords

1. `app/code/Magento/MediaGalleryMetadata/Model/Jpeg/Segment/ReadExif.php`
2. `app/code/Magento/MediaGalleryMetadata/Model/Png/Segment/ReadExif.php`

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by sivaschenko** [comment]
@konarshankar07 do you have any updates for this issue? I think this issue can be closed based on the discussion on the public meeting.
