### ISSUE TITLE
Media Gallery Page opened successfully if "Enhanced Media Gallery" disabled 

### ISSUE THREAD

**Issue by engcom-Lima** [magento/adobe-stock-integration#1760]
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Enhanced Media Gallery Disabled 
### Steps to reproduce (*)

1. Open `https://yourdomain.com/admin/media_gallery/media/index` link

### Expected result (*)

404 page

### Actual result (*)

Pages opened successfully
![Peek 2020-08-17 18-30](https://user-images.githubusercontent.com/60198022/90414499-88af1000-e0b8-11ea-83f9-3847841534d7.gif)

**Comment by jmonteros422** [comment]
Hi @engcom-Lima ,

I will be covering the MFTF test coverage for this task. Do we have the test case scenario ID for this one? Thank you!

**Comment by engcom-Lima** [comment]
Hi @jmonteros422 
Please see manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/5106786)

**Comment by jmonteros422** [comment]
> Hi @jmonteros422
> Please see manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/5106786)

Thank you @engcom-Lima !
