### ISSUE TITLE
Add ability to select product image from media gallery

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#178]
Currently, the media gallery is used for adding images to the most entities in Magento: pages, blocks, categories:

![image](https://user-images.githubusercontent.com/2028541/61046272-9cc41080-a3d4-11e9-91bc-8b6a232582dd.png)

However, the media gallery is not accessible from the product page:

![image](https://user-images.githubusercontent.com/2028541/61046334-bfeec000-a3d4-11e9-8403-6c1f3752dcbe.png)

As the media gallery is the entry point to Adobe Stock Integration - it should be available for adding images to the product.

This change should be done in the core Magento repository.

**Comment by konarshankar07** [comment]
I'm working on magento core repository

**Comment by sivaschenko** [comment]
Decided to postpone this functionality after closer investigation and discussion
