### ISSUE TITLE
"Active filters" shows the "Asset:" filter which is empty if switch to the Default View again 

### ISSUE THREAD

**Issue by engcom-Lima** [magento/adobe-stock-integration#1780]
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. New Media Gallery Enabled
4. Image added to a category
### Steps to reproduce (*)

1. Go to Content -> Media Gallery
2. Select the image that is added to the category by clicking on it
3. Click on three dots -> View Details 
4. Click on the link 'Categories..." in 'Used in' attribute
5. Delete the `?filters[asset_id]=[1]` part of request from address line -> Press `Enter` key
6. Click on the "Clear all" link
7. Wait for a few seconds and reload the page
8. Click on the "Default View" dropdown
9. Select the  "Default View" by clicking on it

### Expected result (*)

No Active filters

### Actual result (*)

"Active filters" shows the "Asset:" filter which is empty 
[Video](https://drive.google.com/file/d/1spREJfBLtRii0I0JujyHshz0E1Rjr59o/view?usp=sharing)
![Screenshot_121](https://user-images.githubusercontent.com/60198022/90918372-31c57580-e3ed-11ea-80e1-7bbf191c97cb.png)

**Comment by Nazar65** [comment]
already fixed in https://github.com/magento/magento2/pull/29633
