### ISSUE TITLE
Replace DocumentToAssetTest unit test with an integration test

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1786]
Replace `\Magento\AdobeStockImage\Test\Unit\Model\Extract\DocumentToAssetTest` unit test with an integration test

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by sivaschenko** [comment]
Hi @konarshankar07 are you working on this issue?

**Comment by konarshankar07** [comment]
Hello @sivaschenko ...
Sorry for the delay and yes, I'm working on this ticket and try to clear this in this week
Thanks
