### ISSUE TITLE
Cover GetAssetListInterface with an integration test

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1787]
Cover `\Magento\AdobeStockAssetApi\Api\GetAssetListInterface` with an integration test.
The test should be located in the `AdobeStockAsset` module.
To exclude external dependencies for the integration test - the `Magento\AdobeStockClientApi\Api\ClientInterface` preference should be replaced with a mock in the test setUp.
I.e.:

```
        Bootstrap::getObjectManager()->configure([
            'preferences' => [
                ClientInterface::class => \Magento\AdobeStockAsset\Test\Integration\Model\ClientMock::class
            ]
        ]);
```

**Comment by yolouiese** [comment]
@magento I am working on this
