### ISSUE TITLE
Category image is not removed from tmp folder after category save action if image with same name already exists in catalog/category folder

### ISSUE THREAD

**Issue by Nazar65** [magento/adobe-stock-integration#1792]
### Preconditions (*)

1 magento 2.4-develop

### Steps to reproduce (*)

1. Create Category
2. Upload main category image from the uploader widget with filename wich already exists in catalog/category folder
3. Save Category
4. Open Media gallery

### Expected result (*)
There is only one image In catalog/category folder and  catalog/tmp/category folder not contains same image

### Actual result (*)
There is two images in catalog/category and catalog/tmp/category folders

**Comment by engcom-Golf** [comment]
@magento I am working on this

**Comment by engcom-Golf** [comment]
@magento add to contributors team

**Comment by engcom-Golf** [comment]
@magento add to contributors team

**Comment by engcom-Golf** [comment]
@magento I am working on this
