### ISSUE TITLE
User is not scrolled up to the "Login failed. Please check if the Secret Key..." error, and can miss the message

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1801]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Old Media Gallery enabled in Stores -> Configuration -> Advanced-> System -> Media Gallery -> Enable Old Media Gallery - Yes
![old_med_gall_settings](https://user-images.githubusercontent.com/51680745/91861360-65b65b80-ec75-11ea-8486-b497ba4c1748.png)
4. Provided _API Key (Client ID)_ . **Not** provided _Client Secret_
![client_key](https://user-images.githubusercontent.com/45624059/85844326-3681fa80-b7ab-11ea-8cd2-d97d7fc19ad0.png)
5. Multiple images saved to Media Gallery, (four rows of images in my case)
6. Unlicensed image preview saved to Media Gallery being at the bottom of images

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Scroll to the bottom of the page
3. Select the previously saved Unlicensed image
4. Click "three dots" and select **License**

### Expected result (*)
User is scrolled to the top of the page and is able to see the error message

### Actual result (*)
_Login failed. Please check if the Secret Key is set correctly and try again._  message appears but it is not visible 
![licensing message](https://user-images.githubusercontent.com/45624059/91977808-df108580-ed2b-11ea-91a4-ba19d66faba7.gif)

**Comment by yolouiese** [comment]
@magento I am working on this
