### ISSUE TITLE
Long image name doesn't fit into License "Adobe Stock Images...?" message

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1809]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Unlicensed image Preview saved into Media Gallery

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**, select the previously used image
2. Click "three dots" and select **Edit**
3. Type the maximum number of symbols into the _Title_ field (128 symbols). Click **Save**
4. Select the previously edited image, and click "three dots"
5. Click **License**
6. Observe the image name in the _License Adobe Stock Images...?_ message 

### Expected result (*)
 The image title fits into the message

### Actual result (*)
The image title doesn't fit into the message
![Selection_084](https://user-images.githubusercontent.com/51680745/92248489-7531e080-eed1-11ea-8a7c-8c15dc499825.png)

**Comment by engcom-Bravo** [comment]
Related to https://github.com/magento/adobe-stock-integration/issues/1108
