### ISSUE TITLE
"Uncought TypeError" if switch to Default View when asset filter is applied

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1845]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. An image Used in a product

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**, select the image which is used in a Product
2. Click "three dots" and select **View Details**
3. Click on Used in **Products(1)** link
(User is redirected to Products grid and Asset filter is applied)
4. Click on **Default View** dropdown
5. Select **Default View**
6. Observe the browsers dev console (F12)

### Expected result (*)
The view is switched to Default, all the products are displayed,  no error messages in dev console

### Actual result (*)
❌ _Uncaught TypeError: Cannot read property 'ids' of undefined_ error message in dev console
![uncought_id_undefined](https://user-images.githubusercontent.com/45624059/93781894-8a796f80-fc32-11ea-8b33-84db95c15422.png)

**Comment by engcom-Golf** [comment]
Hi @chalov-anton, could you please review the steps you have described? I was not able to reproduce this issue following these steps.

**Comment by chalov-anton** [comment]
Hello @engcom-Golf 

I have rechecked this issue on the latest codebase, and it is NOT reproducible. I'm closing this issue.

Thank you
