### ISSUE TITLE
MFTF Tests after conditions should start from the media gallery reopening

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1852]
If one of Adobe Stock tests that are saving image preview fails: the subsequent tests are going to fail as the saved preview image fails to be deleted. The root cause of this problem is the after section of the test is assuming the Media Gallery page is opened (that might not be the case)

To avoid subsequent failures: after section should reopen the media gallery page before further operations.

As an additional stability measure it might make sense to remove all images present in the media gallery before the test execution.

### Tests to update
1. AdminStandaloneMediaGallerySearchByKeywordTest
2. AdminAdobeStockVerifyUnlicensedLabelTest
3. AdminMediaGalleryViewAdobeStockDetailsTest
4. AdminStandaloneMediaGallerySearchByKeywordTest
5. AdminStandaloneMediaGalleryViewAdobeStockDetailsTest

**Comment by engcom-Foxtrot** [comment]
@magento I am working on this
