### ISSUE TITLE
Mark interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#1858]
The following interfaces should be marked as API:
1. adobe-ims/AdobeImsApi/Api/LogInInterface.php
1. adobe-ims/AdobeImsApi/Api/LogOutInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Asset/Command/DeleteByIdInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Asset/Command/LoadByIdInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Asset/Command/LoadByIdsInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Asset/Command/SaveInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Category/Command/DeleteByIdInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Category/Command/LoadByIdInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Category/Command/SaveInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Creator/Command/DeleteByIdInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Creator/Command/LoadByIdInterface.php
1. adobe-stock-integration/AdobeStockAssetApi/Model/Creator/Command/SaveInterface.php
1. adobe-stock-integration/AdobeStockClient/Model/SearchParameterProviderInterface.php
1. adobe-stock-integration/AdobeStockClientApi/Api/ClientInterface.php

The changes should be targeted to `future-develop` branch

**Comment by coderimus** [comment]
@magento I am working on this

**Comment by AndreyChorniy** [comment]
@magento I am working on this
