### ISSUE TITLE
[Story #1] User accesses stock images from Magento Admin

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#22]
## Story

As a *Merchant*, I want to access and browse Adobe stock images inside Magento Admin Panel through the fully integrated business friendly user interface. Images include photos and illustrations.

## Business Value

no need to switch between different systems (Adobe Stock and Magento) to access stock images
## Preconditions 
* User logged into Magento Admin Panel 
* Adobe Stock API credentials are stored in Magento.

## Acceptance Criteria

* Admin user access stock images from Magento Media Gallery. If API credentials are missing, user can't access stock images. 
* Admin user sees the most recent stock images
* Admin user sees 32 images per page
* Admin user uses pagination to see the next/previous page

![image-grid](https://user-images.githubusercontent.com/11355520/57539396-0f9b0780-7310-11e9-9b5e-db3e3ef8a74b.jpg)

### Issues related to the story
- [Admin user access stock images from Magento Media Gallery](https://github.com/magento/adobe-stock-integration/issues/1)
- [Admin user sees default images on the slide out panel](https://github.com/magento/adobe-stock-integration/issues/2)
- [Search API endpoint implementation](https://github.com/magento/adobe-stock-integration/issues/3)
- [Introduce image listing UI component](https://github.com/magento/adobe-stock-integration/issues/4)
- [Introduce pagination for image listing UI component](https://github.com/magento/adobe-stock-integration/issues/5)

**Comment by TomashKhamlai** [comment]
Tests that are ready for Automation:
- [x] [User accesses stock images from Magento](https://app.hiptest.com/projects/131313/test-runs/271976/folder-snapshots/2430893/scenario-snapshots/9234652/test-snapshots/11887042)
- [x] [User cannot access stock images from Magento without token](https://app.hiptest.com/projects/131313/test-runs/271976/folder-snapshots/2430893/scenario-snapshots/9234651/test-snapshots/11887041)

(WIP) Additional tests will be added later.

Covers:
#22, #1, #2, 
Last Updated: Jun 13 16:25 UTC
