### ISSUE TITLE
Expected Magento\Framework\Model\AbstractModel, got Asset

### ISSUE THREAD

**Issue by diazwatson** [magento/adobe-stock-integration#224]
```
Expected Magento\Framework\Model\AbstractModel, got Asset
```
in
https://github.com/magento/adobe-stock-integration/blob/2d39cf7cd85de72347870afb7d0fb64f3b4ac02b/AdobeStockAsset/Model/AssetRepository.php#L128

### Preconditions (*)

1. checkout develop branch

### Steps to reproduce (*)

1. Delete an asset by id (currently the quickest way to do it is using a Web API functional test)

### Expected result (*)

1. Asset is instantiated
2. Asset is deleted

### Actual result (*)

```
Uncaught TypeError: Argument 1 passed to Magento\Framework\Model\ResourceModel\Db\AbstractDb::load() must be an instance of Magento\Framework\Model\AbstractModel, instance of Magento\AdobeStockAsset\Model\Asset given, called in Sites/adobestock/ext/magento/stock-integration/AdobeStockAsset/Model/AssetRepository.php on line 128 and defined in Sites/adobestock/lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php:353
```

**Comment by sivaschenko** [comment]
Hm, @sidolov @diazwatson I think `Asset` should extend `AbstractModel`
