### ISSUE TITLE
[Adobe Stock API] Number of returned results depends on request parameters other than limit

### ISSUE THREAD

**Issue by shikhamis11** [magento/adobe-stock-integration#230]
### Preconditions:

* Retrieve API Key for Adobe Stock API from https://console.adobe.com/integrations
* Use the following headers for performing requests:
   * `x-api-key: <your api key>`
   * `x-product: <you custom product name, basically any string>`

### Request 1 (without words):

    https://stock.adobe.io/Rest/Media/1/Search/Files
    ?locale=en_US
    &search_parameters[offset]=0
    &search_parameters[limit]=2
    &result_columns[0]=nb_results
    &result_columns[1]=comp_url

One line for copying:

    https://stock.adobe.io/Rest/Media/1/Search/Files?locale=en_US&search_parameters[offset]=0&search_parameters[limit]=2&result_columns[0]=nb_results&result_columns[1]=comp_url

### Response 1 (3 results):

    {
    "nb_results": 155818172,
    "files": [
        {
            "comp_url": "https://stock.adobe.com/Rest/Libraries/Watermarked/Download/278471896/2"
        },
        {
            "comp_url": "https://stock.adobe.com/Rest/Libraries/Watermarked/Download/279147307/2"
        },
        {
            "comp_url": "https://stock.adobe.com/Rest/Libraries/Watermarked/Download/278471696/2"
        }
    ]
    }

### Request 2 (with words):

    https://stock.adobe.io/Rest/Media/1/Search/Files
    ?locale=en_US
    &search_parameters[offset]=0
    &search_parameters[limit]=2
    &result_columns[0]=nb_results
    &result_columns[1]=comp_url
    &words=apple

One line for copying:

    https://stock.adobe.io/Rest/Media/1/Search/Files?locale=en_US&search_parameters[offset]=0&search_parameters[limit]=2&result_columns[0]=nb_results&result_columns[1]=comp_url&words=apple

### Response 2 (2 results):

    {
    "nb_results": 155818172,
    "files": [
        {
            "comp_url": "https://stock.adobe.com/Rest/Libraries/Watermarked/Download/278471896/2"
        },
        {
            "comp_url": "https://stock.adobe.com/Rest/Libraries/Watermarked/Download/279147307/2"
        }
    ]
    }

**Comment by sidolov** [comment]
@sivaschenko I believe current issue already fixed, please, re-check

**Comment by sivaschenko** [comment]
The issue cannot be reproduced if the words parameter is set
