### ISSUE TITLE
[Story #3] User views the image details

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#24]
## Story
As a Merchant I want to view stock image attributes inside Magento Admin Panel when I search for the stock images 

## Business Value
provide information for user to take informative decision if the stock image is the right fit for their purposes

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User searched stock images inside Media Gallery
* Admin User sees the images matching search request

## Acceptance Criteria
* User selects the image in search results to view details
* User sees following image attributes without page reload:
* * thumbnail_500 -  Extra large (XL) (500 px) image returned with watermark. 
* * id - Asset's unique identifier
* * title - Asset's title
* * content-type - Mime type of the asset's content
* * width - Width in pixels of the full-sized original asset
* * height - Height in pixels of the full-sized original asset
* User sees selected image in the search result 
* User selects next image in the grid to view details of and sees the image attributes updated.
* User scrolls down the page and sees image details going up
* User hides image details by closing them or selecting this image in the grid once again

![image-simple](https://user-images.githubusercontent.com/11355520/57539939-33ab1880-7311-11e9-95a8-03b98f41aa1e.jpg)

### Issues related to the story
- [Expand image view on image click](https://github.com/magento/adobe-stock-integration/issues/8)
- [Render image attributes on the preview](https://github.com/magento/adobe-stock-integration/issues/9)

**Comment by sivaschenko** [comment]
@belbiy please provide design for vertical and horizontal picture.

Add margin on top and bottom.
Add additional attributes to view
