### ISSUE TITLE
Change the "Enabled" stores configuration field to switch

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#243]
Change the "Enabled" stores configuration field to switch

*Actual UI:*

![image](https://user-images.githubusercontent.com/2028541/61639693-e72a7480-ac93-11e9-82f8-888db1c93d18.png)

*Desired UI:*
![image](https://user-images.githubusercontent.com/2028541/61639787-0aedba80-ac94-11e9-8747-4fcfd5b0d0d4.png)

**Comment by Karlasa** [comment]
@sivaschenko 
Hi! 
Shouldn't we improve Magento_Config module instead to have switch type available for other modules as well? 

Cheers, 
Karla

**Comment by sivaschenko** [comment]
Hi @Karlasa how do you propose to improve Magento_Config module?

**Comment by Karlasa** [comment]
No idea, but was just wondering why all "is enabled" settings under system configuration are dropdowns in Magento.

**Comment by konarshankar07** [comment]
Hello @sivaschenko 
I think we can create a frontend model for the switcher so we can use that model to convert checkbox to the switcher. Is it possible?

**Comment by sivaschenko** [comment]
@Karlasa got it. I was sure there is a switcher for Stores Configuration, it appears it is only available for UI components forms.

@konarshankar07 we should not introduce a custom switcher implementation in scope of Adobe Stock Implementation, please close this issue in case there are no reusable implementations that we can apply

**Comment by konarshankar07** [comment]
Hello @sivaschenko,
We don't have any reuseable component for the switcher so I'm closing this issue
Thanks
