### ISSUE TITLE
Test connection to Adobe Stock Integration API when the stores configuration page is opened

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#251]
Test connection to Adobe Stock Integration API when the Stores Configuration page is opened

### Steps to reproduce (*)
1. Login to Admin Panel
2. Go to Stores -> Configuration → System tab and expand Adobe Stock Configuration fieldset

### Expected result (*)
Initial test connection result is displayed without hitting the "Test Connection" button

![image](https://user-images.githubusercontent.com/2028541/61817333-34e6de80-ae46-11e9-9173-7add3f0c4c87.png)

**Comment by sidolov** [comment]
Cannot reproduce on the latest changes. Closing this issue as not relevant.
