### ISSUE TITLE
[Adobe Stock API] Total number of search results depends on page (offset) if words are not set for the request

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#257]
### Preconditions:

* Retrieve API Key for Adobe Stock API from https://console.adobe.com/integrations
* Use the following headers for performing requests:
   * `x-api-key: <your api key>`
   * `x-product: <you custom product name, basically any string>`

### Request 1:

    https://stock.adobe.io/Rest/Media/1/Search/Files?search_parameters[offset]=0

### Response 1:

    {
    "nb_results": 155816921,
    "files": [
    ...
    ]
    }

### Request 2:

    https://stock.adobe.io/Rest/Media/1/Search/Files?search_parameters[offset]=2

### Response 2:

    {
    "nb_results": 155820740,
    "files": [
    ...
    ]
    }

**Comment by chfabbro** [comment]
@sivaschenko That is odd. I will research this, but can you give a more realistic use case? Why would you send no parameters? One issue is that assets are continuously being added and removed from the index (thousands of changes a day), so the number could be different at any given time. Further, Stock adds Premium content to search results, which can artificially inflate the count.

**Comment by sivaschenko** [comment]
@chfabbro this issue can be reproduced with any other parameters as well, the request is simplified to emphasize the important parameter

**Comment by sivaschenko** [comment]
@chfabbro you are right, the issue can be reproduced only when words is not set

**Comment by sidolov** [comment]
@sivaschenko , @chfabbro looks like https://github.com/magento/adobe-stock-integration/issues/97 is related to the current issue

**Comment by chfabbro** [comment]
> @sivaschenko , @chfabbro looks like #97 is related to the current issue

@sidolov Not exactly, but there is a workaround. I commented to the assigned dev that you should always explicitly set a flag for Premium assets to "true," "false" or "all." Without this setting, the pagination value may be off by ~10. 

I really need to document this :)

**Comment by sivaschenko** [comment]
Resolved in our project by setting Premium level flag for each request
