### ISSUE TITLE
[Story #4] User saves image preview

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#26]
## Story
As a Merchant I want to save stock image preview directly into Magento Media Storage to be able to insert it into website content 

## Business Value
no need manually download image preview locally and re-upload it into Magento Media Storage 
## Preconditions 
* Admin User is logged into Admin Panel
* Admin User found the stock  image to download preview

## Acceptance Criteria
* User saves image preview 
* User sees the image uploaded into the currently selected folder of Magento Media Gallery 
* The image is selected
* The following image attributes associated with the stock image are saved into Magento DB:
  * id - Asset's unique identifier 
  * title - Asset's title
  * creator_id - Unique identifier for the asset's creator
  * creator_name - Asset creator's name	
  * creation_date - Date on which the asset was created			
  * is_licensed - license applied
  * width - Width in pixels of the asset's complementary (unlicensed) image
  * height	- Height in pixels of the asset's complementary (unlicensed) image	
  * category - JSON structure with information about the category assigned to the asset
  * category{id}
  * category{name}
  * keywords - List of keywords for the asset
  * media_type - custom Magento attribute. Value is based on stock media_type_id.
  * content-type - Mime type of the asset's content. E.g.image/jpeg
* If Adobe Stock server is not responding, user sees timeout message

**Comment by TomashKhamlai** [comment]
Do we already know the names of DB tables for these attributes?

**Comment by sivaschenko** [comment]
@tkacheva please update file name requirement

**Comment by sivaschenko** [comment]
@tkacheva let's move the new requirement for file naming to a separate story in Phase 2 and close this story

**Comment by tkacheva** [comment]
@sivaschenko ok!
