### ISSUE TITLE
Add styles for authentication error message when licensing an image

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#260]
Add styles for the authentication error message when licensing an image

# Preconditions

1. Setup adobe stock integration https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide

# Steps:

1. Login to Admin Panel
2. Go to Cms -> Pages
3. Create or edit any page
4. In the content editor insert an image
5. Open Magento media gallery
6. Click "Search Adobe Stock" button
7. Click on any image

Current UI:

![image](https://user-images.githubusercontent.com/2028541/61981839-bda27d80-aff2-11e9-80ec-67d89deb533d.png)

Design:

![image](https://user-images.githubusercontent.com/2028541/61983877-f560f380-aff9-11e9-9fde-244be1cb9ba3.png)

**Comment by sivaschenko** [comment]
@belbiy can you please suggest a design for this error message

**Comment by kieran-s48** [comment]
I'll pick this up

**Comment by diazwatson** [comment]
it is yours now :)

**Comment by kieran-s48** [comment]
Hi Everyone, how can this issue be replicated?

**Comment by sivaschenko** [comment]
@kieran-s48 steps for replication have been added to issue description

**Comment by sivaschenko** [comment]
@kieran-s48 the issue is resolved in https://github.com/magento/adobe-stock-integration/pull/302
