### ISSUE TITLE
Overlay functionality is broken

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#266]
### Preconditions (*)

1. Enable overlay for images - change visible value to `true` for `overlay` column in the `AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml`
```xml
<column name="overlay" component="Magento_AdobeStockImageAdminUi/js/components/grid/column/overlay">
     <settings>
          <label translate="true">Overlay</label>
          <bodyTmpl>Magento_AdobeStockImageAdminUi/grid/column/overlay</bodyTmpl>
          <visible>true</visible>
          <sortable>false</sortable>
     </settings>
</column>
```

### Steps to reproduce (*)

1. Open Adobe Stock Integration panel
2. Hover any image

### Expected result (*)

1. Overlay displays for every image

### Actual result (*)

1. Overlay is broken
<img width="1159" alt="Screen Shot 2019-07-29 at 15 06 16" src="https://user-images.githubusercontent.com/11355520/62078903-3e3fc480-b213-11e9-8045-42d38a8e29c7.png">

**Comment by diazwatson** [comment]
Not sure if related but in my case all images show grouped
![Screenshot 2019-07-29 at 23 44 38](https://user-images.githubusercontent.com/1080386/62087919-618e6200-b25b-11e9-9dd6-79f6618a7015.png)

**Note** In my case, changing values  for overlay in overlay
```
AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
```
does not make any difference.
