### ISSUE TITLE
Test Connection Result must be green When successful result

### ISSUE THREAD

**Issue by engcom-Golf** [magento/adobe-stock-integration#271]
### Preconditions (*)
Try to configure credentials to AdobeStock
### Steps to reproduce (*)
1. Go to Store -> Configuration -> Advanced -> System -> Adobe Stock Integration
2. Fill required fields Api key
3. Click Test Connection

### Expected result (*)
Green box with check mark 
Test Connection Result must be green When successful result

### Actual result (*)
![DeepinScreenshot_select-area_20190801110320](https://user-images.githubusercontent.com/51681547/62276696-4be08e80-b44d-11e9-9316-10d008d25fa2.png)

**Comment by kieran-s48** [comment]
Hi, can this be assigned to me please?

**Comment by diazwatson** [comment]
You have it 👍

**Comment by sidolov** [comment]
Cannot reproduce on the latest changes. Closing this issue as not relevant
