### ISSUE TITLE
Search image result has image download state.

### ISSUE THREAD

**Issue by coderimus** [magento/adobe-stock-integration#275]
**FEATURE DESCRIPTION**

The search image result can have the image download state which identifies is image already downloaded and stored at the Magento media storage or not. It should help the end-user to see is image already downloaded.

According to the data storage structure, I think, that it is also possible to show the path to the stored image. If this sounds like a business or customer usage value we can add the path description to the is image downloaded notification text. Also, this attribute value can be used to identify that the image downloaded or not.

**Comment by sivaschenko** [comment]
@coderimus thanks for the feature request.

We can identify if the image was downloaded or licensed using a request to `adobe_stock_asset` table: if the record for `media_id` is present - the image was downloaded, if `is_licensed` is `1` - it was licensed.

Can you please clarify the feature request? Some information about how do you imagine it in the UI would help. Thanks!

**Comment by sivaschenko** [comment]
The downloaded asset step will be reflected in the image preview with help of "Locate" functionality that will be delivered in https://github.com/magento/adobe-stock-integration/pull/406
