### ISSUE TITLE
Remove unnecessary conversions of asset when loading it from API

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#285]
Remove unnecessary conversions of the asset when loading it from API

### Displaying assets in the grid UI

| Class::method                                                               | Type before conversion                              | Type after conversion                               | Comment |
|-----------------------------------------------------------------------------|-----------------------------------------------------|-----------------------------------------------------|---------|
| \Magento\AdobeStockClient\Model\Client::search                              | \AdobeStock\Api\Models\StockFile                    | \Magento\Framework\Api\Search\DocumentInterface     |         |
| \Magento\AdobeStockImage\Model\GetImageList::execute                        | \Magento\Framework\Api\Search\DocumentInterface     | \Magento\AdobeStockAssetApi\Api\Data\AssetInterface |         |
| \Magento\AdobeStockImageAdminUi\Model\Listing\DataProvider::getSearchResult | \Magento\AdobeStockAssetApi\Api\Data\AssetInterface | \Magento\Framework\Api\Search\DocumentInterface     |         |

### Retrieving asset information for save operation:

| Class::method                                                               | Type before conversion                              | Type after conversion                               | Comment |
|-----------------------------------------------------------------------------|-----------------------------------------------------|-----------------------------------------------------|---------|
| \Magento\AdobeStockClient\Model\Client::search                              | \AdobeStock\Api\Models\StockFile                    | \Magento\Framework\Api\Search\DocumentInterface     |         |
| \Magento\AdobeStockImage\Model\GetImageList::execute                        | \Magento\Framework\Api\Search\DocumentInterface     | \Magento\AdobeStockAssetApi\Api\Data\AssetInterface |         |

## Solution

Replace `\Magento\AdobeStockImageAdminUi\Model\Listing\DataProvider` with custom implementation of `\Magento\Framework\View\Element\UiComponent\DataProvider\DataProviderInterface` that works with `\Magento\AdobeStockAssetApi\Api\Data\AssetInterface`

**Comment by diazwatson** [comment]
@sivaschenko ready to discuss this when you ready :)

**Comment by sivaschenko** [comment]
@diazwatson the description has been updated with the details

**Comment by diazwatson** [comment]
Has dependency on #298
