### ISSUE TITLE
[Story #6] User configures Adobe Stock integration

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#29]
## Story
As a Merchant I want to configure Adobe Stock integration on my Magento instance

## Business Value
no need to maintain API credentials on Magento side
 
## Preconditions 
* Admin User is logged into Admin Panel
* User configured new Adobe Stock integration on adobe.io console

## Acceptance Criteria
* User goes Media Gallery and opens Adobe Stock. User sees message that Adobe Stock disabled and API is missing with the link to Store-Configuration-Advanced-System. User clicks the link and navigates to Adobe Stock Integration configuration options
* User enables Adobe Stock
* User sees the following required fields in empty state:
  * API Keys (x-api-key)
* User sees a message that explains how to get these credentials with a link to [Adobe.io](https://console.adobe.io)
* User copies API key generated on Adobe.io side and inserts it into the API key field
* User sees a message that API key is valid. If user inserted wrong API key, error message displayed.  <strike>Configuration can't be saved with not valid API key</strike>
* <strike>User copies name that they chose for the integration when created it on adobe.io console</strike>
* User saves configuration 
* If API key is invalid, user sees message about that next the API Keys field. Configuration is saved with the wrong key
* User goes Media Gallery and opens Adobe Stock. If API key is invalid, user sees message about that. No image search possible. 
 
https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/bf0d5d64-e91b-4b77-9926-a3ca7946d808/Configuration

**Comment by TomashKhamlai** [comment]
@sidolov, considering this acceptance criterion "User sees the following required fields in the empty state: - API Keys (x-api-key)" does it means that this scenario is valid?

User enables Adobe Stock Integration
User copies credentials from console.adobe.io and saves the configuration
User flushes cache
User disables Adobe Stock Integration and saves the configuration
User flushes cache
User enables Adobe Stock Integration
User sees the following required fields in the empty state: - API Keys (x-api-key)

or this criterion means only that Magento doesn't include any credentials out of the box?

**Comment by sidolov** [comment]
@TomashKhamlai I believe this statement valid only for the first time when you don't have any credentials at all. Once you filled the field and saved the configuration you should see the filled field (hidden, password style)
