### ISSUE TITLE
Search API endpoint implementation

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#3]
### Description
- Define an interface for the API endpoint
- Implement request builder 
- Define request builder configuration is defined in XML and extensible for 3d party developers:
   - Filters configuration
   - Sorting configuration
   - Pagination configuration
- Define GET web-api endpoint for search
- Cover endpoints with the unit, web-api integration tests

### Documentation
Story: [User accesses stock images from Magento Admin](https://github.com/magento/adobe-stock-integration/issues/22)
Design document: [Adobe Stock Image Search Design](https://github.com/magento/adobe-stock-integration/wiki/Adobe-Stock-Image-Search-Design)

### QA notes
- User can view 32 images from Adobe Stock
- Tests are passing

**Comment by kkdg** [comment]
Working on this,

**Comment by kkdg** [comment]
Thanks

**Comment by sidolov** [comment]
Hi @kkdg , please, check the last commits to the develop branch, we have already implemented the API endpoint and I'm going to close this issue as done.
