### ISSUE TITLE
[Story #7] Adobe and Magento teams views report on Adobe Stock integration KPIs

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#30]
## Story

As a Magento/Adobe product manager I want to understand the actual level of interest that Magento merchants have to integrated stock images by tracking the number of search requests, saved preview images and licensed images via Adobe Stock-Magento integration. 

## Business Value

collect metrics to evaluate product success

## Acceptance Criteria
* All requests to Adobe Stock that merchants send need to include static identifier in the header of request. 
* The value of this identifier needs to be hardcoded

**Comment by chfabbro** [comment]
@sidolov Does Magento integrate with any analytics provider today to measure UI interactions? I can suggest workflows for measuring API searches and clickthroughs to Adobe Stock, but Stock cannot measure user engagement in the UI without support from the Magento platform.

**Comment by sidolov** [comment]
We will use `x-request-id` header for requests stats.

**Comment by sivaschenko** [comment]
@tkacheva moving this story to the second phase as it depends on SDK implementation

**Comment by chfabbro** [comment]
@tkacheva I think we should have a separate conversation with the Stock Analytics team, as they have a process for pulling reports of Stock API usage based on particular headers. This data would be available to Magento and internal Adobe users, but probably not available publicly. However, this would only track API usage (search/licensing) but not in-app interactions. If you also want to track, for example, the number of times someone clicks the search button or chooses filters, or opens a preview image in the Magento UI, then you should be using a separate analytics provider for that like Adobe Analytics or Google Analytics.

**Comment by tkacheva** [comment]
@chfabbro do you suggest not to implement this story with community effort? 
This is indeed the solution for us to track the efficiency of the integration.

**Comment by chfabbro** [comment]
@tkacheva Can you confirm the requirements/KPIs? Are these the only metrics you want to capture?

  - Number of searches per integration 
    + Confirm this is not at user level, but at merchant level, per API key
  - Number of licenses per integration
    + Same question as above
  - Number of previews downloaded

FYI, the first two could come from Adobe Stock analytics, but not the third. Stock does not track download of previews. This would have to happen at the client level inside the integration. This could be implemented by your community, if you gave them an analytics endpoint they need to call when a download occurs.

The first two would require some kind of static data point, such as product name or product location header.

**Comment by tkacheva** [comment]
@chfabbro 
>Number of searches per integration
in my understanding for us it's important to see how many image searches users perform via Magento integration overall. Unless we can additionally pass some data about a user (like commerce/OS).

> Number of licenses per integration
Same as above. Don't want to overcomplicate stuff so we end up with no data at all. 

> Number of previews downloaded
That will be great to track so we understand the ratio between preview images saved and image licensed. 

LEt's discuss on next meeting what it takes to achieve those.

**Comment by sivaschenko** [comment]
`magento-adobe-stock-integration` product name (`x-product` request header) can be used for identifying requests from Magento Adobe Stock Integration.

**Comment by filmaj** [comment]
@sivaschenko it seems like the `X-Product` header should also include the integration version number, here is the guidance we received from @chfabbro:



|Header | Type | Default Value | Required | Detail|
|--- | --- | --- | --- | ---|
|X-Product | string | none | Y | The X-Product is required to identify the calling product and should always contain a version. The productID should be the IMS clientID if possible. Example: Photoshop/15.2.0 |

**Comment by chfabbro** [comment]
The definition above comes from an internal Adobe Stock wiki, but is written this way for collecting metrics. Some additional examples are publicly available here: https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/api/10-headers-for-api-calls.md

**Comment by sivaschenko** [comment]
Magento version is included in the X-Product header (i.e. `Magento/2.3.4`)
