### ISSUE TITLE
[Story #22] User views licensed images in the grid

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#309]
## Story
As a Merchant of Magento Community edition I want to recognize images that already licensed in image search results *so that* I can add them to Magento Media Gallery without licensing them again

## Business Value
ability to programmatically upload an image that licensed before, but hasn't been saved into Media Gallery 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User is logged into Adobe Stock
* Stock image search result includes images that have been already licensed

## Acceptance Criteria
* User sees "Licensed" label on the image that has been already licensed

**Comment by tkacheva** [comment]
@sivaschenko there is no Licensed label when I see licensed image 

<img width="1721" alt="Screen Shot 2019-11-01 at 4 06 00 PM" src="https://user-images.githubusercontent.com/5603216/68056720-d3929f00-fcc1-11e9-8ce6-25e45726d6a2.png">

**Comment by sivaschenko** [comment]
Related issues are fixed:
https://github.com/magento/adobe-stock-integration/issues/575
https://github.com/magento/adobe-stock-integration/issues/576
