### ISSUE TITLE
[Story #23] User saves licensed image into Magento Media Gallery 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#310]
## Story
As a Merchant of Magento Community edition I want to programmatically upload images licensed on my AdobeID account, but don't exist in Magento Media Gallery *so that* I can use them on my webstore and marketing email campaigns 

## Business Value
ability to programmatically upload an image that licensed before, but hasn't been saved into Media Gallery 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User is logged into Adobe Stock
* Stock image search result includes images that have been already licensed
* Image is not saved in Media Gallery 

## Acceptance Criteria
* User opens image details 
* User sees the option to upload to Magento Media Gallery available. There is no Save/View preview image options available. 
* User activates uploading image into Media Gallery
* User sees image uploaded into the current folder of the Media Gallery. 
* Image is selected and ready to use

**Comment by filmaj** [comment]
How is this story different from Story 20, User licenses an image (#307)? 

EDIT: this scenario can occur if user licenses an image via other channels, e.g. Adobe Stock web UI.

**Comment by filmaj** [comment]
Label for the button should be "Save"

**Comment by tkacheva** [comment]
@sivaschenko media gallery gets slower and slower as more stock images saved. Can you investigate?

**Comment by tkacheva** [comment]
@sivaschenko I guess story is not ready as when I find the licensed image in the stock grid that doesn't exist in Magento (anymore) the button is still "Locate" and when I press it, I'm navigated to the media gallery with no image selected

**Comment by sivaschenko** [comment]
Remaining to fix the performance issue: https://github.com/magento/adobe-stock-integration/issues/659

**Comment by sivaschenko** [comment]
Related issue is fixed
