### ISSUE TITLE
[Story #24] User locates licensed and uploaded image inside Media Gallery

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#312]
## Story
As a Merchant of Magento Community edition I want to locate a stock image that was already uploaded to the Media Gallery there * son that* I don't upload existing image multiple times

## Business Value
avoid content duplication  

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User is logged into Adobe Stock
* Stock image search result includes images that have been already licensed and uploaded into Media Gallery 

## Acceptance Criteria
* User opens image details 
* User sees the option to view image in the Media Gallery 
* User activates viewing image into Media Gallery
* User sees the image inside Media Gallery in the folder where the image was stored. If image file was not found because it moved/deleted, user sees a message about that. Status of the image is updated to  not saved
* Image is selected and ready to use

**Comment by filmaj** [comment]
Need to confirm button label, currently as "Locate" but  may need to change this.

**Comment by sivaschenko** [comment]
"Locate" button should be renamed to "Open in Media Gallery" - issue TBD

**Comment by sivaschenko** [comment]
Button is renamed
![image](https://user-images.githubusercontent.com/2028541/69547041-c6996080-0f8c-11ea-8b3f-f2b32d210317.png)
