### ISSUE TITLE
[Story #26] User sets the image name

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#328]
## Story
As a Merchant I want to set the image file name *so that* I can better optimize it for SEO purposes

## Business Value
update image file via UI 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin Users saves preview image or license it 

## Acceptance Criteria
* User sees the option to set a file url name for the image they are saving 
* User sees suggested url that is generated out of file title. Encoding is used when necessary to make URL safe. Length is limited to 128 
* User can update  the URL. If user updates the URL, URL Safe characters supported.
* User saves the changes
* User sees image saved with the URL confirmed. If the URL provided already exists, error message displayed

**Comment by sivaschenko** [comment]
Still requires restyling and adding to licensing flow

**Comment by tkacheva** [comment]
@sivaschenko I keep seeing the issue that image with special characters in the name are not correctly rendered in Magento 
<img width="986" alt="Screen Shot 2019-11-01 at 11 59 32 AM" src="https://user-images.githubusercontent.com/5603216/68041758-40487200-fc9f-11e9-97cd-2f1929d4650c.png">

**Comment by sivaschenko** [comment]
Restrict copy-paste for special characters and add validation on "Confirm". @belbiy please provide a message

**Comment by sivaschenko** [comment]
Saving image with special characters is prevented:

![image](https://user-images.githubusercontent.com/2028541/69998892-4ad08280-154f-11ea-9626-123361cad2e7.png)
