### ISSUE TITLE
[Story #27] User locates preview image in the Media Gallery

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#329]
## Story
As a Merchant of Magento Community edition I want to locate a stock image preview that was already uploaded to the Media Gallery there *so that* I don't upload existing image preview multiple times

## Business Value
avoid content duplication  

## Preconditions 
* Admin User is logged into Admin Panel
* Stock image search result includes image previews that have been already uploaded into Media Gallery 

## Acceptance Criteria
* User opens image details 
* User sees the option to view image preview in the Media Gallery 
* User doesn't see the option to save preview to the Media Gallery
* User activates viewing image into Media Gallery
* User sees the image preview inside Media Gallery in the folder where the image was stored. If the file was not found because it moved/deleted, user sees a message about that. Status of the image preview is updated to not saved
* Image is selected and ready to use

**Comment by filmaj** [comment]
Let's check with Eugene on the button labels.

**Comment by sivaschenko** [comment]
"Locate" button should be renamed to "Open in Media Gallery" - issue TBD

**Comment by sivaschenko** [comment]
Button is renamed
![image](https://user-images.githubusercontent.com/2028541/69547062-d3b64f80-0f8c-11ea-92a5-b146d0afc1e7.png)
