### ISSUE TITLE
[Stories #28] User sees the curated images when open Stock

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#344]
## Story
As a Merchant I want to see the meaningful image query when I open stock images *so that* I start image discovery with images that are relevant to me

## Business Value
curated image query instead of random images 

## Preconditions 
* Admin User is logged into Admin Panel

## Acceptance Criteria
* User opens Stock and sees images that matches curated feed specific for Magento customers that is provided by Stock team

**Comment by filmaj** [comment]
Blocked until further info from Adobe Stock team. Will remove test case.

**Comment by sivaschenko** [comment]
Images from the curated gallery are displayed when a search query is not specified
