### ISSUE TITLE
[Story #30] User sees images with the same model as the currently viewed one

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#345]
## Story
As a Merchant I want to see images that with the same model as currently viewed image  *so that* I have better image discovery experience and find the image I need faster 

## Business Value
enhanced image discovery 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User views stock image details  

## Acceptance Criteria
* User sees unto 4 images that are with the same model as currently viewed one
* User selects any of these images and sees its details 
* User activates viewing next\previous image details and sees image details updated to next/previous image in the series.

**Comment by sivaschenko** [comment]
Related issue is fixed https://github.com/magento/adobe-stock-integration/issues/765
