### ISSUE TITLE
[Story #12] User filters safe content images

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#35]
## Story
As a Merchant I want to filter stock images to exclude adult content from search result and narrow search result to images that better fit my needs

## Business Value
Better stock image search relevance 
 
## Preconditions 
* Admin User is logged into Admin Panel
* Admin User sees stock images

## Acceptance Criteria
* User opens image grid filtering 
* User sees filter Safe Search
* User sees adult content is not included in search result by default 
* User updates the filter to include adult content and applies it
* User sees updated search results with images that match filtering
* User sees image grid filter collapses and selected filter displays 
* If filter returns zero results, user sees the message

**Comment by chfabbro** [comment]
Safe search is enabled by default--there is no need to set it by the API unless you want to _disable_ safe search, and display adult content.

Therefore, unless the intent is to show unsafe images as an option (and I am not sure why a business would want this unless they sell adult products), I am not sure this story is needed.
