### ISSUE TITLE
[Story #37] Adobe IMS Login is available for 3-d party devs 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#390]
## Story

As a Developer, I want to include Adobe IMS Login module as a dependency for my own modules *so that* it can be installed via composer separately from Stock integration and utilized in my custom Magento module 

## Business Value
unified Adobe IMS Login implementation for any Adobe-Magento integration dependent on AdobeIMS login

## Acceptance Criteria

* Adobe IMS Login functionality is separated from Stock modules into a separate module
* Adobe IMS Login module available on repo.magento.com
* Developer reads documentation about AdobeIMS module and understands its functionality and how to include it as a dependency for their own custom Magento modules

**Comment by sivaschenko** [comment]
Adobe IMS can be installed separately for adobe stock integration by `composer require module-adobe-ims`
