### ISSUE TITLE
"More from this model" image preview section

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#397]
### Story

https://github.com/magento/adobe-stock-integration/issues/324 [Story 30] User sees images with the same model as the currently viewed one

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image

### Expected result
Image preview is expanded, "More from this model" section with the same series images is displayed (possible to switch tabs between "More from this series" and "More from this model")

![image](https://user-images.githubusercontent.com/2028541/63356243-5b256e80-c35f-11e9-8ebc-29d1686e7da6.png)

### Technical Details

 - Update configuratioin of  `\Magento\AdobeStockClient\Model\SearchParametersProvider\SimpleFilters` to introduce the `search_parameters[model_id]` request parameter
 - I think `\Magento\AdobeStockImageAdminUi\Controller\Adminhtml\Preview\Series` controller can be reused to load same model images as well (do reduce number of requests to server)

**Comment by konarshankar07** [comment]
@sivaschenko ,
Sorry, I mistakenly assign to me can you please put back in ready for development.
Thanks

**Comment by konarshankar07** [comment]
Please ignore the above comment. I'll start working on this ticket
Thanks
