### ISSUE TITLE
Switch the image preview to a selected image in "More from this series" section

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#399]
### Story

https://github.com/magento/adobe-stock-integration/issues/324 [Story 29] User sees images from the same series as the currently viewed image

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image
5. In the expanded preview - click on any image in the "More from this series" section

### Expected result
Image preview is updated to display preview and information of the clicked asset.

![image](https://user-images.githubusercontent.com/2028541/63356243-5b256e80-c35f-11e9-8ebc-29d1686e7da6.png)

**Comment by konarshankar07** [comment]
Hello @sivaschenko  and @serhiyzhovnir 
I have already created PR for this functionality.
https://github.com/magento/adobe-stock-integration/pull/408

Thanks
