### ISSUE TITLE
[Refactoring] Extract StockFileToDocument convertor from Client

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#402]
`\Magento\AdobeStockClient\Model\Client` has too many dependencies and is currently responsible not only for communication with Adobe Stock SDK but also for response format conversion. 

The conversion responsibility currently implemented in `\Magento\AdobeStockClient\Model\Client::convertStockFileToDocument` should be moved to new `\Magento\AdobeStockClient\Model\StockFileToDocument` class, `convert` method.

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Can you please close this task?
Thanks
