### ISSUE TITLE
[Story #18] User sees stock image attributes localized

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#41]
## Story
As a Merchant I want search for stock images using the same language I have selected for Magento Admin Panel and see search results localized

## Business Value
non-english speakers can use stock image search, unified language across Magento Admin
 
## Preconditions 
* Magento Admin Panel is localized language other than English
* Admin User is logged into Admin Panel
* Admin User sees stock images

## Acceptance Criteria
* User views stock image details and sees attributes values in the same language that selected in Magento Admin Panel *if* these localized values exist in Stock 
* User searches for stock images using keywords in the same language selected in Magento Admin panel and sees search returning results
* User saves image preview and localized image attribute values ( *if* they exist in Stock, are saved to the DB)
* User sees messages that come from Stock API localized (success, error, info messages)

**Comment by chfabbro** [comment]
The Stock API supports localization via the `locale=` parameter. A reference of all locales is available here: https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/api/14-locale-codes.md

Note that only _some_ fields are localized. The title of the image is not localized because that is not a straightforward translation; it is left in the contributor's original language.

Keywords and categories are localized, as are URLs.

**Comment by sivaschenko** [comment]
Keywords and category fields are localized

Check if license confirmation message from adobe stock API is localized. If the license confirmation message is not localized on Adobe Stock side the story can be closed

![image](https://user-images.githubusercontent.com/2028541/69441816-47fdb280-0d43-11ea-97f8-91a0f627264e.png)

**Comment by chfabbro** [comment]
@sivaschenko Is that a question? Yes, the license message is localized.

https://stock.adobe.io/Rest/Libraries/1/Member/Profile?content_id=172563501&license=Extended&locale=de_DE
```
    "purchase_options": {
        "state": "possible",
        "requires_checkout": false,
        "message": "Kostet 1 Ihrer 295 Credits."
    }
```

**Comment by sivaschenko** [comment]
Thanks @chfabbro !

Confirmation messages retrieved from Adobe Stock API are localized:
![image](https://user-images.githubusercontent.com/2028541/69562087-63b4c300-0fa6-11ea-9c34-4188c63984b2.png)
