### ISSUE TITLE
[MFTF] User searches images by clicking on keywords in image preview.

### ISSUE THREAD

**Issue by engcom-Golf** [magento/adobe-stock-integration#415]
**Description**

User searches images by clicking on keywords in image preview. 

https://app.hiptest.com/projects/131313/test-plan/folders/943908/scenarios/3516052

**Steps to be automated**

1. Before - Save Adobe Stock API credentials in Magento Admin 
2. Before - LoginAsAdmin 
3. Action - User searches for `Scandinavian Interior` using keyboard input and mouse navigation and sees that grid was updated by new images 
4. Action - User selects any image in search results to view details 
5. Assert that User sees following image attributes keywords 
6. User click on first image keyword 
7. Assert that User sees updated grid result 
8. Assert that User sees selected keyword in the search filter 
9. Action - User selects any image in search results to view details 
10. Action - User click on view all button and click on the last keyword 
11. Assert that User sees updated grid result 
12. Assert that User sees selected keyword in the search filter 
13. After - logout 
14. After - Remove Adobe Stock API credentials in Magento Admin

**Comment by filmaj** [comment]
Hi @sivaschenko @tkacheva I cannot seem to find the related story for this automation task. I think it may be related to #349 (Story 34) or #348 (Story 33) as both are related to searching and viewing tags - but this specific feature is not covered by a story, I don't think. Could you confirm?

**Comment by sivaschenko** [comment]
Hi @filmaj this is automation for https://github.com/magento/adobe-stock-integration/issues/348 but https://github.com/magento/adobe-stock-integration/issues/349 is also covered by this test.
