### ISSUE TITLE
[Story #19] User controls access to Adobe Stock images from Admin Panel in ACL

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#42]
## Story
As a Merchant I want to control level of access that Admin users have to stock images  

## Business Value
control the level of spending on stock images
 
## Preconditions 
* Admin User is logged into Admin Panel
* Admin user created new role in Magento Admin

## Acceptance Criteria
* User opens Resources tree and sees Adobe Stock Config node under Settings - Configuration - System Section. 
* User includes this resource into the role. That will allow admin user with this role to set up an integration with Adobe stock
* User sees Adobe Stock node under Content - Elements - Media Gallery. This node has 2 child nodes:
  * Save preview images
  * License images
* User includes Save preview images resource into the role. This will allow admin user with the role assigned only search for stock images and same their previews into Media Gallery. License image is not accessible. 
* If user doesn't select any of the 2 options, user with the role won't see the access to Adobe Stock from Media Gallery
* If user selects the parent node Adobe Stock, both child nodes get selected.

**Comment by vpodorozh** [comment]
Closing this issue - PR was merged.
