### ISSUE TITLE
[Refactoring] Extract Logout service model from Logout controller

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#427]
Logout implementatioin should be extracted `\Magento\AdobeIms\Controller\Adminhtml\User\Logout::execute` to a separate Logout model in `\Magento\AdobeIms\Model` namespace.

The API interface for that model should be declared in the `AdobeImsApi` module.

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Please close this issue.
Thanks
