### ISSUE TITLE
[MFTF]: User licenses an image

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#440]
# Description
Implement MFTF test to cover scenario: "User licenses an image" (story 20, #307)

#  Preconditions

1. Admin User is logged into Admin Panel
2. Admin User is signed into Adobe IMS

# Test steps

3. Open Adobe Stock Images Grid 
4. User expands image preview of first image
5. Click License and Save button 
6. in the confirmation dialog Click OK button 
7. Open Media Gallery 
8. Verify that licensed image is listed in Media Gallery

**Comment by drpayyne** [comment]
Waiting on @sivaschenko to get back on how to obtain a new image every time. 

Also, two scenarios are considered here. One for preview saved already, and one for brand new image.

**Comment by filmaj** [comment]
I would edit the automation steps and assertions a little, given we shouldn't license new images every time we run the tests:

- find the first unlicensed and unsaved image in a search query's results
- verify the button on the image preview says 'license and save'

Thoughts?

**Comment by drpayyne** [comment]
@filmaj, yes that’d work for just testing the button label functionality. Will work on it.

**Comment by filmaj** [comment]
Great, thank you
