### ISSUE TITLE
[MFTF] User searches for images with the same model as the currently viewed one

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#451]
# Description
Implement MFTF test to cover scenario: "User searches for images with the same model as the currently viewed one" (story 32, #347)

#  Preconditions

1. Admin User is logged into Admin Panel
2. User signs into Adobe IMS

# Test steps

3. Open Adobe Stock Images Grid 
4. Expand preview of first image with a  model
5. Click "See More from this Model"
6. Verify that Images Grid is updated with a model filter

**Comment by sivaschenko** [comment]
Hi @semajeg do you have any updates on this issue?

**Comment by semajeg** [comment]
Sorry, been a busy week! Just pushed a PR for this now :)
