### ISSUE TITLE
[MFTF] User searches for an image by its tag

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#452]
# Description
Implement MFTF test to cover scenario: "User searches for an image by its tag" (story 33, #348)

#  Preconditions

1. Admin User is logged into Admin Panel
2. User signs into Adobe IMS

# Test steps

3. Open Adobe Stock Images Grid 
4. Expand preview of first image
5. Click on any Keyword under the  'Similar Keywords' heading
6. Verify that Images Grid is updated with a keyword filter

**Comment by sivaschenko** [comment]
Already delivered in https://github.com/magento/adobe-stock-integration/pull/416
