### ISSUE TITLE
[MFTF] User license the preview image in Media Gallery

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#457]
# Description
Implement MFTF test to cover scenario: "User license the preview image in Media Gallery" (story 39, #429)

#  Preconditions

1. Admin User is logged into Admin Panel
2. Adobe Stock Preview image exists in Media Gallery
3. User is signed into Adobe IMS

# Test steps

2. Open Media Gallery
3. User clicks first preview image
4. User clicks License
5. Verify that image in Media Gallery is no longer a Preview Image and is now a Licensed Image

**Comment by sivaschenko** [comment]
Blocked by https://github.com/magento/adobe-stock-integration/issues/1170

**Comment by sivaschenko** [comment]
This test case cannot be covered by MFTF test as there is no adobe stock sandbox, the only testing account is available and licensing the preview image will result into the test account state change that has a potential risk for further tests execution
