### ISSUE TITLE
[Story #42] User deletes images in bulk

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#461]
## Story
As a Merchant I want to delete selected images from Magento Media Gallery *so that* I can manage images with less clicks than it was before 

## Business Value
User deletes images with less clicks 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User views images in Media Gallery 

## Acceptance Criteria
* User selects images to delete. Selected state is retained when using pagination 
* User can filter the images and select all to delete
* If any of the selected images are used on the storefront, user sees the warning message. Message says how many of selected images are used on storefront and gives an option to view them. User can move on and delete the images anyway.
* User  deletes the images and  sees the images disappear from the gallery. The images information is deleted from the data base. Image file and all the renditions are deleted from the media server. If images were used on the storefront, there are no broken image links.
* User sees the option to add the image into the content to be not active when several images selected.

**Comment by sivaschenko** [comment]
Task:
 - Endpoint to accept asset ids instead of single id for deletion + Integration test
 - Frontend implementation (checkboxes + additional selected attribute to the image component - update Delete Selected button functionality) + MFTF test
