### ISSUE TITLE
"See more" link applies Model filter to the grid

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#462]
### Story

https://github.com/magento/adobe-stock-integration/issues/347 [Story #32] User searches for images with the same model as the currently viewed one

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image
5. Click on "More from this model" tab in the expanded image preview

### Expected result
"More from this model" section with the same model images is displayed.
**See More** link is at the end of "More from this model" pictures. Click on the link drops all applied filters and applies model_id filter to the grid

![image](https://user-images.githubusercontent.com/2028541/63356243-5b256e80-c35f-11e9-8ebc-29d1686e7da6.png)

### Technical Details

That is very similar functionality to "See More" link introduced for image series in this pull request: https://github.com/magento/adobe-stock-integration/issues/398

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Please move this issue to Done column in backlog
Thanks
