### ISSUE TITLE
[Styles] "See more" link for Series and Model related images styles

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#463]
### Story

https://github.com/magento/adobe-stock-integration/issues/347 [Story #32] User searches for images with the same model as the currently viewed one

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image

### Expected result
Image preview is expanded
"More from this series" section with the same model images is displayed.
**See More** link is at the end of "More from this series" pictures. (the same on "More from this model" tab)

The link design should correspond the design on the mockup below

![image](https://user-images.githubusercontent.com/2028541/63356243-5b256e80-c35f-11e9-8ebc-29d1686e7da6.png)

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Please move this issue to Done column in backlog
Thanks
