### ISSUE TITLE
[Styles] "See more" related images link is shifted out of image preview area on tablet

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#486]
### Story

https://github.com/magento/adobe-stock-integration/issues/328 [Story #26] User sets the image name

### Preconditions
1. Use tablet or adjust the browser to iPad resolution (768X1024)
2. Install Magento with Adobe Stock Integration
3. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image to expand image preview

### Expected result
"See more" link is pushed down outside of image preview area

![image](https://user-images.githubusercontent.com/2028541/65724962-3e94f880-e0ba-11e9-8718-db5e5d883049.png)

### Expected result
"See more" link should be in row with related images shown in tabs

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I have fixed this issue in https://github.com/magento/adobe-stock-integration/pull/481
Please test and let me know if you still reproduce this issue
Thanks
