### ISSUE TITLE
[Unit tests] Cover \Magento\AdobeIms\Model\UserAuthorized with unit test

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#487]
Cover `\Magento\AdobeIms\Model\UserAuthorized` with unit test

**Comment by sivaschenko** [comment]
Hi @karyna-tsymbal-atwix  , do you work on this issue? are there any updates?

**Comment by Nazar65** [comment]
Hi @karyna-tsymbal-atwix can i get this issue ?

**Comment by Nazar65** [comment]
@karyna-tsymbal-atwix thank you
