### ISSUE TITLE
[Bug] Serie Id and Model Id filters do not indicate applied values after relogin to admin panel

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#514]
### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> Advanced -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image to expand image preview
5. Click on "See more" link in the related images section
6. Logout from admin panel
7. Login back to admin panel from another/incognito browser
8. Reopen the Adobe Stock grid

### Actual result
Step 5: Related images filter (Serie Id/Model Id) filter is applied to the grid
Step 8: The filter is applied but the applied value is not indicated in the applied filters section (see screen shot below)

### Expected result
The filter applied value should be indicated in the applied filters section

![image](https://user-images.githubusercontent.com/2028541/66319622-5a4b9a80-e915-11e9-92c8-cb009f637ff1.png)

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I am not able to reproduce this issue as per the steps you have added in this ticket. Can you please confirm?
Thanks
