### ISSUE TITLE
Adjust the code to Magento general static tests

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#540]
Magento static tests results:

 * Backend controller Magento\AdobeIms\Controller\Adminhtml\OAuth\Callback have to overwrite _isAllowed method or ADMIN_RESOURCE constant
 * Backend controller Magento\AdobeStockImageAdminUi\Controller\Adminhtml\Preview\RelatedImages have to overwrite _isAllowed method or ADMIN_RESOURCE constant
 * Magento\AdobeIms\Block\Adminhtml\SignIn block should be marked with API annotation
 * Code duplication in Magento/AdobeStockAsset/Model/ResourceModel/Category/Command/Save.php and Magento/AdobeStockAsset/Model/ResourceModel/Creator/Command/Save.php should be removed
* Namespace should be corrected for Magento/AdobeStockAsset/Test/Unit/Model/GetAssetByIdTest.php (AdobeStockImage -> AdobeStockAsset)
* Namespace should be corrected for app/code/Magento/AdobeStockAsset/Test/Unit/Model/SaveAssetTest.php (AdobeStockImage -> AdobeStockAsset)

inconsistency the number of arguments and placeholders were discovered:

 * Phrase: 'An error occurred during logout operation: %1' /var/www/html/app/code/Magento/AdobeIms/Model/LogOut.php:102
 * Phrase: 'Redirect URI: %uri <br><br>Pattern: %pattern' /var/www/html/app/code/Magento/AdobeStockAdminUi/Model/System/Config/Comment.php:52
* Phrase: 'Get related images list failed: %s' /var/www/html/app/code/Magento/AdobeStockImage/Model/GetRelatedImages.php :90
 * Phrase: 'An error occurred during related images serialization: %s' /var/www/html/app/code/Magento/AdobeStockImage/Model/GetRelatedImages.php:126

Dependency:
* Module Magento\AdobeIms has undeclared dependencies: soft [Magento\AdobeStockImageAdminUi] (dependency has to be removed)
* Module Magento\AdobeIms has undeclared dependencies: soft [Magento\AdobeStockImageAdminUi] (dependency has to be removed)
 * Module Magento\AdobeStockAsset has undeclared dependencies: hard [Magento\Payment] (dependency has to be removed)
 * Module Magento\AdobeStockAsset has undeclared dependencies: hard [Magento\AdobeStockClientApi] (dependency has to be declared)

**Comment by mattheo-geoffray** [comment]
@magento I am working on it

**Comment by mattheo-geoffray** [comment]
Linked PR: https://github.com/magento/adobe-stock-integration/pull/567
This fix:
- ~Backend controller Magento\AdobeStockImageAdminUi\Controller\Adminhtml\Preview\RelatedImages have to overwrite _isAllowed method or ADMIN_RESOURCE constant~
- ~Magento\AdobeIms\Block\Adminhtml\SignIn block should be marked with API annotation~
- ~Phrase: 'An error occurred during logout operation: %1' /var/www/html/app/code/Magento/AdobeIms/Model/LogOut.php:102~
- ~Module Magento\AdobeStockAsset has undeclared dependencies: hard [Magento\Payment] (dependency has to be removed)~
- ~Module Magento\AdobeStockAsset has undeclared dependencies: hard [Magento\AdobeStockClientApi] (dependency has to be declared)~
