### ISSUE TITLE
Fix eslint javascript static tests

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#541]
Run and fix eslint javascript static tests:

`./node_modules/.bin/eslint -c dev/tests/static/testsuite/Magento/Test/Js/_files/eslint/.eslintrc ext/magento/adobe-stock-integration/`

Results:

    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeIms/view/adminhtml/web/js/action/authorization.js
      78:21  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      88:1   error  Line 88 exceeds the maximum line length of 120                   max-len
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeIms/view/adminhtml/web/js/signIn.js
       17:1   error  Line 17 exceeds the maximum line length of 120  max-len
      127:19  error  The function binding is unnecessary             no-extra-bind
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockAdminUi/view/adminhtml/web/js/connection.js
      23:9   error  Expected line before comment  lines-around-comment
      33:55  error  Missing semicolon             semi
      41:9   error  Expected line before comment  lines-around-comment
      55:70  error  Missing semicolon             semi
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
       20:1   error  Line 20 exceeds the maximum line length of 120   max-len
       93:1   error  Line 93 exceeds the maximum line length of 120   max-len
      106:21  error  Expected blank line after variable declarations  newline-after-var
      127:13  error  Expected blank line after variable declarations  newline-after-var
      138:13  error  Expected blank line after variable declarations  newline-after-var
      167:13  error  Expected blank line after variable declarations  newline-after-var
      180:25  error  Expected blank line after variable declarations  newline-after-var
      186:1   error  Line 186 exceeds the maximum line length of 120  max-len
      190:1   error  Line 190 exceeds the maximum line length of 120  max-len
      258:26  error  Gratuitous parentheses around expression         no-extra-parens
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/keywords.js
      16:1  error  Line 16 exceeds the maximum line length of 120  max-len
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
       18:1   error  Line 18 exceeds the maximum line length of 120                   max-len
       89:83  error  Missing semicolon                                                semi
       99:83  error  Missing semicolon                                                semi
      147:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      172:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      192:67  error  'record' is defined but never used                               no-unused-vars
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
      15:1   error  Line 15 exceeds the maximum line length of 120  max-len
      56:30  error  Missing semicolon                               semi
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
      21:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      22:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      23:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      24:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      30:22  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      31:21  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      34:21  error  Blocks are nested too deeply (3)                                 max-depth
      39:21  error  Expected blank line after variable declarations                  newline-after-var
      39:21  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      40:21  error  Blocks are nested too deeply (3)                                 max-depth
      47:13  error  Expected blank line after variable declarations                  newline-after-var
      47:13  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      51:17  error  Expected blank line after variable declarations                  newline-after-var
      51:17  error  All 'var' declarations must be at the top of the function scope  vars-on-top
      58:6   error  Missing semicolon                                                semi
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/model/messages.js
      48:17  error  'timerId' is assigned a value but never used. Allowed unused vars must match /config/  no-unused-vars
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
      40:52  error  Missing semicolon  semi
    
    /Users/sivashch/Projects/magento2/.modman/adobe-stock-integration/AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
      61:13  error  Expected blank line after variable declarations  newline-after-var
      72:13  error  Expected blank line after variable declarations  newline-after-var

**Comment by filmaj** [comment]
I'd like to tackle this issue!

The only thing is I can't find the eslint config to use for this project / Magento projects. Could you point me in the right direction?

**Comment by filmaj** [comment]
Perhaps the same one for the magento2 project? https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-javascript.html

**Comment by Nazar65** [comment]
@filmaj 
`npm install eslint --save-dev`
`./node_modules/.bin/eslint --init`
`./node_modules/.bin/eslint -c dev/tests/static/testsuite/Magento/Test/Js/_files/eslint/.eslintrc  ext`
