### ISSUE TITLE
Run eslint as part of CI

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#548]
**Describe the solution you'd like**
Since we use travis, it would be good to run eslint as part of the travis test run. Perhaps as part of the `static` set of travis tests? Not sure, would like for others to let me know their opinion.

**Additional context**
I am happy to take this issue on once a solution is agreed upon.
Related to #547

**Comment by sivaschenko** [comment]
@filmaj eslint is now running as part of PR tests ("Static tests" job). Closing this issue as done.
