### ISSUE TITLE
Allow to save/download already licensed images to media gallery

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#555]
### Story:

https://github.com/magento/adobe-stock-integration/issues/310: [Story 23] User saves previously licensed image into Magento Media Gallery

### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Login to Adobe Stock (use Sign In link in top right corner)
5. Find an image that is licensed for the Adobe Stock account but not licensed on actual Magento instance
6. Click on the image to expand the preview

### Expected result (*)
Only "Save" button is available for such image
Clicking "Save" button will bring up a popup to specify the image name (if the image preview was not saved before)
After confirming the image name a full licensed image is saved to the media gallery

### Additional Info
See https://github.com/magento/adobe-stock-integration/pull/552 PR - it is adding `is_licensed` filed to the search result

**Comment by sivaschenko** [comment]
Hi @serhiyzhovnir do you have any updates regarding this issue?

**Comment by drpayyne** [comment]
@sivaschenko the bot is auto assigning me and thinking PR is created for this issue as I referenced it in my PR as a dependency. But obviously, that isn't the case.
