### ISSUE TITLE
Add more Adobe Stock search filters support to Client implementation

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#557]
### Story

https://github.com/magento/adobe-stock-integration/issues/344 [Story 28] User sees the curated images when open Stock

### Task description

This task is a backend implementation and currently does not require any extra frontend UI.

The following filters support should be added:
 - gallery_id
 - category
 - creator_id
 - similar

The documentation on Adobe Stock search API can be found here: https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/api/11-search-reference.md

To add support for a new filter a `\Magento\AdobeStockClient\Model\SearchParameterProviderInterface` implementation should be added or `Magento\AdobeStockClient\Model\SearchParametersProvider\SimpleFilters` configuration should be extended in `app/code/Magento/AdobeStockClient/etc/di.xml`

**Comment by krirob** [comment]
@magento I am working on it
