### ISSUE TITLE
Licensed overlay labels are not updated when licensing and login/logout

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#575]
### Story

https://github.com/magento/adobe-stock-integration/issues/309 [Story 22] User views licensed images in the grid

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> Advanced -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Log in to Adobe Stock (previously licensed images should be marked as "Licensed" in grid)
5. License an image (just licensed image should be marked as licensed in grid)
6. Sign out from Adobe Stock (licensed labels should be removed from grid)

### Actual result
Licensed overlay labels are not updated dynamically

### Expected result
Licensed overlay labels should be dynamically updated when the image is licensed and on login/logout

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Can you please move this task to done column?
Thanks
