### ISSUE TITLE
Remove database records when image is deleted from media gallery

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#582]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image to expand preview section
5. Save Preview version of the image
6. Delete the saved image in the media gallery

### Expected result (*)
`media_gallery_asset` and `adobe_stock_asset` tabels do not contain deleted image information

### Technical Details:

There is a plugin for adobe stock asset `\Magento\AdobeStockImage\Plugin\Product\Gallery\Processor` the plugin should be revisited and corresponding plugin should be created for the media gallery asset (`AdobeMediaGallery` module)

**Comment by jporter10** [comment]
@magento I am working on it

**Comment by sivaschenko** [comment]
Hi @jporter10 are you working on this issue?
