### ISSUE TITLE
Cover DataExtractor with a unit test

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#584]
Cover `\Magento\MediaGallery\Model\DataExtractor` with a unit test

**Comment by sivaschenko** [comment]
Hi @valentinboyanov are you working on this issue? Do you have any updates?

**Comment by sivaschenko** [comment]
Removed assignment as there is no response from the assignee. Ready for development.

**Comment by sivaschenko** [comment]
Hi @larsroettig are you working on this issue?)

**Comment by sivaschenko** [comment]
PR for this issue should target magento2 repository

**Comment by larsroettig** [comment]
Cool thank today I have time to finish them
