### ISSUE TITLE
Cover Media Asset Save command with a unit test

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#586]
Cover `\Magento\AdobeMediaGallery\Model\Asset\Command\Save` with a unit test

**Comment by lagaval** [comment]
I assigned it to me

**Comment by sivaschenko** [comment]
Hi @lagaval are you working on this issue? Do you have any updates?

**Comment by sivaschenko** [comment]
Removed assignment as there is no response from the assignee. Ready for development.
