### ISSUE TITLE
Test Module - Adobe Stock SDK Stub

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#593]
Develop a Test Module - Adobe Stock SDK Stub for running tests without credentials and network connection.

The module should add a preference for "\Magento\AdobeStockClient\Model\ConnectionFactory" and to the factory returning the extended and stubbed `\AdobeStock\Api\Client\AdobeStock` proving mock responses.

The module should be placed inside `dev/test/...` directory of `adobe-stock-integration` repo

Examples of existing test modules in Magento:

- `dev/tests/integration/_files/Magento`
- `dev/tests/api-functional/_files/Magento`

**Comment by coderimus** [comment]
Hello @sivaschenko , just want to update with the current status: this issue is in progress and I have started implementation. Will push the WIP PR tomorrow and will be focused on this issue this week.
