### ISSUE TITLE
Fix static tests for translation function arguments

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#598]
Fix static tests for translation function arguments:

    3 usages of inconsistency the number of arguments and placeholders were discovered:
    Phrase: ‘Redirect URI: %uri <br><br>Pattern: %pattern’
    File: /var/www/html/app/code/Magento/AdobeStockAdminUi/Model/System/Config/Comment.php
    Line: 52
    
    Phrase: ‘Get related images list failed: %s’
    File: /var/www/html/app/code/Magento/AdobeStockImage/Model/GetRelatedImages.php
    Line: 90
    
    Phrase: ‘An error occurred during related images serialization: %s’
    File: /var/www/html/app/code/Magento/AdobeStockImage/Model/GetRelatedImages.php
    Line: 122

**Comment by coderimus** [comment]
@sivaschenko this functionality fixed at the scope of this PR  [Remove database records when image is deleted from media gallery](https://github.com/magento/adobe-stock-integration/pull/597) in [this commit](https://github.com/magento/adobe-stock-integration/pull/597/commits/bbdec98d53ae397be087ea82fdc4de0850f51848)

**Comment by sivaschenko** [comment]
Fixed in https://github.com/magento/adobe-stock-integration/pull/597
