### ISSUE TITLE
Search Adobe Stock button is not active after 2nd attempt to open a media gallery from the same place in Admin

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#622]
### Preconditions (*)
1. Create a page
2. Add a Page Builder content type (like row) to the content
3. Open Row configuration
4. Open Media Gallery to select an image for the background 

### Steps to reproduce (*)
1. click "Search Adobe Stock"
2. Select and save the image
3. Add image to the row background
4. Open media gallery again
5. try to search for stock images

### Expected result (*)
1. Adobe stock search opens
### Actual result (*)
1. Button "Search Stock images" doesn't work

![button_not-working](https://user-images.githubusercontent.com/5603216/68056069-397e2700-fcc0-11e9-8a08-a1369ed78f3f.gif)

**Comment by sivaschenko** [comment]
Fixed
