### ISSUE TITLE
The licensed label is shown under the image if the row of images has small height

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#641]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Wide image is licensed

### Steps to reproduce (*)
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Log in to Adobe Stock using Sign in link
4. Find the wide licensed image

### Actual result

The licensed label is shown under the image if the row of images has small height

![image](https://user-images.githubusercontent.com/2028541/68123731-aa625080-ff05-11e9-959d-a71e18fb1fb1.png)

**Comment by drpayyne** [comment]
Hi @sivaschenko. Where should the label be placed? stock.adobe.com places it on the top left:
![image](https://user-images.githubusercontent.com/22623301/68145156-2aff6c00-ff5b-11e9-92ca-5578e4334552.png)

**Comment by sivaschenko** [comment]
@drpayyne the label should be placed according to the mockup:
![image](https://user-images.githubusercontent.com/2028541/68236906-f7295280-fffd-11e9-92b2-f9d7e05d3732.png)

**Comment by drpayyne** [comment]
@sivaschenko Thanks, will do it.

**Comment by sivaschenko** [comment]
@drpayyne the PR was reverted. The solution causes a bug that makes license labels for the row to disappear when the image preview is opened.

**Comment by drpayyne** [comment]
Hi @sivaschenko. Sorry about that. It's my fault that I overlooked that scenario. Have fixed it now in PRs: https://github.com/magento/adobe-stock-integration/pull/670 and https://github.com/magento/magento2/pull/25525
