### ISSUE TITLE
Error when switching to the next listing page with preview opened

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#642]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on an image to expand the preview
5. Switch listing page (Next, previous or manual entry)

### Actual result

Image preview is not closed, page loader is not removed after changing the page.
JS error: `Uncaught TypeError: record.series is not a function at UiClass.canShowMoreSeriesImages (related.js:78)`

The root cause looks to be the fact that image preview is not closed before switching pages

### Expected result
Image preview should be closed before switching listing pages

Edit: typo

**Comment by rogyar** [comment]
I can confirm that the same happens when you are trying to change number items per page
