### ISSUE TITLE
Overflowing text in sort dropdown

### ISSUE THREAD

**Issue by drpayyne** [magento/adobe-stock-integration#644]
### Preconditions
1.  Open Adobe Stock panel

### Steps to reproduce
1. View sorting dropdown

### Expected result (*)
Properly rendered text

### Actual result (*)
![image](https://user-images.githubusercontent.com/22623301/68144947-b5939b80-ff5a-11e9-952a-7a3371c1fb35.png)
![image](https://user-images.githubusercontent.com/22623301/68144980-c3492100-ff5a-11e9-8d90-ca9e9b6463e0.png)

###  Expected Result:
![image](https://user-images.githubusercontent.com/2028541/68715378-c4510280-0599-11ea-83d1-a560258f0b27.png)

**Comment by drpayyne** [comment]
I'm working on this, thanks.

**Comment by sivaschenko** [comment]
@drpayyne Expected Result:
![image](https://user-images.githubusercontent.com/2028541/68715378-c4510280-0599-11ea-83d1-a560258f0b27.png)

**Comment by drpayyne** [comment]
Closing this, as the PR revert in magento2 repository is merged to fix this issue. Thanks!
