### ISSUE TITLE
Possible MFTF test fail scenario discussion

### ISSUE THREAD

**Issue by drpayyne** [magento/adobe-stock-integration#660]
### Preconditions

-  Adobe Stock account doesn't have a phone number linked.

### Steps to reproduce
When the sign in test is run, if the precondition is true, the sign in popup might ask to link the phone number (optional and can be skipped by clicking _Not now_), but if the popup asks to link the phone number, pretty much any MFTF tests which involves the user signing in will fail at this step. Noticed this while manually testing, and the Adobe sign in popup asked for me to link my phone number optionally right after clicking authenticating my credentials, in the same popup window. Not sure how frequent it will ask, or if it can be disabled, but can confirm that this edge case is possible.

**Comment by filmaj** [comment]
We may be able to deal with it in the test(s) by detecting if the 'update your number' screen shows up, and if it is present, dismiss it by clicking "Not Now"?

**Comment by drpayyne** [comment]
@filmaj We can write conditionals in mftf...?

**Comment by filmaj** [comment]
At least it should be possible to click conditionally: https://devdocs.magento.com/mftf/docs/test/actions.html#conditionalclick

**Comment by drpayyne** [comment]
Thank you, @filmaj. Didn't know about that. Will create a fix for that.

**Comment by filmaj** [comment]
This will be hard to test... so I wouldn't put too much time into it. We should keep in the back of our minds that if we see the 'add your phone' screen, to take a snapshot of the DOM so that we can find the right selector to use in the conditional click on the 'skip this step' link.

**Comment by drpayyne** [comment]
True, @filmaj. I've created a work-in-progress PR ready with the test, but just the selector remaining. If anyone or even myself comes across that screen, I can update the PR. Thanks!
