### ISSUE TITLE
Remove original Image from the related images (More from model and More from series)

### ISSUE THREAD

**Issue by konarshankar07** [magento/adobe-stock-integration#675]
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
Click "Search Adobe Stock" button to open images grid
3. Click on any image to open the image preview

### Expected result (*)

The image shown in the image preview should not be visible in the `More from series` and `More from Model` Tab

### Actual result (*)

The image shown in the image preview is visible in the `More from series` and `More from Model` Tab

**Comment by sivaschenko** [comment]
Removing the original image prevents navigation back to the original image when selecting a related image and navigating through related images in the image preview

After the discussion with PO we decided that it would be better to keep the original image between related images to avoid the problem described above.
