### ISSUE TITLE
Image file name is not visible if the title is in other than English language

### ISSUE THREAD

**Issue by konarshankar07** [magento/adobe-stock-integration#678]
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Enter text `246811446` in search by keywords
5. Click on the image to open the image preview
6. Click on Save Preview button

### Expected result (*)

File id is used as the suggested filename

### Actual result (*)

![image](https://user-images.githubusercontent.com/39480008/68548195-22ea7500-0410-11ea-8f38-91a1ea636091.png)

**Comment by sivaschenko** [comment]
Let's add `File id` suffix to the end of the generated image name and remove `-` if there are no characters in result image name without suffix.

So Expected result:
`File id` is used as the suggested filename

@tkacheva what do you think?
