### ISSUE TITLE
Cannot navigate to next image in preview using keyboard arrows 

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#691]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Click on an image to expand the preview
- Click the left arrow or right arrow keyboard button

### Expected result:
Image attributes were updated according next image

### Actual result
Cannot navigate to next image in preview using keyboard arrows

**Comment by drpayyne** [comment]
Hi @sivaschenko, this is just for pressing left and right arrow keys to navigate between previous and next images, right? What about when pressing left on the first image? Nothing should happen, yeah?

**Comment by sivaschenko** [comment]
@drpayyne correct

**Comment by drpayyne** [comment]
Closing as PR is merged at https://github.com/magento/magento2/pull/25611
