### ISSUE TITLE
Search by keywords is broken

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#694]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Click on an image to expand the preview
- Click on first image keyword

### Expected result:
Grid result is updated
Selected keyword is shown in the search filter

### Actual result
Grid result is updated
Selected keyword is not shown in the search filter
JS error: "TypeError: this.inputValue is not a function"
![image](https://user-images.githubusercontent.com/51681379/68666933-83cb9780-054d-11ea-9779-59bd1c9f2cc8.png)

**Comment by filmaj** [comment]
I can confirm this issue as well.
