### ISSUE TITLE
Enable strict types in all php files

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#704]
`declare(strict_types=1);` should be added at the next line after the header phpdoc
List of files where strict types are not enabled:

../ext/magento/adobe-stock-integration/AdobeStockClient/Model/SearchParametersProvider/Premium.php 
../ext/magento/adobe-stock-integration/AdobeStockAsset/Test/Unit/Model/GetAssetByIdTest.php ../ext/magento/adobe-stock-integration/AdobeStockAsset/Test/Unit/Model/SaveAssetTest.php 
../ext/magento/adobe-stock-integration/AdobeStockImage/Test/Unit/Model/Storage/SaveTest.php ../ext/magento/adobe-stock-integration/AdobeStockImage/Test/Unit/Model/Storage/DeleteTest.php ../ext/magento/adobe-stock-integration/AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php ../ext/magento/adobe-stock-integration/AdobeStockImage/Test/Api/SearchExecuteTest.php ../ext/magento/adobe-stock-integration/AdobeStockClient/registration.php 
../ext/magento/adobe-stock-integration/AdobeStockImageApi/registration.php 
../ext/magento/adobe-stock-integration/AdobeStockAsset/registration.php 
../ext/magento/adobe-stock-integration/AdobeImsApi/registration.php 
../ext/magento/adobe-stock-integration/AdobeStockClientApi/registration.php 
../ext/magento/adobe-stock-integration/AdobeIms/registration.php 
../ext/magento/adobe-stock-integration/AdobeStockImageAdminUi/registration.php ../ext/magento/adobe-stock-integration/AdobeStockImage/registration.php 
../ext/magento/adobe-stock-integration/AdobeStockAdminUi/registration.php 
../ext/magento/adobe-stock-integration/AdobeStockAssetApi/registration.php

**Comment by hws47a** [comment]
#701
