### ISSUE TITLE
Image preview should be closed when the page is changed

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#723]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Click on an first image to expand the preview on first page
- Change grid page.

### Expected result (*)
Image preview should be closed when the page is changed

### Actual result (*)
Image preview is shown on next page.
![#25566PR](https://user-images.githubusercontent.com/51681379/69052928-ea025f80-0a10-11ea-9fa9-801acc908d2f.gif)

**Comment by sivaschenko** [comment]
Fixed in https://github.com/magento/magento2/pull/25719
