### ISSUE TITLE
[Story #44] User edits image meta data in Media Gallery

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#724]
## Story
As a Merchant I want to edit, delete and add new image  meta data *so that* it's up to date and can be used for searching and filtering images

## Business Value
Images can be organized and later filtered and searched by their meta data 

## Preconditions 
* Admin User is logged into Admin Panel
* Admin User views images in Media Gallery 
* Admin User views image details 

## Acceptance Criteria
* User can edit image title. Title is a required field
* User can add new keywords (tags). Keywords are coma separated. Keywords field in optional
* User can delete existing keywords
* User can edit meta data fields that are enabled for editing in the meta data file 
* User downloads image with updated meta data and sees  that changes in the file details 

Question: is there an option to define in image meta data xml what fields are editable by user? Like camera data is unlikely editable, but image description can be. 

Whatever fields supplied with image meta data as editable should be edited in Media Gallery 

![image](https://user-images.githubusercontent.com/2028541/82818781-279be580-9e97-11ea-80fb-d978638f6841.png)

**Comment by sivaschenko** [comment]
- Adjust the implementation of SaveAssetsKeywordsInterface to delete assets that are linked to the asset but not provided in the argument + correct integration test
 - Endpoint for updating asset title and keywords + WebAPI or Integration test
 - Add slide panel to the frontend (click on Edit button on View Details slide panel) + MFTF test
