### ISSUE TITLE
[TBD] ASI exception instead of Integration exception

### ISSUE THREAD

**Issue by coderimus** [magento/adobe-stock-integration#732]
@sivaschenko my idea is to replace the Integration exception with the ASI exceptions. In the tech guideline we have next:
`5.19. Each module or component MUST declare its own exceptions. Exceptions declared in other components SHOULD NOT be thrown.`

I see this implementation like adding a new exception class for each module we have and replace every Integration exception with it.

**Comment by sivaschenko** [comment]
Agreed with @coderimus that no updates in this area are needed for adobe stock integration modules
