### ISSUE TITLE
Tabs separation line is absend for related images in image preview

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#735]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration

### Steps to reproduce (*)
1. Open Adobe Stock Integration Grid
2. Open image preview for any image

### Expected result (*)

Tabs separation line should be present:

![image](https://user-images.githubusercontent.com/2028541/69240260-fcf16d00-0b93-11ea-8327-1d586dab4875.png)

### Actual result (*)

Tabs separation line is missing:

![image](https://user-images.githubusercontent.com/2028541/69239718-c830e600-0b92-11ea-94c6-99a039b7990e.png)

**Comment by drpayyne** [comment]
Hi @sivaschenko, should the tab separation line be present even under the selected tab?

**Comment by sivaschenko** [comment]
@drpayyne nope, according to the mockup attached to the expected result
