### ISSUE TITLE
Do not autovalidate API key if it's empty or not yet set

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#737]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Adobe Stock API key is empty or not set in system configuration

### Steps to reproduce (*)

- Go to Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Expected result (*)
Automatic test connection should not be performed if API key field is empty

### Actual result (*)
Message "Connection Failed!" is shown

![image](https://user-images.githubusercontent.com/51681379/69140613-7d986680-0acb-11ea-9fcd-a7498aaa9074.png)

**Comment by drpayyne** [comment]
Would disabling the button on an empty field value be a good way to proceed on this? Or to show an error message on testing the connection without an API key? The latter would be a quick fix. Former, I'm not really sure.

> Edit: Proceeded with just displaying an error message on empty API key to keep things simple
