### ISSUE TITLE
Long Adobe IMS account names show weirdly in Stock Search Grid

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#738]
### Preconditions (*)

1. Open the Stock search grid.
2. Sign in with an Adobe IMS account (ideally with a long name - if not, you can open web  inspector and manually make your name long).

### Steps to reproduce (*)

1. Long IMS account names show much differently from short ones.

### Expected result (*)

1. Both long and short names show similarly.

### Actual result (*)

Short name looks like this:

<img width="304" alt="Screen Shot 2019-11-20 at 10 03 26 AM" src="https://user-images.githubusercontent.com/52645/69250331-7cc00d00-0b7d-11ea-99ec-8990663ed18e.png">

Long names look like this:

<img width="522" alt="Screen Shot 2019-11-20 at 10 02 32 AM" src="https://user-images.githubusercontent.com/52645/69250357-85b0de80-0b7d-11ea-834f-a083598ad52a.png">

Looks like the name cuts  off the avatar picture a little bit.

**Comment by Iamwade** [comment]
@filmaj Can you clarify a little what needs to be done with the name if its length is too long?
I currently see 2 possible implementations
1) crop the name and add "..." after a certain number of characters.
2) Change the width of the div from 220px to a dynamic width that depends on the content.
![image](https://user-images.githubusercontent.com/33068778/69479796-17348080-0e0a-11ea-931b-95110a90f2cb.png)

**Comment by filmaj** [comment]
Hey @Iamwade, I think the 2nd option is the better one given there is a lot of room horizontally around the IMS account container.

**Comment by konarshankar07** [comment]
Hello @Iamwade ,
Sorry, I didn't knew that you are working on this ticket. Let me know if you still working on this ticket so I'll unassigned myself from the ticket
Thanks

**Comment by Iamwade** [comment]
@konarshankar07 
good day. I first wanted to clarify the requirements in more detail before taking the assignment. You can calmly continue the assignment, all right.
