### ISSUE TITLE
MFTF Locale Test (AdminAdobeStockLocalizationTestCest) errors out, failing Grid suite on Travis

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#754]
### Steps to reproduce (*)

1. Check the failure here: https://travis-ci.org/magento/adobe-stock-integration/jobs/615219681

```
Set Admin "Interface Locale" to ru_RU
[setAdminInterfaceLocaleToDefaultValue] SetAdminAccountActionGroup
  [] Navigate to admin System Account Page
  [openAdminSystemAccountPage] am on page "/backend/admin/system_account/index/"
  [waitForInterfaceLocale] wait for element visible "#interface_locale",10
  [] Change Admin locale to Français (France) / French (France)
  [setInterfaceLocate] select option "#interface_locale","ru_RU"
[saveScreenshot] save screenshot
```

### Expected result (*)

1. Won't fail on trying to set the locale to Russian

### Actual result (*)

1. Fails.

### More Context

I think perhaps the Russian language is missing from the Magento instance we are standing  up in Travis? But I'm not sure how to go about installing it? My local instance seems to have a variety of languages....

**Comment by diazwatson** [comment]
Hey @filmaj rather than installing a full language package I think we could add the phrase(s) we need to the database for the inline translation to pick it up and use it during the test?

**Comment by filmaj** [comment]
@diazwatson that is one way to go about it, but I think we'd still need to set the magento instance to a particular locale so that the translations are wired into the UI, right?

I feel like installing a language pack is the way to go... but finding instructions how to do so is frustrating.

**Comment by diazwatson** [comment]
I think the locale in the admin panel is set per user.
![Screenshot 2019-11-28 at 17 45 41](https://user-images.githubusercontent.com/1080386/69825364-ef2c8f00-1206-11ea-9f37-00ea2d2388e0.png)

And I still think that adding the phrase(s) we need for the test directly into the db will be much easier than installing a Language Package.

Maybe something like this:
```
mysql -h hostname -u username -p db_name -e "INSERT INTO `translation` (`string`, `store_id`, `translate`, `locale`) VALUES ('Cache Management', 0, 'Управление кешем', 'ru_RU');"
```
This is an example of how it looks like in the db.
![Screenshot 2019-11-28 at 17 39 49](https://user-images.githubusercontent.com/1080386/69825157-36fee680-1206-11ea-86f1-26d53f2328ca.png)

![Screenshot 2019-11-28 at 17 51 35](https://user-images.githubusercontent.com/1080386/69825621-d2448b80-1207-11ea-8c94-d2595842774f.png)

What do you think @filmaj ?

**Comment by filmaj** [comment]
OK but the issue is that there exists no option other than English in the user interface locale option dropdown on Travis. For example, on [the most recent Travis build for the develop branch](https://travis-ci.org/magento/adobe-stock-integration/builds/618192887), under [the `grid` suite of MFTF tests](https://travis-ci.org/magento/adobe-stock-integration/jobs/618192898), the failure is:

```
[setAdminInterfaceLocaleToDefaultValue] SetAdminAccountActionGroup
  [] Navigate to admin System Account Page
  [openAdminSystemAccountPage] am on page "/backend/admin/system_account/index/"
  [waitForInterfaceLocale] wait for element visible "#interface_locale",10
  [] Change Admin locale to Français (France) / French (France)
  [setInterfaceLocate] select option "#interface_locale","ru_RU"
[saveScreenshot] save screenshot 
```

If you scroll all the way down in the build logs, and expand the `after_failure` block of logs, at the end you can see the URL for the uploaded screenshot at this moment of failure (https://i.ibb.co/WsCjGFq/Magento-Acceptance-Test-adobe-stock-integration-suite-grid-Backend-Admin-Adobe-Stock-Localization-Test-Cest-Admin-Adobe-Stock-Localization-Test-fail.png):

![Magento-Acceptance-Test-adobe-stock-integration-suite-grid-Backend-Admin-Adobe-Stock-Localization-Test-Cest-Admin-Adobe-Stock-Localization-Test-fail](https://user-images.githubusercontent.com/52645/69825854-ba0c4680-11de-11ea-96f4-f12cecd11002.png)

So my understanding  is, even if we enter the translations manually into the DB, we still need to somehow change the configuration to instruct Magento to use those translations in the UI - presumably via this "Interface Locale" option.

Correct me if I'm not understanding this correctly.

**Comment by filmaj** [comment]
Not entirely sure yet whether #946 will solve the issue just yet.. reopening.
