### ISSUE TITLE
Highlight the selected image in the grid

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#761]
### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> Advanced -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image to expand image preview

### Expected result
The selected image is highlighted in the grid with a blue border:

![image](https://user-images.githubusercontent.com/2028541/69456690-2ad8dc00-0d63-11ea-9e54-4d5581b7a36e.png)

**Comment by sivaschenko** [comment]
Hi @serhiyzhovnir do you have any update regarding this issue?

**Comment by serhiyzhovnir** [comment]
Hi @sivaschenko 
The PR is created: https://github.com/magento/magento2/pull/25864
Thanks.

**Comment by sivaschenko** [comment]
Thank you @serhiyzhovnir !
