### ISSUE TITLE
Licensing configramtion message should be localized

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#767]
### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> Advanced -> System -> Adobe Stock Integration fieldset
3. Have Adobe Stock account with credits - contact @sivaschenko 

### Steps to reproduce
1. Login to admin panel
2. Change Admin user locale to i.e. German
3. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
4. Click "Search Adobe Stock" button to open images grid
5. Click on any image to expand image preview
6. Click "License and save" button
7. Complete login to Adobe Stock process

### Actual result
The confirmation message is shown in english

![image](https://user-images.githubusercontent.com/2028541/69457807-ce2af080-0d65-11ea-82d8-3fdeb5680468.png)

### Expected result
The confirmation message should be displayed in the admin panel language.

### Technical details
The locale should be added to confirmation request and the result message should be without any changes forwarded to the frontend

https://stock.adobe.io/Rest/Libraries/1/Member/Profile?content_id=172563501&license=Extended&locale=de_DE
```
    "purchase_options": {
        "state": "possible",
        "requires_checkout": false,
        "message": "Kostet 1 Ihrer 295 Credits."
    }
```

**Comment by sivaschenko** [comment]
Hi @Iamwade are you continuing to work on this task?

**Comment by Iamwade** [comment]
Hi @sivaschenko 
Yes. I'm going to fix this problem.

**Comment by sivaschenko** [comment]
@lamwade great! I think the `localeResolver` has to be used instead of `config` here: https://github.com/magento/adobe-stock-integration/blob/9c053fb04db00ff9f6e3c2ef9727fe54cc0926e4/AdobeStockClient/Model/Client.php#L173

**Comment by sivaschenko** [comment]
Already fixed
