### ISSUE TITLE
[1.1-develop] Introduce MediaGalleryUiApi module and ConfigInterface

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#774]
MediaGalleryUiApi module should be added to the repository including all the general necessary module files.

- `.modman` and metapackage `composer.json` should be updated
- `\Magento\MediaGalleryUiApi\Model\ConfigInterface` containing a single `isEnabled` method declaration should be added to the module
 -`\Magento\MediaGalleryUi\Model\Config` should implement `\Magento\MediaGalleryUiApi\Model\ConfigInterface` and be a declared preference for this interface in DI

Please open a pull request for this issue to **1.1-develop** branch (not default currently)

This task can be implemented after https://github.com/magento/adobe-stock-integration/pull/773 will be merged

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
As mentioned in the task description
> \Magento\MediaGalleryUiApi\Model\ConfigInterface containing a single isEnabled method declaration should be added to the module

I think we need to create `ConfigInterface` in `\Magento\MediaGalleryUiApi\Api\ConfigInterface` instead of `\Magento\MediaGalleryUiApi\Model\ConfigInterface`. Correct me If I'm wrong

Thanks
