### ISSUE TITLE
Cover overlay.js with jasmine tests

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#798]
Cover `AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js` with jasmine tests

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I have started working on this ticket and found that jasmine test files are created in `Magento_Root/dev/tests/js/jasmine/tests/` folder but how can we run jasmine test in our repo?
My guess is `ext/magento/stock-integration/AdobeStockImageAdminUi/Test/js/view/adminhtml/web/js/components/grid/column/overlay.test.js`
Let me know your thoughts
Thanks

**Comment by sivaschenko** [comment]
Hi @konarshankar07 , sorry for delay, lets place them in ASI_Root/dev/tests/js/jasmine/tests/ for now
