### ISSUE TITLE
[MFTF] Cover the case when Admin User attemps to login with incorrect Secret key in configuration

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#799]
#  Preconditions

1. Admin User is logged into Admin Panel
2. User is signed into Adobe IMS
3. Incorrect secret key is saved in the configuration

# Test steps

1. Open Media Gallery (i.e. from Cms -> Pages -> Add new page)
2. Click "Search Adobe Stock" button
3. Click "Sign In" Link

# Expected Result:
A popup with the appropriate error message is opened

**Comment by sivaschenko** [comment]
Hi @tobiascm are you still going to work on this issue? Any updates?

**Comment by drpayyne** [comment]
Hey @filmaj, currently, before any Adobe Stock MFTF test is run, the test logs in to the Admin panel and sets the _correct_ Adobe Stock configuration values ([code reference](https://github.com/magento/adobe-stock-integration/blob/1.1-develop/AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml#L12)) as part of the Suite's `<before/>` node. But the very purpose of this test is to set an incorrect configuration value and test its output and I don't think re-setting an incorrect value in the test file right after the correct value was set as mentioned above. 
Any tips on how to overcome this? Using a fresh suite just for this seems overkill, but would be the easiest way.

**Comment by sivaschenko** [comment]
Hi @drpayyne thanks for the concern, I agree with you that introducing a separate test suite for that test is an overhead. I believe it's ok to set incorrect credentials in this test even though they were set to correct as a test suite precondition.

**Comment by drpayyne** [comment]
Thanks, @sivaschenko. Also, is there a story linked to this?

**Comment by sivaschenko** [comment]
@drpayyne This is a related story https://github.com/magento/adobe-stock-integration/issues/308
