### ISSUE TITLE
Expand preview image on thumbnail click

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#8]
## Description
- Implement new expandable UI column component for image listing
- Use thumbnail_500 image URL for preview
- Implement switching between images in the preview mode
- Cover changes with MFTF test

## Documentation
Story: [User views the image details](https://github.com/magento/adobe-stock-integration/issues/24)

## QA notes
User has the ability to click on the image in the listing and view large image preview.
User can see image attributes

**Comment by sidolov** [comment]
Hi @passtet ! Thank you for your interest in our project!  Have you tried to resolve the issue? If you need help, just ping me!

**Comment by passtet** [comment]
@sidolov , for now I am working on refactoring current implementation, as it has no ability to add other components and contains transforms, which makes it hard to add item inside. One issue I have for now is that the received data from BE already has a compressed image URL, but no full image URL

**Comment by sidolov** [comment]
@passtet we had a proposal to implement current functionality in the scope of new column, it may help you to do this task without any refactoring. Just ping me in Slack and we will discuss implementation details.
