### ISSUE TITLE
The "Undiscovered" filter is presented in Sort by drop-down list, not as a separate filter 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#807]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
### Steps to reproduce (*)
1. From Magento Admin go to Content - Pages, click **Add New Page**
2. Expand **Content** Click **Show / Hide Editor**, select **Insert Image...**
3. Click **Search Adobe Stock**
4. Click **Sort by** dropdown list and observe 
### Expected result (*)
The _Undiscovered_ is a separate filter if check the https://stock.adobe.com/ web page. _Undiscovered_ should be in Filters not in **Sort by**
![undiscovered_filter_AdobeStock](https://user-images.githubusercontent.com/45624059/69853777-61958180-1290-11ea-9984-42ae3aac53dc.png)

### Actual result (*)
The _Undiscovered_ item present in **Sort by** dropdown list
![undiscovered sort_mage](https://user-images.githubusercontent.com/45624059/69853563-e9c75700-128f-11ea-885f-ac410a31e316.png)

**Comment by sivaschenko** [comment]
Adobe Stock API does not support `Undiscovered` as a filter - it is sorting. Adobe Stock website is using a different service
