### ISSUE TITLE
Bookmarks controls are shifter to the right out of screen

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#821]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
### Steps to reproduce (*)
1. From Magento Admin go to Content - Pages, click **Add New Page**
2. Expand **Content** Click **Show / Hide Editor**, select **Insert Image...**
3. Click **Search Adobe Stock**
4. Click **Filters** and **Apply** any filter, _Price - Standard_ for example (this step is done to enable Save View As button)
5. Click **Default View** and select **Save View As...**
6. Type in any name and click Enter key
7. Click on View dropdown again and observe
![filter_remove_edit](https://user-images.githubusercontent.com/45624059/70053839-fa086a80-15de-11ea-97ad-54ba17a13d3b.gif)
 
### Expected result (*)
The buttons **Save all Changes**, **Edit** and **Delete** should be visible 
See, for example, the View from _Catalog - Products_
![Peek 2019-12-03 14-46](https://user-images.githubusercontent.com/45624059/70053960-40f66000-15df-11ea-9a87-59bc11c4df50.gif)

### Actual result (*)
The **Save all Changes**, **Edit** and **Delete** buttons do not fit into the screen
![remove](https://user-images.githubusercontent.com/45624059/70053813-e3621380-15de-11ea-98d9-e233fd59712f.png)

**Comment by sivaschenko** [comment]
The fix for this issue should be delivered to develop branch

**Comment by filmaj** [comment]
This, possibly, may be good to cover with an MFTF test. Thoughts?

**Comment by sivaschenko** [comment]
@filmaj good idea. @chalov-anton is there a test case(s) that are covering the functionality of buttons that were not available on the Adobe Stock grid?

**Comment by chalov-anton** [comment]
> @filmaj good idea. @chalov-anton is there a test case(s) that are covering the functionality of buttons that were not available on the Adobe Stock grid?
@sivaschenko We have created a Scenario in SucumberStudio which covers this

**Comment by chalov-anton** [comment]
@sivaschenko We have created a Scenario in CucumberStudio which covers this, and already used it in the previous Regression Cycle

**Comment by sivaschenko** [comment]
@chalov-anton could you please create an "[MFTF] Cover Adobe Stock grid bookmarks functionality" issue with the steps from the scenario in CucumberStudio. Thank you!
