### ISSUE TITLE
Images in grid is not correctly aligned after clear filters

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#824]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Select and apply filter **Orientation=Square**
- Click **Clear All**

### Expected result (*)
Images in grid is properly aligned

### Actual result (*)
Images in grid is not correctly aligned
![image](https://user-images.githubusercontent.com/51681379/70061375-d64c2100-15ec-11ea-9ce8-6c99dce00f1d.png)

![Peek 2019-12-03 16-55](https://user-images.githubusercontent.com/51681379/70062089-1233b600-15ee-11ea-811c-1cf474086eaa.gif)

**Comment by drpayyne** [comment]
Hey @sivaschenko, would reloading the grid just like https://github.com/magento/adobe-stock-integration/blob/1.1-develop/AdobeStockImageAdminUi/view/adminhtml/web/js/panel.js#L41 be a good solution? I'm thinking there might be a better way. Calling that method fixes the issue tho, I tested on the browser console.

**Comment by sivaschenko** [comment]
@drpayyne the grid should be reloaded when filters are dropped anyway, I guess the issue is in masonry.js that for some reason not recalculating the styles on that reload

**Comment by drpayyne** [comment]
Thanks @sivaschenko, I shall look into it.

**Comment by sivaschenko** [comment]
Hi @drpayyne any updates on this issue?

**Comment by drpayyne** [comment]
Hi @sivaschenko, I had tried some solutions but that didn't work. Will try again this weekend and get back if there's a problem. Sorry about the delay, thanks!

**Comment by rogyar** [comment]
Hi folks. Is this issue still actual? I cannot reproduce it for the current mainline somehow 

![Screen Recording 2020-03-01 at 15 52 39 2020-03-01 15_58_29](https://user-images.githubusercontent.com/2148959/75628040-a43f6080-5bd5-11ea-9381-af5c9a54c148.gif)

**Comment by chalov-anton** [comment]
Still present on the lates 1-1.develop

**Comment by sivaschenko** [comment]
@rogyar feel free to self-assign the issue back if you'd like to work on it

**Comment by Nazar65** [comment]
PR created at M2 repo magento/magento2#28366
