### ISSUE TITLE
Update media gallery grid styles to match the mockups

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#828]
### See more information in the story:

https://github.com/magento/adobe-stock-integration/issues/460

### Preconditions
1. Install Magento with Adobe Stock Integration

### Steps to reproduce (*)
1. Login to Admin Panel
2. Select "Media Gallery Development" from the menu on the right

### Expected result (*)
The masonry grid is rendered using default styles:

![image](https://user-images.githubusercontent.com/2028541/70070972-6f2e6c80-15ec-11ea-9330-ed1d9b07bc30.png)

### Actual result (*)
The masonry grid styles should match the mockups:

![image](https://user-images.githubusercontent.com/2028541/70071106-b61c6200-15ec-11ea-9ce3-b4bc53a8bb90.png)

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I found some issue with the masonry component and I will list out the possible options for the masonry component.
1) Option to add additional classes to the masonry component
2) I think we also need to add the `maxWidth` option cause width needs to be constant as per layout and we can do this via extending the masonry but I think we need to introduce this option as default in masonry component cause its easy for customisation in future and hope it make sense.

Let me know your thoughts
Thanks

**Comment by sivaschenko** [comment]
@konarshankar07 makes sense, thanks for bringing this up! Please feel free to add required defaults to masonry grid in magento2 repo (please link the PR to this issue)

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I'm confused regarding the additional option for the media gallery grid. In masonry grid, Width are variable but in our case media gallery we required fixed width and height so I'm thinking additional of `maxWidth` option we need to add `isMasonry` grid option which is default true but if developer required simple grid with equal width and height then developer can easy enable this option from ui_component with adding equal width and height. Let me know your thoughts
Thanks

**Comment by sivaschenko** [comment]
@konarshankar07 please take a look at https://github.com/magento/adobe-stock-integration/pull/878 and let me know what do you think about using the parent selector instead

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Sorry for the delay, Yes, you can use parent selector but it will create issue when we open image preview. Please check the following screenshot
![image](https://user-images.githubusercontent.com/39480008/72215584-8b51f180-353a-11ea-9b20-0f5532a7010d.png). So we need to fix via masonry.js
Correct me if I'm wrong
Thanks

**Comment by sivaschenko** [comment]
Hi @konarshankar07 I don't think we need image-preview for the Media Gallery. We'll need to remove image-preview component and display image details in a slide panel instead:

![image](https://user-images.githubusercontent.com/2028541/72356951-0efa1280-36e2-11ea-946e-0847c199734f.png)

Anyway, I think that the parent selector should be enough to apply the required styles. I'd avoid any additional complications of masonry component if possible.
