### ISSUE TITLE
Add "Unlicensed" overlay to media gallery grid

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#830]
### See more information in the story:

https://github.com/magento/adobe-stock-integration/issues/460

### Preconditions
1. Install Magento with Adobe Stock Integration
2. Save at least one Adobe Stock image preview to media gallery

### Steps to reproduce (*)
1. Login to Admin Panel
2. Select "Media Gallery Development" from the menu on the right

### Actual result (*)

Images do not include any overlay labels:

![image](https://user-images.githubusercontent.com/2028541/70070972-6f2e6c80-15ec-11ea-9330-ed1d9b07bc30.png)

### Expected result (*)

Images that are saved from Adobe Stock and are not licensed should have "Unlicensed" red overlay label:

![image](https://user-images.githubusercontent.com/2028541/70071106-b61c6200-15ec-11ea-9ce3-b4bc53a8bb90.png)

**Comment by filmaj** [comment]
To clarify, preconditions here include:

- user must be signed into Adobe IMS
- user has saved an image preview

Is the above correct?

**Comment by sivaschenko** [comment]
@filmaj the second precondition is correct. The first one is not - the information about unlicensed assets in media gallery should be retrieved from Magento database (not from API as on Adobe Stock grid) so the login is not required.

Preconditions are updated accordingly

**Comment by filmaj** [comment]
Just a point of clarification: is the licensed/unlicensed DB field implemented already or does that still need to be implemented? And if so, which issue is that tracked in?

**Comment by sivaschenko** [comment]
@filmaj the source field is `adobe_stock_asset.is_licensed` (already there)
