### ISSUE TITLE
Grid header has extra space in right side

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#845]
### Preconditions (*)
1. Install Magento 2.3.4 with Adobe Stock Integration 1.0.0-release
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid

### Expected result (*)
![image](https://user-images.githubusercontent.com/51681379/70221199-9b62fe00-1750-11ea-9e54-bce5e81ebde4.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/51681379/70221229-a584fc80-1750-11ea-8ee5-0c4132585b24.png)

**Comment by filmaj** [comment]
I think this was a change introduced by my recently merged PR in order to make space for the Views dropdown (#835)
