### ISSUE TITLE
The cursor is not moved in Page Number field with keyboard arrow keys

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#846]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
### Steps to reproduce (*)
1. From Magento Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**, click **Show / Hide Editor**, select **Insert Image...**
3. Click **Search Adobe Stock**
4. Try to edit the pages field, move the cursor on it and click
![pages field1](https://user-images.githubusercontent.com/45624059/70228598-4974a500-175d-11ea-96f5-7d64107793d2.png)
5. Try to move the cursor with left and right arrow keys on the keyboard 
### Expected result (*)
The cursor should be moved in order to edit the page number 
### Actual result (*)
The cursor is not moved
This is a bug because it works in Сatalog - Products for example
![arrow keys](https://user-images.githubusercontent.com/45624059/70229044-1d0d5880-175e-11ea-8b2c-12abc4ae9c4c.gif)

**Comment by rogyar** [comment]
From my attempts to figure out what's wrong, I found the following. If you try to add any `input type="number"` to the AdobeStock modal, you get the same issue. So, I assume, it's not about the pager component somehow but some parent event listener.
Will proceed with the clues gathering.

**Comment by rogyar** [comment]
Well then, I got the cause of this issue. The jsTree hotkeys plugin conflicts with `<input type="number"/>`. The plugin works well with most input types but overtakes keyboard cursors control from the number type. So, basically, if we have jsTree with hotkeys plugin enabled and `<input type="number"/>` on the same page, the keyboard cursor buttons will be handled by jsTree when any of the`<input type="number"/>` is focused. 
I have not found a reliable solution so far except disabling the hotkeys plugin 

https://github.com/magento/magento2/blob/cfa160903307359cc3de11e5e781774e289276e5/app/code/Magento/Cms/view/adminhtml/web/js/folder-tree.js#L20

**Comment by rogyar** [comment]
Nevermind, I found a more elegant solution 🤓

**Comment by drpayyne** [comment]
@sivaschenko, issue label status needs to be applied here too.

**Comment by sivaschenko** [comment]
Thanks @drpayyne , applied
