### ISSUE TITLE
The Preview images are changed if move the cursor with arrow keys in File Name field

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#847]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, select **Insert Image...**
3. Click **Search Adobe Stock**
4. Select any NON saved image from the grid and click **Save Preview** or **Save** if the image is _Licensed_
5. In _Save Preview_ window _File name_ field, move the cursor with left **arrow key from the keyboard**
### Expected result (*)
The images on the background do not change, only the cursor.  
### Actual result (*)
The cursor is moved, but the preview images on the background are switched. **And after clicking Confirm, you can accidentally save the image that was not selected in the first place**
![Peek 2019-12-05 14-25](https://user-images.githubusercontent.com/45624059/70235321-6c0dba80-176b-11ea-993d-4ecd78f274fd.gif)

**Comment by drpayyne** [comment]
PR created at ^ https://github.com/magento/magento2/pull/25991

**Comment by drpayyne** [comment]
@sivaschenko some help here with respect to the label status please :sweat_smile:, thank you!

**Comment by sivaschenko** [comment]
@drpayyne done. Sorry, our bots are not currently ready to work cross repositories
