### ISSUE TITLE
Admin user with all permissions for Media Gallery is not able to license images

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#848]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Create user role `new_role` with permissions for Pages and Media Gallery:

![image](https://user-images.githubusercontent.com/51681379/70236679-1686dd00-176e-11ea-94bf-cfeeeb5915fb.png)

- Create admin user `test_user` with `new_role`
- Login to admin panel by `test_user`
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Expand image preview
- Click **License and Save**

### Expected result (*)
Admin user with checked **License Images** permission should be able license image

### Actual result (*)
Admin user is not able to license images
![image](https://user-images.githubusercontent.com/51681379/70236913-944ae880-176e-11ea-88b6-5302440f610b.png)

**Comment by sivaschenko** [comment]
Thanks for the report @engcom-Delta ! Actually `Adobe IMS` permissions have to be enabled to allow user to login to Adobe IMS.

Can you please check the following cases (and add them to our test cases):
 - Licensing and Login IMS ACL are enabled for admin - Admin can login and license images
 - Login ACL is enabled but Licensing ACL is disabled - Admin can login to adobe stock account byt cannot license images

**Comment by engcom-Delta** [comment]
@sivaschenko 
**Case 1:**
Licensing and Login IMS ACL are enabled for admin - :heavy_check_mark: Admin can login and license images
**Case 2:**
Login ACL is enabled but Licensing ACL is disabled - :x: Admin can login to adobe stock account but cannot license images

**Case 2**
**Steps to reproduce:**
- Login to admin panel
- Create user role `new_role1`:
![image](https://user-images.githubusercontent.com/51681379/70434260-69bda000-1a8c-11ea-98bb-5715d2d4815f.png)

- Create admin user `test_user` with `new_role1`
- Login to admin panel by `test_user`
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Expand image preview
- Click **License and Save**


### Expected result (*)
Admin can login to adobe stock account but cannot license images

### Actual result (*)
Error "TypeError: Cannot read property 'message' of undefined" and infinite loader is shown on page 
![#848issue](https://user-images.githubusercontent.com/51681379/70433821-52ca7e00-1a8b-11ea-8ae7-cab0d1831b20.png)

**Comment by sivaschenko** [comment]
Thanks for checking @engcom-Delta ! The current issue is not a bug, Admin needs to have IMS permissions set to license an image. The second case is extracted to separate issue https://github.com/magento/adobe-stock-integration/issues/856
