### ISSUE TITLE
The "See more" button doesn't work when More images are loaded and the same image is previewed again

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#850]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, select **Insert Image...**
3. Click **Search Adobe Stock**
4. Click, for example on the first image to open the Preview
5. Click **See more**
![see more link](https://user-images.githubusercontent.com/45624059/70308091-358b7a80-1813-11ea-9867-0ee94a7495a8.png)
6. From the updated grid, select the same image you've opened previously, and click **See more** 

### Expected result (*)
The page is scrolled to the top

### Actual result (*)
Nothing happens 

![see more](https://user-images.githubusercontent.com/45624059/70308287-8e5b1300-1813-11ea-8eb7-9146927248bf.gif)

**Comment by sivaschenko** [comment]
The expected result is to simply give user a feedback: scroll the page to the top for the user to see that filter is already applied

**Comment by chalov-anton** [comment]
The issue is reproducible if the Enhanced Media Gallery is enabled.

**Comment by chalov-anton** [comment]
The issue is reproducible on the latest codebase
