### ISSUE TITLE
Rename "Save" image preview button to "Save Licensed"

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#851]
### Preconditions (*)

1. Have licensed images
Imagine that you cleaned cache and cookies and forgot to sign in again to Adobe IMS

### Steps to reproduce (*)

1. Activate masonry component from the Media Gallery
2. In top-right corner click "Sign Out"
3. Save a preview of the image that was licensed
4. Remember now that for licensing you have to Sign In
5. Sign in to Adobe IMS
6. Click the same image

### Expected result (*)

"Save Licensed" and Open in Media Gallery

### Actual result (*)

Save and Open in Media Gallery
![image](https://user-images.githubusercontent.com/11827230/70323242-fb32d500-1834-11ea-92d9-6898071a0c8a.png)

**Comment by sivaschenko** [comment]
Hi @TomashKhamlai thanks for the issue. The behaviour looks correct to me. We are allowing to find the saved preview image or save licensed version of the image.

However, to avoid the confusion we might want to rename Save button to "Save Licensed" @tkacheva @belbiy What do you think?

**Comment by TomashKhamlai** [comment]
Also, pay attention to the time spent on changing from "Licence" to "Save". Now it takes ~5 seconds. Don't know if something can be done to improve the user experience here. The only idea I had was to work on faster data delivery or caching the last query result and waiting for the data before revealing a last opened image.
![Peek 2019-12-06 18-13](https://user-images.githubusercontent.com/11827230/70338831-4f01e600-1856-11ea-9983-d561584d110c.gif)

**Comment by sivaschenko** [comment]
Thanks for clarification @TomashKhamlai . We decided to rename the Save button to Save Licensed to avoid confusion: the issue title and expected result changed accordingly
