### ISSUE TITLE
Сannot apply several filtering options for Orientation filter at the same time 

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#861]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Try to select and apply several filtering options for Orientation filter at the same time 

### Expected result (*)
User can select several filtering options at the same time
https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/db8a2237-788d-44ac-936f-98655c6854af/Stock-Filters-open-orientation-selected/

### Actual result (*)
Only one filtering options is applied at same time

**Comment by sivaschenko** [comment]
Hi @coderimus are you working on this issue?

**Comment by drpayyne** [comment]
Hi @sivaschenko, I've started work on this.

The SearchCriteria's Filter returns an array of the selected orientation options at `AdobeStockClient/Model/SearchParametersProvider/Orientation.php:27`. We'll need to handle this, but `AdobeStock\Api\Models\SearchParameters::setOrientation` in vendor accepts only a single orientation value as a string. Do you have any suggestions on how we can pass multiple orientations to the API? Or does the API not support this at all?

Related: https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/api/11-search-reference.md#about-search-and-filter-criteria

**Comment by sivaschenko** [comment]
Hi @drpayyne I think we should close this issue as the API does not provide the required capability for this. Thank you for your investigation!
