### ISSUE TITLE
"Found 2 elements with non-unique id" warning in browser console on Adobe Stock grid

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#862]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Chrome version(Version 79.0.3945.79)

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid

### Expected result (*)
No warning messages, all id's should be unique

### Actual result (*)
Warning message **"Found 2 elements with non-unique id #adobe_stock_images_listing.adobe_stock_images_listing.listing_top.listing_paging_sizes"** is shown

![Screenshot from 2019-12-12 17-04-53](https://user-images.githubusercontent.com/51681379/70723562-bd84ef00-1d01-11ea-96eb-9d770cadbdf7.png)

**Comment by drpayyne** [comment]
I'm not able to reproduce this error and I don't remember coming across this warning recently either. Is anyone else able to reproduce this?

**Comment by engcom-Delta** [comment]
@drpayyne This console message occurs on latest Chrome version(Version 79.0.3945.79).
For example, Firefox v.71.0 doesn't show this message

**Comment by drpayyne** [comment]
Yes, I see the duplicate IDs. Thanks.

**Comment by konarshankar07** [comment]
Hello guys,
I have investigated this issue and I think this issue also present in the core magento 2. Here is the screenshot of catalog grid console window
![image](https://user-images.githubusercontent.com/39480008/70863743-4eadcd00-1f71-11ea-9cf1-4b7b20b2601a.png)

**Comment by rogyar** [comment]
Hi folks. 

In this particular case, the issue is related to sticky toolbar. Basically, the sticky toolbar duplicates the original toolbar's content but stays hidden. That's why we have two inputs with the same IDs. 
I just wonder if we still need [the sticky toolbar](https://github.com/magento/adobe-stock-integration/blob/60cfa8063cd3aacd7e84e241f1108ea38ecffd13/AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml#L38) functionality in the product listing. 
Since we have two toolbars (top and bottom) I'm not sure about the use case of the sticky toolbar. Moreover, the sticky toolbar functionality for some reason does not work but it might be a sort of local issue. @sivaschenko, could you please help with the decision here? Thank you.

**Comment by konarshankar07** [comment]
@rogyar 
Thanks for the explaination. Yes, I also figured it out the same problem. we can easily fix this issue in our project by disabling the sticky toolbar cause we are not using sticky toolbar in `adobe_stock_images_listing` currently we have hidden the sticky toolbar using less but personally I think we need to fix this issue in magento repo

**Comment by sivaschenko** [comment]
@rogyar @konarshankar07 thanks for investigation, I think we should disable stick toolbar for both adobe stock integration and new media gallery grids

**Comment by sivaschenko** [comment]
@chalov-anton can you please create a general issue for magento2 repository. That should be possible to replicate for all grids that have sticky headers enabled

**Comment by chalov-anton** [comment]
> @chalov-anton can you please create a general issue for magento2 repository. That should be possible to replicate for all grids that have sticky headers enabled

:heavy_check_mark: https://github.com/magento/magento2/issues/26147

**Comment by chalov-anton** [comment]
> @chalov-anton can you please create a general issue for magento2 repository. That should be possible to replicate for all grids that have sticky headers enabled

@sivaschenko :heavy_check_mark: https://github.com/magento/magento2/issues/26147
