### ISSUE TITLE
User is not Signed Out from IMS after the User Role was changed

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#864]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. From Magento Admin go to _System - Permissions - User Roles_, click **Add New Role**
2. Select the following **Role Resources** and **Save Role**
- **_Content_** 
![content](https://user-images.githubusercontent.com/45624059/70789906-9fb89800-1d9c-11ea-80e6-83be7502d78d.png)

- **_Adobe IMS_**
![ims](https://user-images.githubusercontent.com/45624059/70790067-f2924f80-1d9c-11ea-9161-ce5393a58568.png)
3. Go to _System - Permissions - All Users_. **Add New User** and assign the previously created **User Role**. **Save User**
4. Sign In Magento Admin with the previously created User, and go to _Content - Add New Page - Content - Show / Hide Editor - Insert Image..._
5. Click **Search Adobe Stock** and **Sign In** to IMS
6. **Do not Sign Out from IMS** Sign Out from Magento Admin
7. Sign In Magento with Admin Account and change the User Role
Go to  _System - Permissions - User Roles_, select the previously created Role. Go to Role Resources and uncheck _Adobe IMS_
![ims uncheckedpng](https://user-images.githubusercontent.com/45624059/70791190-47cf6080-1d9f-11ea-97ea-923c063313bd.png)
**Save Role**
8. Sign In Magento Admin with the previously created User
9. Go to _Content - Add New Page - Content - Show / Hide Editor - Insert Image...- Search Adobe Stock_ And try to Sign Out from IMS

### Actual result (*)
Sign Out is not completed, a _"POST 403 (Forbidden)"_ error appears in Dev Console.
**User can continue Licensing the images**
![licence continue](https://user-images.githubusercontent.com/45624059/70792092-28d1ce00-1da1-11ea-9f4f-fd0470a99dbd.gif)

### Expected result (*)
User is not Signed In IMS

### Technical details (*)

The plugin/observer should be added to clean admin user tokens stored in `adobe_user_profile` db table when the permissions for users role are updated and _Adobe IMS_ permissions are removed

**Comment by sivaschenko** [comment]
@tkacheva can you please advise what is the expected behaviour in this situation?:
