### ISSUE TITLE
Possible to open several "Sign In Adobe ID" windows

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#865]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Ensure you are Signed out on adobe.com

### Steps to reproduce (*)
1. Login to Admin panel
1. Open media gallery (**Content** - **Pages**, click **Add New Page**, expand **Content**, select **Insert Image...**)
3. Click **Search Adobe Stock**
4. Click **Sign In** link in the top right corner
5. When the login window opens, switch back to Magento window and click "Sign in" link again or "License and save" button

### Actual result (*)
Existing  _Sign In Adobe ID_ window stays open. The second _Sign In Adobe ID_ window is opened.

### Expected result (*)
The previous _Sign In Adobe ID_ windows should be closed when a new one is opened

**Comment by sivaschenko** [comment]
Sign in link should not be active if a login window is opened
