### ISSUE TITLE
[Feature request] Add an ability to move images between folders in Media Gallery

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#871]
## Desription
There is no opportunity to move images from Media Gallery between folders. User has to delete an image from Media Gallery, switch to another folder, and save it again.
Add an ability to move Images between folders 

## Benefits
Ability to change the location of the image for more convenience 

## Actual Result
No ability to change the image location 
![folders](https://user-images.githubusercontent.com/45624059/70909519-53788c80-2016-11ea-8f8b-1b6192774a28.png)

**Comment by sivaschenko** [comment]
Moving images between folders is an insecure operation that could lead to potentially broken frontend and any content where the assets from the folder have been used.
For a better understanding of consequences, it's better to let admin user to delete and reupload the images instead
