### ISSUE TITLE
The folders structure is not updated after deleting, the focus remains on deleted folder

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#888]
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery is disabled

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, select **Insert Image...**
3. Select _Storage Root_ folder, for example, and Create Folder with name _Folder_, for example
4. Switch to newly created _Folder_ and click **Delete Folder**, **Ok** (Do not click anywhere else)
5.  Click **Search Adobe Stock**, select a non saved image and click **Save Preview**, **Confirm**

### Expected result (*)
The folders tree is updated after Deleting a folder, and the cursor is switched to _Storage Root_ folder

### Actual result (*)
_The image cannot be located_ message appears, but the image appears in the Gallery 
![image_cannot_be located](https://user-images.githubusercontent.com/45624059/71984093-d913e480-3230-11ea-86a3-f6ff60720033.png)
After reopening the  **Content** - **Pages**, click **Add New Page** ... the Folder and the image in it will be displayed
![deleted_folder1](https://user-images.githubusercontent.com/45624059/71984224-1a0bf900-3231-11ea-85e5-aa50642c9a78.gif)

**Comment by sivaschenko** [comment]
Hi @pmclain are you working on this issue? Are there any updates?

**Comment by sivaschenko** [comment]
@chalov-anton can this issue be reproduced on the new media gallery?

**Comment by engcom-Bravo** [comment]
> @chalov-anton can this issue be reproduced on the new media gallery?

@sivaschenko No, this is not reproducible on Enhanced Media Gallery. The folder structure is updated, and the image from the folder has been deleted from the Database table ``` media_gallery_asset```
