### ISSUE TITLE
AdminAdobeStockImagePreviewKeywordsSearchTest fails due to async loading of similar series/model images

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#890]
This is very similar to #686 (and the relevant fix #760).

Link to a failing job exhibiting this behaviour: https://travis-ci.org/magento/adobe-stock-integration/jobs/633929629
And link to screenshot from the moment of failure for this test in the above job: https://i.ibb.co/fCzKF1t/Magento-Acceptance-Test-adobe-stock-integration-suite-keywords-Backend-Admin-Adobe-Stock-Image-Preview-Keywords-Search-Test-Cest-Admin-Adobe-Stock-Image-Preview-Keywords-Search-Test-fail.png

Relevant test output:

```
[expandImagePreview] AdminAdobeStockExpandImagePreviewActionGroup
  [clickOnThumbnail] click "aside.adobe-stock-modal [data-role=grid-wrapper] img[data-role=thumbnail]"
  [waitForImagePreviewToExpand] wait for loading mask to disappear 
[scrollToKeywords] execute js "document.querySelector('.keywords').scrollIntoView()"
[clickAccessoryKeyword] AdminImagePreviewKeywordSearchActionGroup
  [seeKeyword] see element "//div[@class='keyword']//span[text()='accessory']"
[saveScreenshot] save screenshot 
```

So the general flow is:

1. Expand image preview
2. Wait for loading mask to disappear
3. Scroll to the "keywords" section
4. Assert on visible keywords.

Based on the output above and the screenshot at the moment of failure, it looks like the similar model/series images are still loading even _after_ we have scrolled down to the keywords section. As such, the keywords are pushed down past the bottom of the viewport, effectively making all keywords not visible. Thus the test fails.

I think one possible avenue to make this test more consistent is to wait for the same series images to load before scrolling to the keywords section, but perhaps others have better ideas.

**Comment by drpayyne** [comment]
Hi @filmaj, I'm trying to reproduce this and I'm unable to run any MFTF test. It constantly fails at `AdobeStockAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSetConfigActionGroup.xml:17`: `CSS or XPath element with '#system_adobe_stock_integration-head' was not found`. Am I out of loop on anything?
