### ISSUE TITLE
[Bug] Media Gallery buttons are shifted to the left

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#895]
### Preconditions (*)
1. Magento with Adobe Stock Integration is installed

### Steps to reproduce (*)
1. Login to Admin Panel
2. Open Media Gallery (i.e. Catalog -> Category -> Content -> Select From Media Gallery button)

### Expected result (*)
Media gallery buttons should be aligned to the right

### Actual result (*)
Media gallery buttons are shifted to the left

![image](https://user-images.githubusercontent.com/2028541/72358619-c42dca00-36e4-11ea-9530-4bb93271b5ef.png)

**Comment by diazwatson** [comment]
@sivaschenko just to confirm, I am right to say that since the Magento_MediaGallery module has been moved to Magento2 this change should be done in Magento 2 repo?

**Comment by diazwatson** [comment]
naughty bot 👊

**Comment by sivaschenko** [comment]
@diazwatson right, also see my review in the PR: https://github.com/magento/magento2/pull/26413#pullrequestreview-343957378
