### ISSUE TITLE
Add explanation message to the configuration

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#90]
### Description
- Add tooltip with a message that explains how to get credentials for the integration. 
Similar tooltip already implemented in the admin panel, please, see Configuration for PayPal Express
<img width="654" alt="Screen Shot 2019-06-13 at 16 35 16" src="https://user-images.githubusercontent.com/11355520/59469117-889eea80-8df9-11e9-8ad8-ad7a6e10dbfa.png">

**Message text**: "Configure Adobe Stock account on the ['Adobe.io](https://console.adobe.io/) to retrieve API key"

### Documentation
Story: [User configures Adobe Stock integration](https://github.com/magento/adobe-stock-integration/issues/29)

### QA notes
- User sees a message that explains how to get these credentials with a link to Adobe.io

**Comment by diazwatson** [comment]
@sivaschenko @sidolov Guys, do you know why this issue is back in the backlog?

**Comment by sivaschenko** [comment]
@diazwatson sorry, my bad, had to close it when merging a pull request

**Comment by diazwatson** [comment]
np :)
