### ISSUE TITLE
Delete an image from Media Gallery

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#902]
### Preconditions (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)

### Steps to reproduce (*)
1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)

### Expected result (*)
The actions menu is available for each image. The actions menu contains the "Delete" option. Clicking the "Delete" options opens the confirmation popup and if confirmed deletes an image from filesystem and database
![image](https://user-images.githubusercontent.com/2028541/73016561-fee6df00-3e15-11ea-90fe-1a79f013fa70.png)

### Technical details (*)
Use `\Magento\MediaGalleryApi\Model\Asset\Command\DeleteByPathInterface` to delete the image data from the database.
Use `\Magento\Cms\Model\Wysiwyg\Images\Storage::deleteFile` to delete the image from filesystem

**Comment by sivaschenko** [comment]
Hi @serhiyzhovnir , are you working on this issue? Do you have any updates?

**Comment by serhiyzhovnir** [comment]
Hi @sivaschenko
I still working on this issue.
I will create PR soon.
Thank you!
