### ISSUE TITLE
View details slide panel for an image in media gallery

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#904]
### Preconditions (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)

### Steps to reproduce (*)
1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)
3. Open the menu for any image
4. Click "View details"

### Expected result (*)
"View Details" option is available on the image menu. Click on "View details" opens a slide panel containing the image details (Does not include "Used in" section)
![image](https://user-images.githubusercontent.com/2028541/73016561-fee6df00-3e15-11ea-90fe-1a79f013fa70.png)

![image](https://user-images.githubusercontent.com/2028541/73016741-5c7b2b80-3e16-11ea-95a1-5be08d1330e9.png)

**Comment by sivaschenko** [comment]
Hi @serhiyzhovnir are you working on this issue, do you have any udpates?

**Comment by serhiyzhovnir** [comment]
Hi @sivaschenko 
The PR is created: https://github.com/magento/adobe-stock-integration/pull/1018
Thank you!

**Comment by sivaschenko** [comment]
Thank you @serhiyzhovnir !
