### ISSUE TITLE
Specify correct ACL resources for UI component and backend resources

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#93]
### Description
- Specify correct ACL resources for UI component and backend resources

### Documentation
Story: [User controls access to Adobe Stock images from Admin Panel in ACL](https://github.com/magento/adobe-stock-integration/issues/42)

### QA notes
1. User opens Resources tree and sees Adobe Stock Config node under Settings - Configuration - System Section.
2. User includes this resource into the role. That will allow admin user with this role to set up an integration with Adobe stock
3. User sees Adobe Stock node under Content - Elements - Media Gallery. This node has 2 child nodes:
  * Save preview images
  * License images

4. User includes Save preview images resource into the role. This will allow admin user with the role assigned only search for stock images and same their previews into Media Gallery. License image is not accessible.
5. If user doesn't select any of the 2 options, user with the role won't see the access to Adobe Stock from Media Gallery
6. If user selects the parent node Adobe Stock, both child nodes get selected.

**Comment by vpodorozh** [comment]
#kharkiv2019
