### ISSUE TITLE
[Story 52] User accesses Media Gallery from the main navigation 

### ISSUE THREAD

**Issue by tkacheva** [magento/adobe-stock-integration#937]
## Story
As a Designer/UX Person I want to access Media Gallery directly from the Admin Panel main navigation  *so that* I can get the assets prepared without interfering with the content 

## Business Value
External people can be given access to manage the media assets only

## Preconditions 
1.  Admin User is logged into Admin Panel

## Acceptance Criteria
* User opens *Content*  navigation menu and sees new group under Elements - *Media*
* User sees the *Media Gallery* link inside the *Media* group 
* User navigates to the Media Gallery and sees a page from which they can access the following use cases:
** upload images
** delete images
** move images into folders
** create folders
** delete folders
** change folder names
** search images
** filter images
** sort image results 
** view image details
** update image meta tags 
** create image renditions 
** delete image renditions 
** search for stock images
** license unlicensed stock images

**Comment by sivaschenko** [comment]
@tkacheva there are currently only 3 levels of menu items in Magento Admin Panel. The requirements of this story contain 4 levels. Should we shorten it to "Content -> Elements -> Media Gallery" for consistency?
