### ISSUE TITLE
User can navigate between images in the preview mode

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#94]
### Description
- User can navigate between images in the preview mode

### Documentation
Story: [User navigates to next previous image from the currently viewed](https://github.com/magento/adobe-stock-integration/issues/40)

### QA notes
- User sees controls to view next and previous images in search result
- User activates viewing next\previous image details in the search result
- User sees image preview and image attributes updated. Any other elements on the page aren't reloaded
- User sees details of the next\previous image in search result.

### Dependency
Has dependency on https://github.com/magento/adobe-stock-integration/issues/8

**Comment by sivaschenko** [comment]
Implemented in https://github.com/magento/adobe-stock-integration/pull/221
