### ISSUE TITLE
[WIP]: User saves image preview to the Magento media gallery

### ISSUE THREAD

**Issue by sidolov** [magento/adobe-stock-integration#95]
### Description
- User saves image preview to the Magento media gallery

### Documentation
Story: [User saves image preview](https://github.com/magento/adobe-stock-integration/issues/26)

### QA notes
- User saves image preview
- User sees the image uploaded into the currently selected folder of Magento Media Gallery
- The image is selected

**Comment by diazwatson** [comment]
Adding `has dependency` label as I believe that work in https://github.com/magento/adobe-stock-integration/issues/8 needs to be done in order to unblock this task.
