### ISSUE TITLE
Introduce a dedicated Media Gallery page

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#963]
### Story

[Story 52](https://github.com/magento/adobe-stock-integration/issues/937) User accesses Media Gallery from the main navigation

### Preconditions (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)

### Steps to reproduce (*)
1. Login to Admin panel
2. Go to Content -> Elements -> Media Gallery (this menu item should be created in scope of this task)

### Expected result (*)
An Admin page displaying the media gallery should be opened

### Technical Details
A new ui_component listing configuration `standalone_media_gallery_listing.xml` should be introduced for the media gallery grid (as there will be differences between the media gallery opened to insert an image and standalone version)

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I think we can create a new module for the standalone media gallery. Let me know your thoughts
Thanks

**Comment by sivaschenko** [comment]
Hi @konarshankar07 please add the menu item and page in the MediaGalleryUi module
