### ISSUE TITLE
[Adobe Stock API] Pagination is not accurate

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#97]
### Preconditions:
1. php bin/magento config:set adobe_stock/integration/enabled 1
2. php bin/magento config:set adobe_stock/integration/api_key \<key\>
3. php bin/magento config:set cms/wysiwyg/enabled disabled
4. php bin/magento config:set admin/security/admin_account_sharing 1
5. php bin/magento config:set admin/security/use_form_key 0
6. php bin/magento cache:flush

### Steps to reproduce:
1. Navigate to Content > Elements > Pages
2. Click Add New Page button
3. Fill Title with "Test CMS Page"
4. Expand the "Content" section
5. Fill Content Heading with "Test Content Heading"
6. Click "Insert Image..." button
7. Click "Search Adobe Stock" button
8. Type `chris cornell` in the search input
9. Expand "per page" dropdown
10. Click "Custom"
11. Type 2
12. Click arrow right button
13. Submit search
14. Verify that 1 image was returned
15. Type `cornell` in the search input
16. Verify that 407 results were found. Pagination is 2 images per page. 2 images are displayed. The position is 1 of 204, that means 204*2=408 and 408-407=1. 1 is the value we expect in the next step.
17. Change the position to page 204 and verify that 1 image is displayed on the last page.
18. Set position back to the first page.
19. Type `chris` to the search input

### Expected result:
:heavy_check_mark: 1. 2 images are displayed. Position 1 of 319. (637 results)
:heavy_check_mark: 2. 2 images are displayed. Position 10 of 319 (637 results)
:heavy_check_mark: 2. 2 images are displayed. Position 11 of 319 (637 results)

### Actual result
1. :x: 3 images are displayed. :heavy_check_mark: Position 1 of 319. (:heavy_check_mark: 637 results)
2. 3 images are displayed. :heavy_check_mark: Position 10 of 319. (:heavy_check_mark: 637 results)
3. :heavy_check_mark: 2 images are displayed. :x: Position 11 of 314. (:x: 627 results)

### Other tests:
`a`, `b`, `c`, ... , `x`, `y`, `z` returns 3 images, when grouped by 2

**Comment by sidolov** [comment]
Hi @shikhamis11 ! How is your progress on the issue? Do you need help with it?

**Comment by shikhamis11** [comment]
hello @sidolov . I am working on the issue . I will let you know If I need help :)
Thanks

**Comment by chfabbro** [comment]
Hi @shikhamis11 and @sidolov. There is a known bug (or "design feature") in the Stock API where all results will have ~10 extra Premium images that throw off the offset value unless you set an additional filter:
`search_parameters[filters][premium]= false | true | all`

If you set this filter to any value (true/false/all), it should fix the problem.

See FAQ: 
https://github.com/adobe/stock-api-docs/blob/master/docs/15-faq.md#why-are-there-more-search-results-returned-than-the-limit-value 

And Search API reference:
https://github.com/adobe/stock-api-docs/blob/master/docs/api/11-search-reference.md#url-parameters

**Comment by sidolov** [comment]
I believe this issue already resolved, just need to re-check it

**Comment by sivaschenko** [comment]
The issue cannot be reproduced if the premium parameter is set. It is set to `ALL` by default in the integration: https://github.com/magento/adobe-stock-integration/blob/1161ab3a5b23e148c4e0603edb3c8af14726eb33/AdobeStockClient/Model/SearchParametersProvider/Premium.php#L23
