### ISSUE TITLE
Some images on the grid are not correctly aligned if open Preview in resized browser, and then maximize the web browser 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#972]
### Preconditions (*)
Magento 2.3.5-develop
Adobe-Stock-Integration 1.0.1-release

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. **(Key step )** Resize your web browser so it's on the half of the screen, for example
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** and click on any image, so the Preview is displayed
4. Resize the web browser on the whole screen by double click on web browsers title bar 
![grid2](https://user-images.githubusercontent.com/45624059/74940717-8403ea80-53fa-11ea-9d2f-8bb5d9aa71af.gif)

### Expected result (*)
All the images on the grid are properly aligned  

### Actual result (*)
Some images in the grid are not correctly aligned
![grid_align](https://user-images.githubusercontent.com/45624059/74941506-cf6ac880-53fb-11ea-9f37-714edd5e1d20.png)

**Comment by drpayyne** [comment]
Related to: https://github.com/magento/adobe-stock-integration/issues/824

**Comment by Nazar65** [comment]
PR created at M2 repo https://github.com/magento/magento2/pull/28366
