### ISSUE TITLE
Possible to switch to a whole div using TAB key 

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#973]
### Preconditions (*)
Magento 2.3.5-develop
Adobe-Stock-Integration 1.0.1-release

1. Installed Magento with Adobe Stock Integration
2. Select Enabled Adobe Stock- Yes in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Do **NOT** configure Api Key and Client secret

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** 
4. Switch between controllers using TAB key on keyboard

### Expected result (*)
The whole div should not be selected as it is not a button or a field. The link to _Configuration → System → Adobe Stock Integration_ should be selected
![tab_link](https://user-images.githubusercontent.com/45624059/74974980-df4fd000-542e-11ea-9445-63013a4c921a.png)

### Actual result (*)
At about tens switch, the whole _Failed to authenticate to Adobe Stock API.
Please correct the API credentials in Configuration → System → Adobe Stock Integration._ div is selected
![tab_please_correct](https://user-images.githubusercontent.com/45624059/74974715-6c465980-542e-11ea-8311-76abe8cf8d33.png) 
Hitting Enter key doesn't do anything

**Comment by drpayyne** [comment]
Hi @chalov-anton, thanks for reporting the issue. Pressing enter key when the link is focussed does actually work for me and it takes me to the Admin Configuration panel. 

@sivaschenko, is the `div.masonry-image-grid` supposed to have `tabindex=-1`? It currently has 0 as its value. The `tabindex=0` property was added by me as part of https://github.com/magento/magento2/pull/25991.

**Comment by chalov-anton** [comment]
Hello @drpayyne 

Yes, pressing Enter key, when the focus is on _Configuration → System → Adobe Stock Integration_, **does work**
It, obviously, doesn't work when the whole div is selected. There is no purpose of focusing (selecting) the whole div
