### ISSUE TITLE
Impossible to 'Save Preview' or 'License and Save'. An "UncaughtType Error" appears

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#979]
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
![enhansedMG](https://user-images.githubusercontent.com/45624059/75229948-9b0c5900-57bb-11ea-83d3-d150e4ae3db8.png)

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** and click on any image, so the Preview is displayed
4. Click **Save Preview**, and **Confirm** File Name
5. Open dev console in the web browser

### Expected result (*)
The image preview is saved to Media Gallery, no errors appear in browsers dev console 

### Actual result (*)
An :negative_squared_cross_mark: _UncaughtType Error_ appears, the image **preview is not saved** to Media Gallery
```
actions.js:156 Uncaught TypeError: Cannot read property 'activeNode' of undefined
    at UiClass.save (actions.js:156)
    at UiClass.<anonymous> (actions.js:122)
    at $.<computed>.<computed>.closeModal (prompt.js:164)
    at $.<computed>.<computed>.closeModal (jquery-ui-1.9.2.js:432)
    at HTMLButtonElement.dispatch (jquery.js:5232)
    at HTMLButtonElement.elemData.handle (jquery.js:4884)
save @ actions.js:156
(anonymous) @ actions.js:122
closeModal @ prompt.js:164
(anonymous) @ jquery-ui-1.9.2.js:432
dispatch @ jquery.js:5232
elemData.handle @ jquery.js:4884
```
![uncought_type_error](https://user-images.githubusercontent.com/45624059/75230584-909e8f00-57bc-11ea-8960-8de2e552cb94.png)

### Additional info,

The same result if attempt to **License and Save** an image
![license](https://user-images.githubusercontent.com/45624059/75231202-ba0bea80-57bd-11ea-8933-24d72573ce89.png)

**Comment by sivaschenko** [comment]
Hi @mmezhensky this issue is rather not a bug but missing implementation for the new Media Gallery.

The implementation was meant to be introduced in:
https://github.com/magento/adobe-stock-integration/issues/913
https://github.com/magento/adobe-stock-integration/issues/910

But they are dependent on https://github.com/magento/adobe-stock-integration/issues/912 (as that is the part of save functionality)

Would you like to first work on https://github.com/magento/adobe-stock-integration/issues/912 instead of this issue?

**Comment by mmezhensky** [comment]
Hi @sivaschenko 

Thanks, 
yes, I will do it

**Comment by chalov-anton** [comment]
Hello @mmezhensky 

Is there any progress with this?

Thank you

**Comment by mmezhensky** [comment]
Hi @chalov-anton 

Yes, I think this will work after fixed this #913 issue (PR - https://github.com/magento/adobe-stock-integration/pull/1111)

Thank you!

**Comment by sivaschenko** [comment]
Hi @mmezhensky the https://github.com/magento/adobe-stock-integration/pull/1111 is merged. Thank you!

**Comment by lenaorobei** [comment]
@chalov-anton could you please check of this issue is still reproducible?

**Comment by chalov-anton** [comment]
@lenaorobei The issue is not reproducible from Content - Pages... So we can close it.
It is reproducible on Standalone Media Gallery, but there is an already created PR https://github.com/magento/adobe-stock-integration/pull/1149
