### ISSUE TITLE
The image that has no "More from this series" and "More from this model", can't be found via Search by keywords

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#994]
I found that the images that do not have _"More from this series"_ and _"More from this model"_, can't be found via **Search by keywords**

### Preconditions (*)
Magento 2.3.5-develop
Adobe-Stock-Integration 1.0.1-release

1. Installed Magento with Adobe Stock Integration
2. Select Enabled Adobe Stock- Yes in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** 
4. From the grid find an image that has no _"More from this series"_ and _"More from this model"_ when Preview
5. Copy the file number
![file_number](https://user-images.githubusercontent.com/45624059/75550111-cef4b200-5a39-11ea-910d-d231b3c89879.png)
and paste it into the _Search by keyword_ field. Click **Search**  
![search_by_keywords](https://user-images.githubusercontent.com/45624059/75551145-2b58d100-5a3c-11ea-8873-198164a89ec1.png)

### Expected result (*)
The image is found

### Actual result (*)
The image is not found. _We could not find any records_ is displayed
![#search](https://user-images.githubusercontent.com/45624059/75551017-e6cd3580-5a3b-11ea-8ce0-bff9a18054ac.gif)

### Additional info
- image File numbers from my case: _325535445_ _324844990_

**Comment by chalov-anton** [comment]
Might be related to https://github.com/magento/adobe-stock-integration/pull/818

**Comment by lenaorobei** [comment]
@chalov-anton is this issue still reproducible?
